### PR TITLE
dd: allow skipping and seeking in FIFOs

### LINKED ISSUE #3321: dd: seek should cause a read from named pipe but doesn't
Steps to reproduce:

First, create a named pipe:
```
$ mkfifo tape
```

In one shell, invoke GNU `dd` to copy one block of zeros to the named pipe.
```
$ dd count=1 if=/dev/zero of=tape
```
This process will wait until another process reads from the named pipe.

In a second shell, invoke GNU `dd` to copy nothing but seek by one block in the named pipe.
```
$ dd count=0 seek=1 of=tape
```
This second command will terminate successfully almost immediately, presenting the following output:
```
0+0 records in
0+0 records out
0 bytes copied, 0.000242781 s, 0.0 kB/s
```
And the process in the first shell will also terminate because bytes have now been read from the named pipe. It will print the following:
```
1+0 records in
1+0 records out
512 bytes copied, 0.000450248 s, 1.1 MB/s
```
(512 is the default block size.) The logic here is that the second process attempted to simulate a seek by reading from the named pipe.

Now try using uutils `dd` in the first shell and GNU `dd` in the second. The first process will terminate with an error
```
$ ./target/release/dd count=1 if=/dev/zero of=tape
./target/release/dd: failed to seek in output file: Illegal seek
```
and the second will wait indefinitely.

Finally, try using GNU `dd` in the first shell and uutils `dd` in the second. Both processes will wait indefinitely.

This issue comes from the GNU test case `tests/dd/no-allocate.sh`.

### PR DESCRIPTION
**Pull request by jfinkels**
First, this pull request creates a `Source` enum and simplifies the `Input` struct in `dd`, mirroring pull request #4134 that introduced the `Dest` enum and a simplified `Output` struct. Second, this pull request adds support seeking in FIFOs given as either input or output (or both). For example, `dd seek=1 of=fifo` and `dd skip=1 if=fifo` will now work.

This should cause GNU test suite file `tests/dd/no-allocate.sh` to change from `ERROR` to `FAIL` status.

Fixes #3321.

### CODE REVIEW

**Comment by jfinkels** [comment]
Well, there's a few platform-compatibility issues I'll need to work out, but this is good news:

> Congrats! The gnu test tests/dd/no-allocate is no longer ERROR!

File: src/uu/dd/src/dd.rs [hunk 1]
```diff
@@ -770,40 +884,22 @@ pub fn uumain(args: impl uucore::Args) -> UResult<()> {
...
-                let filename = stdout_canonicalized();
-                let o = Output::new_file(Path::new(&filename), &settings)?;
-                o.dd_out(i).map_err_context(|| "IO error".to_string())
-            } else {
-                let o = Output::new_stdout(&settings)?;
-                o.dd_out(i).map_err_context(|| "IO error".to_string())
-            }
+    let i = match settings.infile {
+        #[cfg(any(target_os = "linux", target_os = "android"))]
+        Some(ref outfile) if is_fifo(outfile) => Input::new_fifo(Path::new(&outfile), &settings)?,
```
Comment (tertsdiepraam) [inline src/uu/dd/src/dd.rs:889]: Should this be infile?

**Review by tertsdiepraam — COMMENTED** [review]
Love where this is going!

File: src/uu/dd/src/dd.rs (hunk 1 above)
Comment (jfinkels) [reply src/uu/dd/src/dd.rs:889]: yes, it's a copy-and-paste error

**Comment by jfinkels** [comment]
Looks like something is not working right on macos:
```
2022-11-20T20:44:52.4512090Z test test_dd::test_seek_output_fifo has been running for over 60 seconds
2022-11-20T20:44:53.4303380Z test test_dd::test_skip_input_fifo has been running for over 60 seconds
```
What do you think about just skipping those two tests on macos and opening a new issue requesting an implementation that works on macos? I don't have a Mac computer so it's hard for me to debug these issues.

File: src/uu/dd/src/dd.rs [hunk 2]
```diff
@@ -88,30 +88,105 @@ impl Num {
...
+/// Data sources.
+enum Source {
+    /// Input from stdin.
+    Stdin(Stdin),
+
+    /// Input from a file.
+    File(File),
+
+    /// Input from a named pipe, also known as a FIFO.
+    #[cfg(any(target_os = "linux", target_os = "android"))]
```
Comment (tertsdiepraam) [inline src/uu/dd/src/dd.rs:100]: Is the problem not just that this should be Mac too?

Comment (tertsdiepraam) [reply src/uu/dd/src/dd.rs:100]: Or maybe it should be cfg(unix)?

Comment (jfinkels) [reply src/uu/dd/src/dd.rs:100]: You may be right. I think I was trying to match a `#[cfg]` guard that was already in the code (around `make_linux_iflags()`, etc.) but it was probably unnecessary.

File: tests/by-util/test_dd.rs [hunk 3]
```diff
@@ -1394,3 +1396,69 @@ fn test_sync_delayed_reader() {
...
+        .stderr(Stdio::piped())
+        .spawn()
+        .expect("failed to execute child process");
+
+    ts.ucmd()
+        .args(&["count=0", "seek=1", "of=fifo", "status=noxfer"])
+        .succeeds()
+        .stderr_only("0+0 records in\n0+0 records out\n");
+
+    let output = child.wait_with_output().unwrap();
```
Comment (jfinkels) [inline tests/by-util/test_dd.rs:1427]: If pull request #4136 gets merged, that would allow me to make these tests more concise.

**Comment by jfinkels** [comment]
I tried getting the macos build to succeed using @tertsdiepraam's suggestion, but it doesn't seem to work.

**Comment by jfinkels** [comment]
> I think the dd_out should also just become a free function dd, but that's not high priority.

Great minds think alike; I have such a branch on my local machine but it depends on this branch, so I was waiting until this is merged.

File: tests/by-util/test_dd.rs (hunk 3 above)
Comment (jfinkels) [reply tests/by-util/test_dd.rs:1479]: I think I was wrong when I made this comment. The `child` process comes from `Command`, not `UCommand`, so I don't think any changes can be made here at the moment.

**Comment by jfinkels** [comment]
I skipped the tests for this feature on macos and freebsd because I wasn't sure how to make the implementation work.

File: tests/by-util/test_dd.rs (hunk 3 above)
Comment (tertsdiepraam) [reply tests/by-util/test_dd.rs:1479]: You could use `ts.cmd` to make it a `UCommand`, but it's not a high priority.

File: src/uu/dd/src/dd.rs [hunk 4]
```diff
@@ -90,30 +92,106 @@ impl Num {
...
+    #[cfg(unix)]
+    fn new_fifo(filename: &Path, settings: &'a Settings) -> UResult<Self> {
+        let mut opts = OpenOptions::new();
+        opts.read(true);
+        #[cfg(any(target_os = "linux", target_os = "android"))]
+        opts.custom_flags(make_linux_iflags(&settings.iflags).unwrap_or(0));
+        let mut src = Source::Fifo(opts.open(filename)?);
+        if settings.skip > 0 {
+            src.skip(settings.skip)?;
+        }
```
Comment (tertsdiepraam) [inline src/uu/dd/src/dd.rs:193]: Would it make sense to extract this? It appears in all the `new_*` functions.

**Review by tertsdiepraam — APPROVED** [review]
Excellent! Just one nit

File: src/uu/dd/src/dd.rs (hunk 4 above)
Comment (jfinkels) [reply src/uu/dd/src/dd.rs:193]: Do you mean to factor these three lines out of the `new_*` functions into a new helper function and call that function in each of the three places? If so, I don't think it offers much benefit but I can do that if you it seems better to you.

Or do you mean to move this functionality out to the calling code so that it appears after the call to `new_*()`? I think I tried a design like that when I was first working on this pull request, but I no longer remember if it worked :).

Comment (tertsdiepraam) [reply src/uu/dd/src/dd.rs:193]: Alright, nevermind. It's not that important.
