### PR TITLE
head: fix overflow errors

### LINKED ISSUE #7166: head: errors on very large argument to -c but shouldn't
Environment: Ubuntu 20.04, uutils `main` branch (git commit d39dcad47ca4d9fa96e8f8132b4d1c298f1f7753), GNU coreutils v9.6.3-3189c-dirty.

Steps to reproduce:
```
head --bytes=-18446744073709551616000 < /dev/null
```

What happens now: uutils `head` complains that the number is too large:
```
head: invalid number of bytes: '18446744073709551616000': Value too large for defined data type
```

What I expected to happen: GNU `head` terminates successfully with no output.

Notes: this is causing a failure in the GNU test file `tests/head/head-c.sh`.

### PR DESCRIPTION
**Pull request by Qelxiros**
closes #7166

Also changes number parsing to allow for a leading `+`, in line with GNU `head`

### CODE REVIEW

**Comment by jfinkels** [comment]
I don't think this quite fixes the linked issue. I tried compiling `uu_head` on this branch and the error message is still displayed:
```
$ ./target/debug/head --bytes=-18446744073709551616000 < /dev/null
./target/debug/head: invalid number of bytes: '18446744073709551616000': Value too large for defined data type
```

**Comment by Qelxiros** [comment]
Should be fixed now.

**Comment by Qelxiros** [comment]
I don't have an easy way to test GNU behavior on 32-bit platforms, so if commit d887038 is a regression, let me know.

File: src/uu/head/src/head.rs [hunk 1]
```diff
@@ -288,13 +282,7 @@ fn read_n_lines(input: &mut impl io::BufRead, n: u64, separator: u8) -> io::Resu
 }
 
 fn catch_too_large_numbers_in_backwards_bytes_or_lines(n: u64) -> Option<usize> {
```
Comment (jfinkels) [inline src/uu/head/src/head.rs:284]: Let's just remove this helper function entirely and use the `usize::try_from(n).ok()` directly where needed.

**Review by jfinkels — APPROVED** [review]
> Congrats! The gnu test tests/head/head-c is no longer failing!

Great!

**Comment by jfinkels** [comment]
Looks good to me, thanks.
