### PR TITLE
fix: handle /dev/full write errors gracefully

### LINKED ISSUE #9769: Many utils: command subcommand --arg > /dev/full panics
```
cat --version > /dev/full

thread 'main' (13171) panicked at src/uucore/src/lib/mods/error.rs:751:28:
called `Result::unwrap()` on an `Err` value: Os { code: 28, kind: StorageFull, message: "No space left on device" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by naoNao89**
hehe, i think this very simple fix if correct 😅

just changed `.unwrap()` to `let _ =` in error.rs. now utilities don't panic when writing to /dev/full, they exit gracefully like GNU coreutils does.

one line fix + regression test. affects 20+ utilities.

Fixes #9769

### CODE REVIEW

File: src/uucore/src/lib/mods/error.rs [hunk 1]
```diff
@@ -748,7 +748,7 @@ impl Error for ClapErrorWrapper {}
 // This is abuse of the Display trait
 impl Display for ClapErrorWrapper {
     fn fmt(&self, _f: &mut Formatter<'_>) -> Result<(), std::fmt::Error> {
-        self.error.print().unwrap();
+        let _ = self.error.print();
```
Comment (sylvestre) [inline src/uucore/src/lib/mods/error.rs:753]: please add a comment explaining why

Comment (naoNao89) [reply src/uucore/src/lib/mods/error.rs:753]: oke
