### PR TITLE
tail: report PermissionDenied instead of No such file when metadata f…

### LINKED ISSUE #10193: tail: exists precheck masks permission errors
## Component
`tail`

## Description
uutils checks `path.exists()` before opening the file. `Path::exists()` returns false on metadata errors (including EACCES), so a permission error is reported as “No such file or directory” and the open is never attempted. GNU `tail` attempts the open and reports the real errno.

## Test / Reproduction Steps
```bash
# As root:
mkdir /tmp/noexec
echo secret > /tmp/noexec/file
chmod 000 /tmp/noexec

# As unprivileged user:
tail -n 1 /tmp/noexec/file
# GNU: "tail: cannot open '/tmp/noexec/file' for reading: Permission denied"
# uutils: "tail: cannot open '/tmp/noexec/file' for reading: No such file or directory"
```

## Impact
Incorrect diagnostics and follow/retry behavior can break scripts that rely on accurate error reporting.

### PR DESCRIPTION
**Pull request by RedNhight**
Fixes #10193

Before:
  tail prints "No such file" on lack of permissions.

After:
  tail attempts open() and prints correct Permission denied.

### CODE REVIEW

**Comment by oech3** [comment]
Thankyou for 1st contrib. Would you add test to https://github.com/uutils/coreutils/blob/main/tests/by-util/test_tail.rs ?

**Comment by RedNhight** [comment]
> Thankyou for 1st contrib. Would you add test to https://github.com/uutils/coreutils/blob/main/tests/by-util/test_tail.rs ?

Yes, sure!

**Comment by rglKali** [comment]
lgtm!

**Comment by cakebaker** [comment]
Can you please run `cargo fmt` and `cargo clippy`? Thanks.

**Comment by RedNhight** [comment]
> Can you please run `cargo fmt` and `cargo clippy`? Thanks.

Yes, sure!

**Comment by RedNhight** [comment]
> Can you please run `cargo fmt` and `cargo clippy`? Thanks.

Done!

File: tests/by-util/test_tail.rs [hunk 1]
```diff
@@ -574,6 +574,37 @@ fn test_follow_non_utf8_bytes() {
...
+        return;
+    }
+
+    let (at, mut ucmd) = at_and_ucmd!();
+
+    at.mkdir("noexec");
+    let mut f = at.make_file("noexec/file");
+    use std::io::Write;
+    writeln!(f, "secret").unwrap();
+    f.flush().unwrap();
```
Comment (cakebaker) [inline tests/by-util/test_tail.rs]: I would use `touch` as you don't care about the file content in this test:
```suggestion
    at.touch("noexec/file");
```

File: tests/by-util/test_tail.rs [hunk 2]
```diff
@@ -574,6 +574,37 @@ fn test_follow_non_utf8_bytes() {
...
+    fs::set_permissions(&dir, fs::Permissions::from_mode(0o000)).unwrap();
+
+    let result = ucmd.arg("noexec/file").run();
+
+    fs::set_permissions(&dir, fs::Permissions::from_mode(0o700)).unwrap();
+
+    // Asserts that the result is incorrect.
+    result.failure();
+    let err = result.stderr_str();
+    assert!(err.contains("Permission denied"));
```
Comment (cakebaker) [inline tests/by-util/test_tail.rs]: You can simplify this snippet a bit with:

```suggestion
    ucmd.arg("noexec/file")
        .fails()
        .stderr_contains("Permission denied");

    fs::set_permissions(&dir, fs::Permissions::from_mode(0o700)).unwrap();
```

Comment (RedNhight) [reply tests/by-util/test_tail.rs]: Thanks! You're right. This is way better!

**Comment by cakebaker** [comment]
Thanks for your PR!
