### PR TITLE
echo: fixed double hyphen as argument

### LINKED ISSUE #7558: echo: "--" duplicated when passed as non-first argument
GNU:
```sh
$ /bin/echo a -- b
a -- b
```

uutils:
```sh
$ /bin/uu-echo a -- b
a -- -- b

# (Same result on the `main` branch with `cargo run --features unix -- echo a -- b`).
```

Working on a fix.

### PR DESCRIPTION
**Pull request by cerdelen**
Added check to only insert addition double hyphen if at start of arguments to correctly prepend addition hyphens for clap as well as additional test case

### CODE REVIEW

File: src/uu/echo/src/echo.rs [hunk 1]
```diff
@@ -27,12 +27,10 @@ mod options {
 // follows. In order to use '--' as a value, we have to inject an additional '--'
 fn handle_double_hyphens(args: impl uucore::Args) -> impl uucore::Args {
     let mut result = Vec::new();
-    let mut is_first_double_hyphen = true;
 
-    for arg in args {
-        if arg == "--" && is_first_double_hyphen {
+    for (i, arg) in args.enumerate() {
+        if arg == "--" && i == 1 {
```
Comment (sylvestre) [inline src/uu/echo/src/echo.rs:32]: please add a comment to explain what is it

**Comment by sylvestre** [comment]
> GNU test failed: tests/misc/echo. tests/misc/echo is passing on 'main'. Maybe you have to rebase?

seems that it regressed upstream tests

File: src/uu/echo/src/echo.rs (hunk 1 above)
Comment (cerdelen) [reply src/uu/echo/src/echo.rs]: added a comment

**Comment by cerdelen** [comment]
i rebased main and pushed a comment ... on my machine no tests are failing i hope the error was that i hadnt rebased main into my fork before pushing (?)

**Comment by Expertcoderz** [comment]
This seems to have the same bug as my PR (#7559):

```sh
$ cargo run -q echo -n -e -- 'foo\n'
foo
```

The double hyphen gets eaten up if it is given immediately after a flag that is recognized by Clap. Solving this problem could be less straightforward than it seems... :(

**Comment by Expertcoderz** [comment]
There's a limitation in your fix in a8d6780a40687337f83bb72a6424a733495f7941:

```sh
# doesn't work with combined flags
$ cargo run -q echo -eE -- hi
hi
```

**Comment by cerdelen** [comment]
mhh ... i could modify the is_echo_flag to manually go through the givven string and check if index 0 is '-' and then any following char is either 'e' 'E' 'n' 

would this be too much of code or acceptable?

i see that with the gnu echo you can even give as an input flags such as '-nneE' which doesnt work as clap will throw an error `error: the argument '-n' cannot be used multiple times`

should i already limit checks at index 4 t hen as multiple flags are not allowed and will be caught later by clap or ignore that?

**Comment by cerdelen** [comment]
i also discovered that `echo - -n --` should print `-n --` which i am not sure where that error comes from, if that is part of clap or if that is from my implementation ... i will try to investigate a little bit more

**Comment by blyxxyz** [comment]
POSIX says to not apply any of the normal options processing and only check if the first arg is -n: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/echo.html

GNU is more complicated but I think the same principle applies: we shouldn't use clap to parse at all. Maybe we can use it to generate the help message but we need very simple parsing so we're better off doing it ourselves instead of trying to coerce clap.

> mhh ... i could modify the is_echo_flag to manually go through the given string and check if index 0 is '-' and then any following char is either 'e' 'E' 'n'

Like that, and then you can manually set `bool`s as you go so you no longer even need clap.

**Comment by Expertcoderz** [comment]
> mhh ... i could modify the is_echo_flag to manually go through the given string and check if index 0 is '-' and then any following char is either 'e' 'E' 'n'
> 
> would this be too much of code or acceptable?

Won't work with cases such as `echo -enonsense` which starts with `-e` but is recognized simply as a regular argument by GNU echo.

> i see that with the gnu echo you can even give as an input flags such as '-nneE' which doesnt work as clap will throw an error `error: the argument '-n' cannot be used multiple times`

This is probably why the best approach is to just not use clap at all for implementing echo. It seems to be complicating things *a whole lot*.

> should i already limit checks at index 4 t hen as multiple flags are not allowed and will be caught later by clap or ignore that?

Yeah, makes sense to do that.

**Comment by cerdelen** [comment]
I would suggest that i fix the problem at hand and removing clap would be a new issue all together?

i found even more cases where flags are printed improperly compared to gnu coreutils

`echo - -neE` -> `-neE`
`cargo run echo - -neE` -> `- -neE`

`echo -gfew -n --` -> `-gfew -n --`
`cargo run -gfew -n --` -> 
error: unexpected argument '-g' found

  tip: to pass '-g' as a value, use '-- -g'

Usage: cargo run [OPTIONS] [ARGS]...

For more information, try '--help'.

**Comment by blyxxyz** [comment]
Huh, which version of echo are you on? For me it prints the `-`:
```console
$ /bin/echo - -neE
- -neE
$ /bin/echo --version
echo (GNU coreutils) 8.32
```

> `cargo run -gfew -n --`

I think the trick here is to use `cargo run -- -gfew -n --`. (The first `--` is only seen by `cargo run`.) `cargo run`'s option handling is pretty confusing but if you give it a `--` as early as possible you can put whatever afterward.

If in doubt you can also check with `target/debug/uu_echo`.

> I would suggest that i fix the problem at hand and removing clap would be a new issue all together?

That makes sense.

**Comment by cakebaker** [comment]
Thanks for your work on this issue, @cerdelen and @Expertcoderz !
