### PR TITLE
Fix military date parsing not adjusting date

### LINKED ISSUE #9775: Military timezone parsing shows incorrect date (1 day ahead)
GNU:
```
  $ TZ=UTC-5 /usr/bin/date -d "B" "+%F %T %Z"
  2025-12-22 03:00:00 UTC
```

  Rust:
  ```
$ TZ=UTC-5 ./target/debug/date -d "B" "+%F %T %Z"
  2025-12-23 03:00:00 UTC
```

  - GNU date: Shows December 22 with military timezone "B"
  - Rust date: Shows December 23 (1 day ahead) with same input
  - Pattern consistent across military timezones A, B, C - all show +1 day in Rust
  - Times are correct (04:00, 03:00, 02:00) but date is wrong

  Found with a fuzzer

### PR DESCRIPTION
**Pull request by cerdelen**
fixes #9775.

I fixed the bug described in this issue and also added regression tests. 

I am pretty sure that the unwrap i added is not okay but i am not sure what fallback date to use if the edgecases of the time is reached and would love for someone to give me some input.

### CODE REVIEW

File: src/uu/date/src/date.rs [hunk 1]
```diff
@@ -115,6 +115,13 @@ impl From<&str> for Rfc3339Format {
     }
 }
 
+#[derive(PartialEq, Debug)]
+enum DayDelta {
```
Comment (sylvestre) [inline src/uu/date/src/date.rs:124]: please add a rustdoc comment here

File: src/uu/date/src/date.rs [hunk 2]
```diff
@@ -305,11 +318,22 @@ pub fn uumain(args: impl uucore::Args) -> UResult<()> {
                     format!("{date_part} 00:00 {offset}")
                 };
                 parse_date(composed)
-            } else if let Some(total_hours) = military_tz_with_offset {
+            } else if let Some((total_hours, day_delta)) = military_tz_with_offset {
                 // Military timezone with optional hour offset
                 // Convert to UTC time: midnight + military_tz_offset + additional_hours
-                let date_part =
-                    strtime::format("%F", &now).unwrap_or_else(|_| String::from("1970-01-01"));
+                let date_part = match day_delta {
```
Comment (sylvestre) [inline src/uu/date/src/date.rs:342]: please add some comments to detail what it is about :)

Comment (cerdelen) [reply src/uu/date/src/date.rs:342]: Documented in newest commit

File: src/uu/date/src/date.rs (hunk 1 above)
Comment (cerdelen) [reply src/uu/date/src/date.rs:124]: Documented in newest commit

File: src/uu/date/src/date.rs [hunk 3]
```diff
@@ -115,6 +115,20 @@ impl From<&str> for Rfc3339Format {
     }
 }
 
+/// Indicates whether parsing a military timezone causes the date to remain the same, roll back to the previous day, or
+/// advance to the next day.
+/// This can occur when applying a military timezone with an optional hour offset crosses midnight
+/// in eihter direction.
```
Comment (sylvestre) [inline src/uu/date/src/date.rs]:
```suggestion
/// in either direction.
```

File: src/uu/date/src/date.rs [hunk 4]
```diff
@@ -305,11 +325,26 @@ pub fn uumain(args: impl uucore::Args) -> UResult<()> {
...
                 };
                 parse_date(composed)
-            } else if let Some(total_hours) = military_tz_with_offset {
+            } else if let Some((total_hours, day_delta)) = military_tz_with_offset {
                 // Military timezone with optional hour offset
                 // Convert to UTC time: midnight + military_tz_offset + additional_hours
-                let date_part =
-                    strtime::format("%F", &now).unwrap_or_else(|_| String::from("1970-01-01"));
+
+                // When calculating a military timezone with an optional hour offset, midgnight may
```
Comment (sylvestre) [inline src/uu/date/src/date.rs]:
```suggestion
                // When calculating a military timezone with an optional hour offset, midnight may
```

**Comment by cerdelen** [comment]
also fixes #9798

**Comment by sylvestre** [comment]
@cerdelen could you please update this PR with the test cases from https://github.com/uutils/coreutils/issues/9798 ?
thanks

File: src/uu/date/src/date.rs [hunk 5]
```diff
@@ -305,11 +325,26 @@ pub fn uumain(args: impl uucore::Args) -> UResult<()> {
...
+                    }
+                    DayDelta::Next => now
+                        .tomorrow()
+                        .and_then(|d| strtime::format("%F", &d))
+                        .unwrap_or_else(|_| String::from("1970-01-01")),
+                    DayDelta::Previous => now
+                        .yesterday()
+                        .and_then(|d| strtime::format("%F", &d))
+                        .unwrap_or_else(|_| String::from("1970-01-01")),
+                };
```
Comment (sylvestre) [inline src/uu/date/src/date.rs:346]: can probably simplified with something like:

```suggestion
                let format_date = |date: Option<Zoned>| -> String {
                    date.and_then(|d| strtime::format("%F", &d))
                        .unwrap_or_else(|_| String::from("1970-01-01"))
                };
                let date_part = match day_delta {
                    DayDelta::Same => format_date(Some(now)),
                    DayDelta::Next => format_date(now.tomorrow()),
                    DayDelta::Previous => format_date(now.yesterday()),
                };
```

Comment (cerdelen) [reply src/uu/date/src/date.rs:346]: tomorrow()/yesterday() return Result but i did implement this closure approach in the newest commit

**Comment by cerdelen** [comment]
> @cerdelen could you please update this PR with the test cases from #9798 ? thanks

line 1117 in file `tests/by-util/test_date.rs` already tests this explicitly for correct time

and i extended my test with this variation too to checks that the date is correct

**Comment by cerdelen** [comment]
@sylvestre is the 1 failing Pipeline maybe flakey. Its some test with 'more'? So i have to investigate this failed Pipeline or is it okay?

**Comment by sylvestre** [comment]
Don't hesitate to investigate :)
In a different pr

**Comment by cerdelen** [comment]
Is there anything else needed for this PR before it can be merged into the repository?

File: tests/by-util/test_date.rs [hunk 6]
```diff
@@ -1132,6 +1132,44 @@ fn test_date_military_timezone_with_offset_variations() {
...
+        ("m23", 0),
+        // midnight crossings with hour offsets to tomorrow
+        ("n23", 1),
+        ("y23", 1),
+    ];
+
+    for (input, day_delta) in test_cases {
+        let expected_date = today.checked_add_signed(Duration::days(day_delta)).unwrap();
+
+        let expected = format!("{}\n", expected_date.format("%F"),);
```
Comment (sylvestre) [inline tests/by-util/test_date.rs]:
```suggestion
        let expected = format!("{}\n", expected_date.format("%F"));
```

File: tests/by-util/test_date.rs [hunk 7]
```diff
@@ -1132,6 +1132,44 @@ fn test_date_military_timezone_with_offset_variations() {
...
+fn test_date_military_timezone_with_offset_and_date() {
+    use chrono::{Duration, Utc};
+
+    let today = Utc::now().date_naive();
+
+    let test_cases = vec![
+        ("m", -1), // M = UTC+12
+        ("a", -1), // A = UTC+1
+        ("n", 0),  // N = UTC-1
+        ("y", 0),  // N = UTC-12
```
Comment (sylvestre) [inline tests/by-util/test_date.rs]:
```suggestion
        ("y", 0),  // Y = UTC-12
```

File: src/uu/date/src/date.rs [hunk 8]
```diff
@@ -306,11 +326,24 @@ pub fn uumain(args: impl uucore::Args) -> UResult<()> {
...
                 // Convert to UTC time: midnight + military_tz_offset + additional_hours
-                let date_part =
-                    strtime::format("%F", &now).unwrap_or_else(|_| String::from("1970-01-01"));
+
+                // When calculating a military timezone with an optional hour offset, midnight may
+                // be crossed in either direction. `day_delta` indicates wether the date remains
+                // the same, moves to the previous day, or advances to the next day.
+                // Changing day can result in error, this closure will help handle these errors
+                // gracefully.
+                let format_date_closure = |date: Result<Zoned, _>| -> String {
```
Comment (sylvestre) [inline src/uu/date/src/date.rs]: Closure naming could be improved

File: src/uu/date/src/date.rs [hunk 9]
```diff
@@ -306,11 +326,24 @@ pub fn uumain(args: impl uucore::Args) -> UResult<()> {
...
                 parse_date(composed)
-            } else if let Some(total_hours) = military_tz_with_offset {
+            } else if let Some((total_hours, day_delta)) = military_tz_with_offset {
                 // Military timezone with optional hour offset
                 // Convert to UTC time: midnight + military_tz_offset + additional_hours
-                let date_part =
-                    strtime::format("%F", &now).unwrap_or_else(|_| String::from("1970-01-01"));
+
+                // When calculating a military timezone with an optional hour offset, midnight may
+                // be crossed in either direction. `day_delta` indicates wether the date remains
```
Comment (sylvestre) [inline src/uu/date/src/date.rs]:
```suggestion
                // be crossed in either direction. `day_delta` indicates whether the date remains
```

File: src/uu/date/src/date.rs [hunk 10]
```diff
@@ -160,11 +174,17 @@ fn parse_military_timezone_with_offset(s: &str) -> Option<i32> {
         _ => return None,
     };
 
+    let day_delta = match additional_hours - tz_offset {
```
Comment (sylvestre) [inline src/uu/date/src/date.rs:177]:
```suggestion
    let hours_from_today_midnight = match additional_hours - tz_offset {
```

File: src/uu/date/src/date.rs [hunk 11]
```diff
@@ -160,11 +174,17 @@ fn parse_military_timezone_with_offset(s: &str) -> Option<i32> {
...
+        h if h >= 24 => DayDelta::Next,
+        _ => DayDelta::Same,
+    };
+
     // Calculate total hours: midnight (0) + tz_offset + additional_hours
     // Midnight in timezone X converted to UTC
     let total_hours = (0 - tz_offset + additional_hours).rem_euclid(24);
 
-    Some(total_hours)
+    Some((total_hours, day_delta))
```
Comment (sylvestre) [inline src/uu/date/src/date.rs]:
```suggestion
    Some((total_hours, hours_from_today_midnight))
```

File: src/uu/date/src/date.rs [hunk 12]
```diff
@@ -306,11 +326,24 @@ pub fn uumain(args: impl uucore::Args) -> UResult<()> {
...
                 // Convert to UTC time: midnight + military_tz_offset + additional_hours
-                let date_part =
-                    strtime::format("%F", &now).unwrap_or_else(|_| String::from("1970-01-01"));
+
+                // When calculating a military timezone with an optional hour offset, midnight may
+                // be crossed in either direction. `day_delta` indicates whether the date remains
+                // the same, moves to the previous day, or advances to the next day.
+                // Changing day can result in error, this closure will help handle these errors
+                // gracefully.
+                let format_date = |date: Result<Zoned, _>| -> String {
```
Comment (sylvestre) [inline src/uu/date/src/date.rs]:
```suggestion
                let format_date_with_epoch_fallback = |date: Result<Zoned, _>| -> String {
```

File: src/uu/date/src/date.rs [hunk 13]
```diff
@@ -306,11 +326,24 @@ pub fn uumain(args: impl uucore::Args) -> UResult<()> {
...
+                    date.and_then(|d| strtime::format("%F", &d))
+                        .unwrap_or_else(|_| String::from("1970-01-01"))
+                };
+                let date_part = match day_delta {
+                    DayDelta::Same => format_date(Ok(now)),
+                    DayDelta::Next => format_date(now.tomorrow()),
+                    DayDelta::Previous => format_date(now.yesterday()),
```
Comment (sylvestre) [inline src/uu/date/src/date.rs]:
```suggestion
                    DayDelta::Same => format_date_with_epoch_fallback(Ok(now)),
                    DayDelta::Next => format_date_with_epoch_fallback(now.tomorrow()),
                    DayDelta::Previous => format_date_with_epoch_fallback(now.yesterday()),
```

File: src/uu/date/src/date.rs (hunk 10 above)
Comment (cerdelen) [reply src/uu/date/src/date.rs:177]: this is not hours from today midnight. Its the enum DayDelta which specifies if we should add 1 day to the date, remove 1 day or if its the same date. The hour from midnight today is calculated unchanged in line 185.

Comment (cerdelen) [reply src/uu/date/src/date.rs:177]: should i change the total hours variable to hours_from_today_midnight instead?

Comment (sylvestre) [reply src/uu/date/src/date.rs:177]: sure :)
thanks
