### PR TITLE
printf: fix printf sci notation round up

### LINKED ISSUE #3088: printf - Incorrect rounding behavior for scientific notation
`printf %e 99999999`

GNU prints `1.000000e+08`. Uutils prints `0.000000e+07`.

### PR DESCRIPTION
**Pull request by nickd0**
fixes #3088

update `round_terminal_digit`
- Return `bool` (along with pre- and post-decimal formatted strings) indicating if we have rounded in such a way that the decimal place, or mantissa for `%e/%E` format specifiers, should change

update `_round_str_from`
- Accept `before_dec: bool` argument indicating if the numeric string to be rounded is before or after decimal place. This is used to round a `9` to a `1` in the most significant position in a pre-decimal string.

This fixes similar cases for `printf` with `%e`, `%E`, and `%f`:
```shell
$ printf "%e\n" 0.99999999
1.000000e+00  # was 0.000000e-01

$ printf "%f\n" 99999.9999999
100000.000000  # was 00000.000000
```

I also noticed that `%g`/`%G` doesn't perform as expected, but I can open a separate issue for that if needed.
```shell
$ pritnf "%g\n" 99  # GNU
99

$ printf  "%g\n" 99  # uutils/coreutils
99.0
```

### CODE REVIEW

File: src/uucore/src/lib/features/tokenize/num_format/formatters/float_common.rs [hunk 1]
```diff
@@ -162,7 +164,11 @@ fn _round_str_from(in_str: &str, position: usize) -> (String, bool) {
         i -= 1;
         match c {
             '9' => {
-                rev.push('0');
+                if before_dec {
```
Comment (sylvestre) [inline src/uucore/src/lib/features/tokenize/num_format/formatters/float_common.rs:167]: please a comment explaining the why :)

**Comment by nickd0** [comment]
Added comments and updated for another case (documented above)!

**Comment by nickd0** [comment]
Having trouble replicating this test failure on a windows server 2019 virtual box, will dig into it a little more this weekend

**Review by jfinkels — APPROVED** [review]
