### PR TITLE
install: add missing directory chown

### LINKED ISSUE #4361: Wrong user+group for `uu-install -o $uid -g $gid -d dir/a/b`
## Issue

The `uu-install` implementation handles the argument combination of  `-o $uid -g $gid -d a/b/c` differently then `coreutils`.  Running `install -o $UID -g $GID -d dir/a/b` fails to set the permissions on the final directory (`b` in this case) where `coreutils` does.

## Example test cases

Arch Linux uses this in `makechrootpkg` which is broken by this. [Code for usage is here](https://github.com/heftig/devtools/blob/master/makechrootpkg.in#L160).

Versions
```
$ /usr/bin/uu-install --version
/usr/bin/uu-install 0.0.17
$ /usr/bin/install --version | head -n1
install (GNU coreutils) 9.1
```

Simple test case
```
$ sudo /usr/bin/install -o 1000 -g 1000 -d core/a/b
$ sudo /usr/bin/uu-install -o 1000 -g 1000 -d uu/a/b

$  exa -lng --tree core uu

drwxr-xr-x - 0    0    13 Feb 18:28 core
drwxr-xr-x - 0    0    13 Feb 18:28 └── a
drwxr-xr-x - 1000 1000 13 Feb 18:28    └── b

drwxr-xr-x - 0    0    13 Feb 18:28 uu
drwxr-xr-x - 0    0    13 Feb 18:28 └── a
drwxr-xr-x - 0    0    13 Feb 18:28    └── b
```

Note that `coreutils` implementation sets the requested permissions of `core/a/b` to the uid+gid passed in but `uu-install` does not.

### PR DESCRIPTION
**Pull request by kylemanna**
* Re-factor the copy function `chown` into a function that can be re-used.
* Fix bug where the group overwrote the user.
* Add `chown` compatibility to follow GNU coreutils.
* Reduce two `chown` calls to a single syscall only when needed.
* Fixes #4361

Not sure how to test this though.  Can the CI/CD server change owners?  I assume this will break most test setups.

Manually tested for now.

### CODE REVIEW

File: src/uu/install/src/install.rs [hunk 1]
```diff
@@ -626,6 +628,62 @@ fn copy_files_into_dir(files: &[PathBuf], target_dir: &Path, b: &Behavior) -> UR
...
+/// # Errors
+///
+/// If the owner or group are invalid or copy system call fails, we print a verbose error and
+/// return an empty error value.
+///
+fn chown_optional_user_group(path: &Path, b: &Behavior) -> UResult<()> {
+    let owner = if !b.owner.is_empty() {
+        match usr2uid(&b.owner) {
+            Ok(u) => Some(u),
+            _ => return Err(InstallError::NoSuchUser(b.owner.clone()).into()),
```
Comment (tertsdiepraam) [inline src/uu/install/src/install.rs:648]: Can we create tests for the lines that codecov reports are untested?

**Review by tertsdiepraam — COMMENTED** [review]
Very clean! I just have a couple of small questions/suggestions.

File: src/uu/install/src/install.rs [hunk 2]
```diff
@@ -466,6 +466,8 @@ fn directory(paths: &[String], b: &Behavior) -> UResult<()> {
                 uucore::error::set_exit_code(1);
                 continue;
             }
+
+            chown_optional_user_group(path, b)?;
```
[the remark this answers is not in the document]
Comment (kylemanna) [reply src/uu/install/src/install.rs:470]: Good point, I'll mimick the chmod behavior and set the exit code to 1, print an error and continue to the next file.

File: src/uu/install/src/install.rs (hunk 1 above)
Comment (kylemanna) [reply src/uu/install/src/install.rs]: Tests added and error strings corrected to match GNU coreutils for invalid users.

Would like to test the operation, but unclear how to `chown` as an unprivileged user on the build server.  Probably not feasible?

File: src/uu/install/src/install.rs [hunk 3]
```diff
@@ -466,6 +489,12 @@ fn directory(paths: &[String], b: &Behavior) -> UResult<()> {
                 uucore::error::set_exit_code(1);
                 continue;
             }
+
+            if chown_optional_user_group(path, b).is_err() {
+                // Error messages are printed by the chown_optional_user_group function!
```
Comment (tertsdiepraam) [inline src/uu/install/src/install.rs:494]: This is not entirely true. The `InstallError::MetadataFailed` is not printed. I'd make `chown_optional_user_group` not print any errors and then use the [`show_if_err!`](https://docs.rs/uucore/latest/uucore/macro.show_if_err.html) macro here:
```rust
show_if_err!(chown_optional_user_group(path, b));
```
Alternatively, if you want to be a bit more explicit:
```rust
if Err(e) = chown_optional_user_group(path, b) {
    show!(e);
}
```
(these are equivalent, because that's what `show_if_err` expands to)

`show!` will print the message and set the exit code.

File: src/uu/install/src/install.rs [hunk 4]
```diff
@@ -391,21 +391,44 @@ fn behavior(matches: &ArgMatches) -> UResult<Behavior> {
...
             .get_one::<String>(OPT_GROUP)
             .map(|s| s.as_str())
             .unwrap_or("")
-            .to_string(),
+            .to_string();
+
+    let group_id = if !group.is_empty() {
+        match grp2gid(&group) {
+            Ok(g) => Some(g),
+            _ => return Err(InstallError::InvalidGroup(group.clone()).into()),
```
Comment (tertsdiepraam) [inline src/uu/install/src/install.rs:419]: Nit: let's be explicit about `Err(_)` here, instead of `_` (and also in the other match)

File: src/uu/install/src/install.rs (hunk 1 above)
Comment (tertsdiepraam) [reply src/uu/install/src/install.rs]: Yeah, I think you're right that's not possible at the moment.

File: src/uu/install/src/install.rs (hunk 4 above)
Comment (kylemanna) [reply src/uu/install/src/install.rs:419]: Agreed, updated both to be more explicit.  Originally left it as it was moved from the original section.

File: src/uu/install/src/install.rs (hunk 3 above)
Comment (kylemanna) [reply src/uu/install/src/install.rs]: Followed your advice and added an `InstallError::ChownFailed` with the error message. Please take a look.

File: src/uu/install/src/install.rs [hunk 5]
```diff
@@ -626,6 +653,44 @@ fn copy_files_into_dir(files: &[PathBuf], target_dir: &Path, b: &Behavior) -> UR
...
+        };
+
+        match wrap_chown(path, &meta, b.owner_id, b.group_id, false, verbosity) {
+            Ok(n) => {
+                if !n.is_empty() {
+                    return Err(InstallError::ChownFailed(path.to_path_buf(), n).into());
+                }
+            }
+            Err(e) => return Err(InstallError::ChownFailed(path.to_path_buf(), e).into()),
+        }
```
Comment (tertsdiepraam) [inline src/uu/install/src/install.rs:688]: Nit: This can be condensed a little:
```suggestion
        match wrap_chown(path, &meta, b.owner_id, b.group_id, false, verbosity) {
            Ok(n) if n.is_empty()  => {},
            Ok(e) | Err(e) => return Err(InstallError::ChownFailed(path.to_path_buf(), e).into()),
        }
```

More importantly, however, why are you treating the `Ok` case as an error? Maybe it should just be printed right here? I think your current implementation will set the exit code to 1 on a successful chown, which doesn't seem correct.

**Review by tertsdiepraam — COMMENTED** [review]
I like where this is headed! Just one question

File: src/uu/install/src/install.rs (hunk 5 above)
Comment (kylemanna) [reply src/uu/install/src/install.rs]: Tried to leave this as it was, but it doesn't make sense as an error. The main driver here for `wrap_chown()` printing informative messages is the verbosity passed in which is `VerbosityLevel::Normal`.  However, the current implementation of `wrap_chown()` never returns any strings.

When comparing with GNU `install`, it doesn't print `chown` operations with or with the verbose flag.

I updated it to be more explicit and `println!(msg)` if `b.verbose` and `wrap_chown()` returns a string in the future.

Please take a look now.

I might argue we should disregard all verbose `wrap_chown()` output to better mimick GNU Coreutils, but mostly trying to maintain previous behavior so I don't break something else that's not tested.

Comment (tertsdiepraam) [reply src/uu/install/src/install.rs]: > When comparing with GNU install, it doesn't print chown operations with or with the verbose flag.

Oh my bad then. You're absolutely right: in that case we should be compatible and not print anything.

**Comment by kylemanna** [comment]
> Not sure how to test this though. Can the CI/CD server change owners? I assume this will break most test setups.


Passing thought: it's probably possible to `chown`/`chrgp` by running `fakeroot cargo ...` for the tests.  This probably requires re-organizing tests that must run in `fakeroot` to another test suite or something to that we don't require users running unit-tests to have `fakeroot` installed.

File: src/uu/install/src/install.rs (hunk 5 above)
Comment (kylemanna) [reply src/uu/install/src/install.rs]: Currently it doesn't print anything unless `wrap_chown` is changed and that'd be a bug there with mishandling the verbosity.

This is ready for merge if you're happy.

**Comment by kylemanna** [comment]
Thanks!
