### PR TITLE
kill: fix the fail to use only least significant bits to identify signal with -l

### LINKED ISSUE #7218: kill: fails to use only least significant bits to identify signal with -l
Environment: Ubuntu 24.04, uutils `main` branch (git commit 2430e2a396d5f5ae29413081b065a4503245839b), GNU coreutils v9.6.8-fbfd88-dirty

Steps to reproduce:
```
# 143 is 15 + 128, and signal number 15 is SIGTERM.
kill -l 143
```

What happens now: uutils `kill` displays an error message that the signal 143 is unknown:
```
kill: unknown signal name '143'
```

What I expected to happen: GNU `kill` lists the name of the signal `TERM`:
```
TERM
```

Notes: This is causing a failure in the GNU test file `tests/misc/kill.sh`. It seems that only some number of the least significant bits are used to identify the signal.

### PR DESCRIPTION
**Pull request by Felle33**
This pull request solves the issue number #7218.
Fixes #7218

### CODE REVIEW

**Comment by Felle33** [comment]
With this pull request the `tests/misc/kill.sh` passes. Should I modify some file or is it just fine as it is?

File: src/uu/kill/src/kill.rs [hunk 1]
```diff
@@ -164,13 +164,19 @@ fn table() {
 }
 
 fn print_signal(signal_name_or_value: &str) -> UResult<()> {
+    let lower_5_bits = |x: usize| x & 0b11111;
```
Comment (sylvestre) [inline src/uu/kill/src/kill.rs:167]: Please document this magic number :)

**Comment by sylvestre** [comment]
> With this pull request the `tests/misc/kill.sh` passes. Should I modify some file or is it just fine as it is?

You can update utils/why-error.md but no worries if you don't

File: tests/by-util/test_kill.rs [hunk 2]
```diff
@@ -334,6 +334,15 @@ fn test_kill_with_signal_and_list() {
         .fails();
 }
 
+#[test]
+fn test_kill_with_list_lower_bits() {
+    new_ucmd!()
+        .arg("-l")
+        .arg("143")
+        .succeeds()
+        .stdout_matches(&Regex::new("TERM").unwrap());
```
Comment (cakebaker) [inline tests/by-util/test_kill.rs:343]: While this works, I think using a regex is a bit overkill and you can simplify it by using either `stdout_is` or `stdout_contains`.

Comment (cakebaker) [reply tests/by-util/test_kill.rs:343]: Yes, that's also fine.

File: src/uu/kill/src/kill.rs (hunk 1 above)
Comment (cakebaker) [reply src/uu/kill/src/kill.rs:167]: I think it is not entirely correct, because it recognizes, for example, `111` (= `b1101111`) as a TERM signal whereas GNU `kill` doesn't recognize it.

Comment (Felle33) [reply src/uu/kill/src/kill.rs:167]: Yes you are right. I have done some tests and the range of number accepted goes from 0 to 64 and from 128 to 192 (both endings included). It is like they are managing the same signals but mapped 2 times.
I noticed also that we don't manage the name of the signals from 32 to 64 (and therefore also from 160 to 192).

Comment (Felle33) [reply src/uu/kill/src/kill.rs:167]: I could add this feature in this pull request or should I open a new one?

Comment (cakebaker) [reply src/uu/kill/src/kill.rs:167]: I would create a new PR. There is also a ticket for it: https://github.com/uutils/coreutils/issues/6218

**Comment by Felle33** [comment]
I tried to come up with a solution, take for example the signal EXIT (`0`):
with some tests, I noticed that it appears when the argument is `0 128 256 512 768 1024` and so on; it is repeated with a `mod 128`.
For this reason, we should only check only the low 7 bits

**Comment by cakebaker** [comment]
I think you are close :)  It looks like it's `mod 256` for numbers >= 256 and not `mod 128`:
```
$ ../gnu/src/kill -l $(seq 0 128 2560)
EXIT
EXIT
EXIT
kill: ‘384’: invalid signal
EXIT
kill: ‘640’: invalid signal
EXIT
kill: ‘896’: invalid signal
EXIT
kill: ‘1152’: invalid signal
EXIT
kill: ‘1408’: invalid signal
EXIT
kill: ‘1664’: invalid signal
EXIT
kill: ‘1920’: invalid signal
EXIT
kill: ‘2176’: invalid signal
EXIT
kill: ‘2432’: invalid signal
EXIT
```

**Comment by sylvestre** [comment]
is it a bug or a feature ?

**Comment by cakebaker** [comment]
@sylvestre I think it's a feature. This is the relevant part of the corresponding GNU `kill` test:
```bash
# Verify we only consider the lower "signal" bits,
# to support ksh which just adds 256 to the signal value
STD_TERM_STATUS=$(expr "$SIGTERM" + 128)
KSH_TERM_STATUS=$(expr "$SIGTERM" + 256)
test $(env kill -l $STD_TERM_STATUS $KSH_TERM_STATUS | uniq) = TERM || fail=1
```

**Comment by cakebaker** [comment]
> Congrats! The gnu test tests/misc/kill is no longer failing!

Well done and thanks :)

**Comment by Felle33** [comment]
Thanks for your patience...it was a journey :)

**Comment by sylvestre** [comment]
only two days, kudos :)
