### PR TITLE
sort: wait when SIGINT was raised for the program to finish properly

### LINKED ISSUE #3623: `sort::test_tmp_files_deleted_on_sigint` is intermittent
Example:
https://github.com/uutils/coreutils/runs/6865338221?check_suite_focus=true

```
---- test_sort::test_tmp_files_deleted_on_sigint stdout ----
current_directory_resolved: 
mkdir: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/.tmpowUudY/tmp_dir
run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils sort ext_sort.txt --buffer-size=1 --temporary-directory=tmp_dir
thread 'test_sort::test_tmp_files_deleted_on_sigint' panicked at 'assertion failed: read_dir(at.plus(\"tmp_dir\")).unwrap().next().is_some()', /Users/runner/work/coreutils/coreutils/tests/by-util/test_sort.rs:1129:5
```

### PR DESCRIPTION
**Pull request by niyaznigmatullin**
- I hope it fixes #3623 issue

I think that `test_tmp_files_deleted_on_sigint` was failing, because sometimes the program finished before signal handling was finished, so the directory wasn't removed after all. I tested locally it was failing sometimes, after the fix I didn't see it failing.

- Added wait for lock just before the program finishes if the lock was taken by the signal handler

### CODE REVIEW

File: src/uu/sort/src/sort.rs [hunk 1]
```diff
@@ -1267,7 +1267,9 @@ pub fn uumain(args: impl uucore::Args) -> UResult<()> {
 
     settings.init_precomputed();
 
-    exec(&mut files, &settings, output, &mut tmp_dir)
+    let result = exec(&mut files, &settings, output, &mut tmp_dir);
+    tmp_dir.wait_if_signal();
```
Comment (sylvestre) [inline src/uu/sort/src/sort.rs:1271]: please add a comment here and in the function explaining why it is needed 
thanks

Comment (niyaznigmatullin) [reply src/uu/sort/src/sort.rs:1273]: done
