### PR TITLE
Fix EINTR handling in cat, od, and comm

### LINKED ISSUE #1275: Check for interruptible I/O
We should probably check if a read/write was interrupted by a signal or something for some of the utilities (if the read/write fails) and then continue reading/writing if so.

### PR DESCRIPTION
**Pull request by naoNao89**
This adds proper signal interruption handling to cat, od, and comm. When read or write operations get interrupted by signals like SIGUSR1, these utilities now retry instead of failing.

The pattern used here is identical to #6025 from March 2024 that fixed dd's signal handling for the GNU test suite. That same retry-on-interrupted pattern is already working in 9 other utilities including head, tail, tee, wc, sort, sum, tr, and shuf.

Closes #1275

### CODE REVIEW

File: src/uu/comm/src/comm.rs [hunk 1]
```diff
@@ -135,8 +135,18 @@ pub fn are_files_identical(path1: &Path, path2: &Path) -> io::Result<bool> {
     let mut buffer2 = [0; 8192];
 
     loop {
-        let bytes1 = reader1.read(&mut buffer1)?;
-        let bytes2 = reader2.read(&mut buffer2)?;
+        let bytes1 = loop {
```
Comment (sylvestre) [inline src/uu/comm/src/comm.rs:141]: please add comments to explain what it is :)

File: tests/by-util/test_eintr_handling.rs [hunk 2]
```diff
@@ -0,0 +1,204 @@
...
+    }
+}
+
+#[cfg(test)]
+mod tests {
+    use super::*;
+    use std::io::Cursor;
+
+    #[test]
+    fn test_interrupting_reader_no_interrupts() {
```
Comment (sylvestre) [inline tests/by-util/test_eintr_handling.rs:123]: i don't see them in the ci logs. Do you know which jobs should run them ?
