### PR TITLE
cksum: Match GNU behavior for digest length errors in --check mode

### LINKED ISSUE #11202: sha256sum/sha1sum breaking change
When a checksum file contains different type of hashes, running `sha256sum -c CHECKSUMS` will fail.

`coreutils` would report `sha256sum: WARNING: 4 lines are improperly formatted` and return exit code 0.

```
# Checksums, check with the command below:
#     shasum -c CHECKSUMS
#
# Checksums-Sha1:
16884dd63beb3349acf3cae4d2d592d4724751f1  linux-headers-6.18.14-061814-generic_6.18.14-061814.202602262345_amd64.deb
4df410365485b1214689c4aea433ca852dd5b01a  linux-headers-6.18.14-061814_6.18.14-061814.202602262345_all.deb
809697f1a23338fb10d9812cf1f8be509b2ee608  linux-image-unsigned-6.18.14-061814-generic_6.18.14-061814.202602262345_amd64.deb
5e841b4ff3708a8db05c7c4e9f4e723e0927dd92  linux-modules-6.18.14-061814-generic_6.18.14-061814.202602262345_amd64.deb
#
# Checksums-Sha256:
eb4f751b84693e731f9497a4a5913b4e1eef7a60b853d1185d5214932fdbb588  linux-headers-6.18.14-061814-generic_6.18.14-061814.202602262345_amd64.deb
bf9f50363eba0f9cd9c9fbd61b930857aa75d46945aa584cdc8cdcb92cb76573  linux-headers-6.18.14-061814_6.18.14-061814.202602262345_all.deb
e31a9b827a165b0d685f3306cdedf8f6d9ef27b694b37f832af8db023c0523b6  linux-image-unsigned-6.18.14-061814-generic_6.18.14-061814.202602262345_amd64.deb
e34c69bd2cfa07ae0a6aa538a498ac3c4ca82404b71232a2fff00e754f756a9f  linux-modules-6.18.14-061814-generic_6.18.14-061814.202602262345_amd64.deb
```

Thank you *rewrite everything in rust* guys for amazing breaking changes and wasting my time.

### PR DESCRIPTION
**Pull request by RenjiSann**
This PR fixes #11202, as well as a few other related issues

### CODE REVIEW

File: src/uucore/src/lib/features/checksum/validate.rs [hunk 1]
```diff
@@ -747,17 +749,23 @@ fn process_algo_based_line(
     // If the digest bitlen is known, we can check the format of the expected
     // checksum with it.
     let digest_char_length_hint = match (algo_kind, algo_byte_len) {
-        (AlgoKind::Blake2b | AlgoKind::Blake3, Some(byte_len)) => Some(byte_len),
-        (AlgoKind::Shake128 | AlgoKind::Shake256, Some(bit_len)) => Some(bit_len.div_ceil(8)),
-        (AlgoKind::Shake128, None) => Some(sum::Shake128::DEFAULT_BIT_SIZE.div_ceil(8)),
-        (AlgoKind::Shake256, None) => Some(sum::Shake256::DEFAULT_BIT_SIZE.div_ceil(8)),
+        (AlgoKind::Blake2b | AlgoKind::Blake3, Some(byte_len)) => Some(byte_len * 8),
```
Comment (AldanTanneo) [inline src/uucore/src/lib/features/checksum/validate.rs:751]: `digest_char_length_hint` now stores a bit length instead of a byte length hint? the name should probably change then.

File: src/uucore/src/lib/features/checksum/validate.rs [hunk 2]
```diff
@@ -490,14 +490,16 @@ impl LineInfo {
...
-fn get_raw_expected_digest(checksum: &str, byte_len_hint: Option<usize>) -> Option<Vec<u8>> {
+fn get_raw_expected_digest(checksum: &str, bit_len_hint: Option<usize>) -> Option<Vec<u8>> {
     // If the length of the digest is not a multiple of 2, then it must be
     // improperly formatted (1 byte is 2 hex digits, and base64 strings should
     // always be a multiple of 4).
     if !checksum.len().is_multiple_of(2) {
         return None;
     }
 
+    let byte_len_hint = bit_len_hint.map(|n| n / 8);
```
Comment (AldanTanneo) [inline src/uucore/src/lib/features/checksum/validate.rs]: the division should probably be a `.div_ceil(8)`, since for instance 4 bits still take a full byte to be represented in a truncated XOF output.

File: src/uucore/src/lib/features/checksum/validate.rs [hunk 3]
```diff
@@ -747,17 +749,23 @@ fn process_algo_based_line(
...
     };
 
     let expected_checksum = get_raw_expected_digest(&line_info.checksum, digest_char_length_hint)
         .ok_or(LineCheckError::ImproperlyFormatted)?;
 
-    let algo = SizedAlgoKind::from_unsized(algo_kind, algo_byte_len)?;
+    // If the algorithm is SHA2 and no length hint was provided, compute it
+    // from the size of the expected checksum.
+    let algo_byte_len = algo_byte_len
+        .or_else(|| (algo_kind == AlgoKind::Sha2).then(|| expected_checksum.len() * 8));
```
Comment (AldanTanneo) [inline src/uucore/src/lib/features/checksum/validate.rs]: wrong variable name? why do we multiply by 8 if this is a byte length

File: src/uucore/src/lib/features/checksum/mod.rs [hunk 4]
```diff
@@ -200,6 +200,22 @@ impl AlgoKind {
         use AlgoKind::*;
         matches!(self, Sysv | Bsd | Crc | Crc32b)
     }
+
+    /// When checking untagged format lines, non-XOF non-legacy algorithms
+    /// should report "improperly formatted lines" if the digest length isn't
+    /// equivalent to this.
+    pub fn expected_digest_byte_len(self) -> Option<usize> {
```
Comment (AldanTanneo) [inline src/uucore/src/lib/features/checksum/mod.rs]: wrong function name: returns a bit length, not a byte length.

File: src/uucore/src/lib/features/checksum/validate.rs (hunk 3 above)
Comment (RenjiSann) [reply src/uucore/src/lib/features/checksum/validate.rs]: Should change the name, but when algo is Blake, this variable holds bytes 😅

Comment (AldanTanneo) [reply src/uucore/src/lib/features/checksum/validate.rs]: #11500 is direly needed :sob:

File: src/uucore/src/lib/features/checksum/mod.rs (hunk 4 above)
Comment (RenjiSann) [reply src/uucore/src/lib/features/checksum/mod.rs]: indeed, thanks

File: src/uucore/src/lib/features/checksum/validate.rs (hunk 2 above)
Comment (RenjiSann) [reply src/uucore/src/lib/features/checksum/validate.rs]: Indeed, thanks :+1:

File: src/uucore/src/lib/features/checksum/validate.rs (hunk 1 above)
Comment (RenjiSann) [reply src/uucore/src/lib/features/checksum/validate.rs:751]: Done :+1:

File: tests/by-util/test_cksum.rs [hunk 5]
```diff
@@ -562,6 +605,71 @@ fn test_check_sha2_tagged_variant() {
...
+
+    let checksum = "SHA2 (a) = d14a028c2a3a2bc9476102bb288234c415a2b01f828ea62ac5b3e42f";
+    let invalid = "SHA2 (b) = xxxx";
+
+    ucmd.arg("-c")
+        .pipe_in(format!("{checksum}\n{invalid}"))
+        .succeeds()
+        .stdout_contains("a: OK")
+        .stderr_contains("WARNING: 1 line is improperly formatted");
+}
```
Comment (cakebaker) [inline tests/by-util/test_cksum.rs]: I think this test is incorrect because I get a failure when running the command manually with GNU `cksum`:
```
$ touch a b
$ printf "SHA2 (a) = d14a028c2a3a2bc9476102bb288234c415a2b01f828ea62ac5b3e42f\nSHA2 (b) = xxxx" | cksum -c
cksum: 'standard input': no properly formatted checksum lines found
$ echo $?
1
```
If I replace `SHA2` with `SHA224`, however, I get the same result as in the test:
```
$ printf "SHA224 (a) = d14a028c2a3a2bc9476102bb288234c415a2b01f828ea62ac5b3e42f\nSHA224 (b) = xxxx" | cksum -c
a: OK
cksum: WARNING: 1 line is improperly formatted
```

File: tests/by-util/test_cksum.rs [hunk 6]
```diff
@@ -562,6 +605,71 @@ fn test_check_sha2_tagged_variant() {
...
+    // issue #11202
+
+    // Ensures that when checking untagged lines, if the provided algorithm is
+    // one of `sha(224|256|384|512)`, digests whose length mismatches the
+    // length of the given algorithm will report as "improperly formatted"
+    // rather than a  FAILED check.
+
+    let (at, mut ucmd) = at_and_ucmd!();
+    at.touch("null");
+    at.write("one", "A");
```
Comment (cakebaker) [inline tests/by-util/test_cksum.rs]: I don't understand why you create this file as it isn't used afterwards.

File: tests/by-util/test_cksum.rs [hunk 7]
```diff
@@ -562,6 +605,71 @@ fn test_check_sha2_tagged_variant() {
...
+    let invalid_checksum = "e3b0  null";
+    let good_checksum = format!("{digest}  null");
+
+    ucmd.arg("-a")
+        .arg(algo)
+        .arg("-c")
+        .pipe_in(format!("{invalid_checksum}\n{good_checksum}"))
+        .succeeds()
+        .stdout_contains("null: OK")
+        .stdout_does_not_contain("one: FAILED")
```
Comment (cakebaker) [inline tests/by-util/test_cksum.rs]: See my previous comment.

File: tests/by-util/test_cksum.rs (hunk 6 above)
Comment (RenjiSann) [reply tests/by-util/test_cksum.rs]: It was meant to be the filename used in the invalid checksum, thanks for noticing it !
I changed the test a bit to use both files, and I renamed them to `a` and `b`.

File: tests/by-util/test_cksum.rs (hunk 5 above)
Comment (RenjiSann) [reply tests/by-util/test_cksum.rs]: I made a mistake somewhere when testing. I'm investigating

Comment (RenjiSann) [reply tests/by-util/test_cksum.rs]: Looks like I hallaucinated this feature, I pushed a fix

**Comment by RenjiSann** [comment]
> It looks good. Can you please do a rebase and reduce the number of commits?

Did it, and rebased at the same time.

**Comment by cakebaker** [comment]
Thanks!
