### PR TITLE
cp: truncate destination when `--reflink` is set

### LINKED ISSUE #3758: `cp` is unable to override files with `--reflink` for linux
The issue seems to be related to the use of [`truncate(false)`](https://github.com/uutils/coreutils/blob/38679f1c1bc7606dc9a5803f4844148baaf6950a/src/uu/cp/src/cp.rs#L1538) for the destination of the copy when `--reflink` is present. My understanding of [Rust documentation](https://doc.rust-lang.org/stable/std/fs/struct.OpenOptions.html#method.truncate) is that we want to truncate the file.

Below is an example comparing GNU `cp` to uutils `cp`:

```
$ truncate -s 512M /tmp/disk.img
$ mkfs.btrfs /tmp/disk.img
[...]
$ mkdir /tmp/disk
$ sudo mount /tmp/disk.img /tmp/disk
$ sudo chown $(id -u):$(id -g) -R /tmp/disk
$ for i in $(seq 0 8192); do echo -ne 'a' >>/tmp/disk/src1; done
$ echo "success" >/tmp/disk/src2
$
$ # GNU ls supports overriding files created with `--reflink`
$ cp --version
cp (GNU coreutils) 9.1
[...]
$ cp --reflink=always /tmp/disk/src1 /tmp/disk/dst1
$ cp --reflink=always /tmp/disk/src2 /tmp/disk/dst1
$ cat /tmp/disk/dst1
success
$
$ # Now testing with uutils
$ cargo run cp --reflink=always /tmp/disk/src1 /tmp/disk/dst2
    Finished dev [unoptimized + debuginfo] target(s) in 0.25s
     Running `target/debug/coreutils cp --reflink=always /tmp/disk/src1 /tmp/disk/dst2`
$ cargo run cp --reflink=always /tmp/disk/src2 /tmp/disk/dst2
    Finished dev [unoptimized + debuginfo] target(s) in 0.26s
     Running `target/debug/coreutils cp --reflink=always /tmp/disk/src2 /tmp/disk/dst2`
cp: failed to clone "/tmp/disk/src2" from "/tmp/disk/dst2": Invalid argument (os error 22)
$ cat /tmp/disk/dst2
[lots of 'a']
```

### PR DESCRIPTION
**Pull request by pimzero**
This is needed in order to allow overriding an existing file. closes #3758 

```
$ truncate -s 512M /tmp/disk.img
$ mkfs.btrfs /tmp/disk.img
[...]
$ mkdir /tmp/disk
$ sudo mount /tmp/disk.img /tmp/disk
$ sudo chown $(id -u):$(id -g) -R /tmp/disk
$ for i in $(seq 0 8192); do echo -ne 'a' >>/tmp/disk/src1; done
$ echo "success" >/tmp/disk/src2
$
$ # GNU ls supports overriding files created with `--reflink`
$ cp --reflink=always /tmp/disk/src1 /tmp/disk/dst1
$ cp --reflink=always /tmp/disk/src2 /tmp/disk/dst1
$ cat /tmp/disk/dst1
success
$
$ # Now testing with uutils
$ cargo run cp --reflink=always /tmp/disk/src1 /tmp/disk/dst2
    Finished dev [unoptimized + debuginfo] target(s) in 0.25s
     Running `target/debug/coreutils cp --reflink=always /tmp/disk/src1 /tmp/disk/dst2`
$ cargo run cp --reflink=always /tmp/disk/src2 /tmp/disk/dst2
    Finished dev [unoptimized + debuginfo] target(s) in 0.26s
     Running `target/debug/coreutils cp --reflink=always /tmp/disk/src2 /tmp/disk/dst2`
cp: failed to clone "/tmp/disk/src2" from "/tmp/disk/dst2": Invalid argument (os error 22)
$ cat /tmp/disk/dst2
[lots of 'a']
$
$ # With truncate(true)
$ cargo run cp --reflink=always /tmp/disk/src1 /tmp/disk/dst3
    Finished dev [unoptimized + debuginfo] target(s) in 7.98s
     Running `target/debug/coreutils cp --reflink=always /tmp/disk/src1 /tmp/disk/dst3`
$ cargo run cp --reflink=always /tmp/disk/src2 /tmp/disk/dst3
    Finished dev [unoptimized + debuginfo] target(s) in 0.27s
     Running `target/debug/coreutils cp --reflink=always /tmp/disk/src2 /tmp/disk/dst3`
$ cat /tmp/disk/dst3
success
```

### CODE REVIEW

**Comment by sylvestre** [comment]
cool, could you please add a test for this ? thanks

**Review by sylvestre — CHANGES_REQUESTED** [review]
need test :)

**Comment by pimzero** [comment]
I am not completely happy with the testing (it looks clunky, needs root, and may leak mount points in case of test failures) but I don't see a better way to check this (I believe tmpfs don't handle reflink).

File: tests/by-util/test_cp.rs [hunk 1]
```diff
@@ -1388,6 +1388,52 @@ fn test_closes_file_descriptors() {
         .succeeds();
 }
 
+#[cfg(any(target_os = "linux", target_os = "android"))]
+#[test]
+fn test_cp_reflink_always_override() {
+    let scene = TestScenario::new(util_name!());
+
+    // Test must be run as root (or with `sudo -E`)
```
Comment (sylvestre) [inline tests/by-util/test_cp.rs:1396]: Can you do like in
https://github.com/uutils/coreutils/blob/40095e1b5070b1c353de613f0b258a030b978407/tests/by-util/test_chown.rs#L432-L442 instead?

thanks

Comment (pimzero) [reply tests/by-util/test_cp.rs:1396]: I am not sure this allows me to do what I want, only the tested command (`cp`) can be run as root with `run_ucmd_as_root`, while we need only need root for `mount`/`umount` in this test. Nevertheless, I tried to take into account this idea to allow running the test as non root (running `sudo` only for `mount` and `umount`)
