### PR TITLE
tr: Raise error if set2 is too big on complemented class

### LINKED ISSUE #6345: tr: Raise error when STRING2 argument has unreachable character during complement
When complementing, we basically translate all bytes not mentioned in STRING1 to bytes in STRING2. This means that only the first 256-len(ARRAYISH1) bytes of ARRAY2 can be accessed.

GNU `tr` issues a (confusing, but well-intentioned) error message if the command-line argument contains garbage:

```console
$ x230="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
$ echo -n 'hello' | ../gnu/src/tr -c '[:upper:]' "${x230}" # 256-26 times 'x'
xxxxx
$ echo -n 'hello' | ../gnu/src/tr -c '[:upper:]' "${x230}x" # 256-26+1 times 'x'
../gnu/src/tr: when translating with complemented character classes,
string2 must map all characters in the domain to one
[$? = 1]
$ echo -n 'hello' | cargo run tr -c '[:upper:]' "${x230}" # we accidentally treat this correctly
xxxxx
$ echo -n 'hello' | cargo run tr -c '[:upper:]' "${x230}x" # this needs to change
xxxxx
```

Computing the ideal size should be easy, but checking it isn't:
- If we just consider the length of STRING2, then this will obviously fail due to expansions
- I believe there was some reason why checking the length of ARRAY2 didn't work. Hmm. I'm confused.

(Original issue: https://github.com/uutils/coreutils/issues/6133)

### PR DESCRIPTION
**Pull request by RenjiSann**
Fixes #6345

### CODE REVIEW

File: tests/by-util/test_tr.rs [hunk 1]
```diff
@@ -1413,3 +1413,14 @@ fn check_complement_1_unique_in_set2() {
         .args(&["-c", "[:upper:]", arg.as_str()])
         .succeeds();
 }
+
+#[test]
+fn check_complement_set2_too_big() {
+    let x231 = "x".repeat(231);
```
Comment (BenWiederhake) [inline tests/by-util/test_tr.rs:1419]: The existence of this test is great! Can you also add a test to make sure that using 230 works as intended?

File: tests/by-util/test_tr.rs [hunk 2]
```diff
@@ -1413,3 +1413,14 @@ fn check_complement_1_unique_in_set2() {
...
+
+    // [:upper:] expands to 230 characters, putting more characters in set2
```
Comment (BenWiederhake) [inline tests/by-util/test_tr.rs:1421]:
```suggestion
    // The complement of [:upper:] expands to 230 characters, putting more characters in set2
```

File: tests/by-util/test_tr.rs [hunk 3]
```diff
@@ -1413,3 +1413,14 @@ fn check_complement_1_unique_in_set2() {
...
+    // should fail.
+    new_ucmd!()
+        .args(&["-c", "[:upper:]", x231.as_str()])
+        .fails();
```
Comment (BenWiederhake) [inline tests/by-util/test_tr.rs:1425]: Please also check whether the "correct" error message has been generated. (Just in case this invocation fails for an unrelated reason.)

**Review by BenWiederhake — CHANGES_REQUESTED** [review]
The code change itself is great! It's really straight-forward, thanks to the previous PRs.

I have some requests about the test: Please test the positive case, fix a technically-incorrect comment, and make sure the test checks for the correct failure reason. (Details below.)

**Comment by RenjiSann** [comment]
Force push fixed this:
- Add `The complement of` ('[:upper:]').
- Add a test with 230 x.
- Check the expected error message

**Review by BenWiederhake — APPROVED** [review]
Code looks good to me, tests both the positive and the negative case, remaining failures are unrelated issues with CI: #6534, #6569, #6570 (twice).
