### PR TITLE
printf: fix octal escape parsing

### LINKED ISSUE #7202: printf: fails to interpret octal escape sequence with leading 0 in string literal
Environment: Ubuntu 20.04, uutils `main` branch (git commit ceb0785f8d89e82dabe347ff6d368f310977dce0), GNU coreutils v8.30

Steps to reproduce:
```
printf "\xaa\0377\n"
```

What happens now: uutils `printf` prints
```
\252\377
```

What I expected to happen: GNU `printf` prints
```
\252^_7
```

Notes: this is causing a failure in GNU test file `tests/printf/printf-cov.pl`.

### PR DESCRIPTION
**Pull request by RenjiSann**
Refit of #7210 by @aryalaadi
I had some trouble rebasing so I just copied the changes manually to a new branch, so your name disappears from the commits. Sorry for that, I'll try to find a way to make you a co-author of these changes
Fixes #7202

### CODE REVIEW

**Comment by RenjiSann** [comment]
@Copilot

**Comment by aryalaadi** [comment]
i don't mind it

**Comment by RenjiSann** [comment]
Well it looks like my suggestions are incompatible with other dependencies of `escape.rs`
Will look further into it soon

**Comment by cakebaker** [comment]
@RenjiSann for adding a co-author: https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

File: src/uucore/src/lib/features/format/escape.rs [hunk 1]
```diff
@@ -99,13 +113,16 @@ fn parse_unicode(input: &mut &[u8], digits: u8) -> Option<char> {
 pub struct EscapeError {}
 
 /// Parse an escape sequence, like `\n` or `\xff`, etc.
-pub fn parse_escape_code(rest: &mut &[u8]) -> Result<EscapedChar, EscapeError> {
+pub fn parse_escape_code(
+    rest: &mut &[u8],
+    zero_octal_parsing: Option<OctalParsing>,
```
Comment (cakebaker) [inline src/uucore/src/lib/features/format/escape.rs:118]: I'm not sure about the `Option` here. `None` indicates that the default variant of `OctalParsing` should be used (and not that there is no `OctalParsing`). Maybe it makes sense to explicitly mark one of the `OctalParsing` variants as default and use `OctalParsing::default()` where `None` is currently used?

**Comment by cakebaker** [comment]
Thanks :)
