### PR TITLE
cp: treat an empty file name as a non-existing file

### LINKED ISSUE #6177: cp: treat emptystring-file as a regular missing file, not as invocation error
Discovered during #6176. Example:

```console
$ rm -rf target/test/; mkdir target/test/; cp LICENSE "" README.md target/test/; echo "EXITCODE GNU: $?"; ls -l target/test/; echo "(end)"      
cp: cannot stat '': No such file or directory
EXITCODE GNU: 1
total 12
-rw-r--r-- 1 user user 1056 Apr  1 21:12 LICENSE
-rw-r--r-- 1 user user 7973 Apr  1 21:12 README.md
(end)
$ rm -rf target/test/; mkdir target/test/; cargo run cp LICENSE "" README.md target/test/; echo "EXITCODE uutils: $?"; ls -l target/test/; echo "(end)"
error: a value is required for '[paths]...' but none was supplied

For more information, try '--help'.
EXITCODE uutils: 1
total 0
(end)
```

In the above example, GNU `cp` tried its best to copy the two reasonably-named files, and reported the emptystring-named file as a regular error. In contrast, uutils `cp` refused to even start copying.

I feel like both behaviors are reasonable; but if we want uutils to bee a drop-in replacement, then it should also try its best to copy all files.

### PR DESCRIPTION
**Pull request by samueltardieu**
The `PathBuf` value parser from `clap` cannot be used directly as it does not (rightly) accept empty file names. 

Fix #6177

### CODE REVIEW

File: tests/by-util/test_cp.rs [hunk 1]
```diff
@@ -169,6 +168,32 @@ fn test_cp_multiple_files() {
...
 }
 
+#[test]
+fn test_cp_multiple_files_with_nonexistent_file() {
+    let (at, mut ucmd) = at_and_ucmd!();
+    ucmd.arg(TEST_HELLO_WORLD_SOURCE)
+        .arg(TEST_NONEXISTENT_FILE)
+        .arg(TEST_HOW_ARE_YOU_SOURCE)
+        .arg(TEST_COPY_TO_FOLDER)
+        .fails();
```
Comment (BenWiederhake) [inline tests/by-util/test_cp.rs:178]: `.fails()` is a bit too general: What if we fail due to something unrelated?

Suggestion: Add something like `.stderr_contains(…);` in order to check for something that indicates that TEST_NONEXISTENT_FILE is indeed nonexistent.

File: tests/by-util/test_cp.rs [hunk 2]
```diff
@@ -169,6 +168,32 @@ fn test_cp_multiple_files() {
...
+}
+
+#[test]
+fn test_cp_multiple_files_with_empty_file_name() {
+    let (at, mut ucmd) = at_and_ucmd!();
+    ucmd.arg(TEST_HELLO_WORLD_SOURCE)
+        .arg("")
+        .arg(TEST_HOW_ARE_YOU_SOURCE)
+        .arg(TEST_COPY_TO_FOLDER)
+        .fails();
```
Comment (BenWiederhake) [inline tests/by-util/test_cp.rs:191]: Same here.

**Review by BenWiederhake — CHANGES_REQUESTED** [review]
Straight-forward implementation, tests, lovely.

Can you make the tests a bit more specific, just in case `cp` encounters an unrelated issue?

File: tests/by-util/test_cp.rs (hunk 1 above)
Comment (samueltardieu) [reply tests/by-util/test_cp.rs:178]: I will think about it, but error messages on Windows for non-existent files seem to have nothing in common with error messages on other platforms.

Comment (samueltardieu) [reply tests/by-util/test_cp.rs]: I've added another commit which attempts to detect the specific error outputs.

**Review by BenWiederhake — APPROVED** [review]
LGTM!

The unhelpful error message on windows is a pity, but out of scope for this PR.

Let's see if known issue #6534 remains the only CI failure.

**Comment by samueltardieu** [comment]
> LGTM!
> 
> The unhelpful error message on windows is a pity, but out of scope for this PR.
> 
> Let's see if known issue #6534 remains the only CI failure.
> 
> EDIT: Oops, I celebrated too early.
> 
> ```
> thread 'test_cp::test_cp_multiple_files_with_empty_file_name' panicked at tests\by-util\test_cp.rs:182:10:
> 'cp: The system cannot find the path specified. (os error 3)
> ' does not contain 'The system cannot find the file specified'
> ```

The message on Windows is different for the empty file name and other non-existent file names. I've entered a new version.

**Comment by samueltardieu** [comment]
@BenWiederhake The only failing test is the Windows test coverage which has since be disabled in the CI.

**Comment by BenWiederhake** [comment]
Thanks!
