### PR TITLE
mktemp: prioritize TMPDIR over -p when using -t

### LINKED ISSUE #4874: mktemp: incorrect priority between TMPDIR & -p
With GNU mktemp:
```
$ TMPDIR=dir_a mktemp -t -p dir_b foo.XXXX
dir_a/foo.CnlA
```
With uutils mktemp:
```
$ TMPDIR=dir_a cargo run mktemp -t -p dir_b foo.XXXX
dir_b/foo.DAXt
```

_Originally posted by @cakebaker in https://github.com/uutils/coreutils/pull/4832#pullrequestreview-1427932652_

### PR DESCRIPTION
**Pull request by cakebaker**
This PR ensures that the `TMPDIR` env variable has a higher priority than `-p` when using `-t`.

```
$ TMPDIR=dir_a cargo run mktemp -t -p dir_b foo.XXXX
dir_a/foo.DAXt
```

Closes #4874

### CODE REVIEW

File: tests/by-util/test_mktemp.rs [hunk 1]
```diff
@@ -884,3 +884,20 @@ fn test_default_issue_4821_t_tmpdir_p() {
...
+#[test]
+fn test_t_ensure_tmpdir_has_higher_priority_than_p() {
+    let scene = TestScenario::new(util_name!());
+    let pathname = scene.fixtures.as_string();
+    let result = scene
+        .ucmd()
+        .env("TMPDIR", &pathname)
+        .arg("-t")
+        .arg("-p")
+        .arg("should_not_attempt_to_write_in_this_nonexisting_dir")
```
Comment (sylvestre) [inline tests/by-util/test_mktemp.rs:897]: i love this trick ;)

**Comment by cakebaker** [comment]
The latest push introduces the `TMPDIR_ENV_VAR` const to make it work with Windows' `TMP` env var. Previously, I hardcoded the usage of the `TMPDIR` env var.
