### PR TITLE
uucore: num_parser: Update pow_with_context

### LINKED ISSUE #7708: fuzz_seq_parse_number often hangs
e.g. in CI here: https://github.com/uutils/coreutils/actions/runs/14349472400/job/40226263754

Easy to reproduce locally with `-timeout=10`:
```
cargo +nightly fuzz run fuzz_seq_parse_number -- -max_total_time=60 -detect_leaks=0 -timeout=10
```

Looking.

### PR DESCRIPTION
**Pull request by drinkcat**
This is the latest version in https://github.com/akubera/bigdecimal-rs/pull/148 , but the discussion sort of stalled, this is really complicated math, but this new function is a little bit better than the original (at least I hope so).

--

I think we can close #7708 after this, I'm referencing https://github.com/akubera/bigdecimal-rs/issues/147 so if/when we reach a conclusion there, we can drop this function.

### CODE REVIEW

File: src/uucore/src/lib/features/parser/num_parser.rs [hunk 1]
```diff
@@ -375,30 +377,66 @@ fn make_error<'a>(overflow: bool, negative: bool) -> ExtendedParserError<'a, Ext
...
 
-    let bd = trim_precision(bd, ctx);
-    let ret = if exp % 2 == 0 {
-        pow_with_context(bd.square(), exp / 2, ctx)
+    // Count the number of multiplications we're going to perform, one per "1" binary digit
+    // in exp, and the number of times we can divide exp by 2.
+    let mut n = exp.unsigned_abs();
+    // Note: 63 - n.leading_zeros() == n.ilog2, but that's only available in recent Rust versions.
+    let muls = (n.count_ones() + (63 - n.leading_zeros()) - 1) as u64;
+    // Note: div_ceil would be nice to use here, but only available in recent Rust versions.
```
Comment (cakebaker) [inline src/uucore/src/lib/features/parser/num_parser.rs:414]: We have a MSRV of `1.85` and so it should be fine to use those functions mentioned in the comments. Or am I missing something?

Comment (drinkcat) [reply src/uucore/src/lib/features/parser/num_parser.rs:414]: Oh... Yeah, I just copy-pasted the code that I have as a PR for `bigdecimal-rs` https://github.com/akubera/bigdecimal-rs/pull/148.

I can either add a clearer note at the top of the function, or adapt this piece of code. (I have a mild preference for the former but let me know)

Comment (drinkcat) [reply src/uucore/src/lib/features/parser/num_parser.rs:416]: It's meant to be replaced by a version in `bigdecimal`, but this is tricky stuff, so I'm not sure about the timeline.

I'll just add a TODO, and maybe it'll get caught in a clippy warning at some point and we can adjust.

Comment (drinkcat) [reply src/uucore/src/lib/features/parser/num_parser.rs:416]: (done)

**Comment by cakebaker** [comment]
Thanks!
