### PR TITLE
fix tr with any flag with more than 2 operands 

### LINKED ISSUE #5950: tr: `-d a b c` should show similar error as `-d a b`
This issue was mentioned by @BaherSalama in https://github.com/uutils/coreutils/pull/5945.

GNU `tr` shows almost the same error for `tr -d a b` and `tr -d a b c`:
```
$ tr -d a b
tr: extra operand ‘b’
Only one string may be given when deleting without squeezing repeats.
Try 'tr --help' for more information.
$ tr -d a b c
tr: extra operand ‘b’
Try 'tr --help' for more information.
```
uutils `tr`, on the other hand, shows a clap error in the second case:
```
$ cargo run tr -d a b
tr: extra operand 'b'
Only one string may be given when deleting without squeezing repeats.
Try 'target/debug/coreutils tr --help' for more information.
$ cargo run tr -d a b c
error: unexpected value 'c' for '[sets]...' found; no more were expected

Usage: target/debug/coreutils tr [OPTION]... SET1 [SET2]

For more information, try '--help'.
```

### PR DESCRIPTION
**Pull request by BaherSalama**
turns out all tr flags should fail with the same massage not just delete flag if the number of operands is more than 2 so i rewrote the part i did write so all the flags fails with more than 2 operand 
so now 
```
gnu tr:
>tr -s a b c
tr: extra operand ‘c’
Try 'tr --help' for more information.
[ble: exit 1]
~
>tr -d a b c
tr: extra operand ‘b’
Try 'tr --help' for more information.
[ble: exit 1]

and uutils tr 
>cargo run tr -s a b c
   Compiling coreutils v0.0.24 (/home/broly/sad/coreutils)
   Finished dev [unoptimized + debuginfo] target(s) in 2.68s
   Running `target/debug/coreutils tr -s a b c`
tr: extra operand 'c'
Try 'target/debug/coreutils tr --help' for more information.
[ble: exit 1]

>cargo run tr -d a b c
  Finished dev [unoptimized + debuginfo] target(s) in 0.10s
  Running `target/debug/coreutils tr -d a b c`
tr: extra operand 'b'
Try 'target/debug/coreutils tr --help' for more information.
[ble: exit 1]
```
this fixes #5950
but i have 2 questions 
1. in gnu tr it takes any number of arguments even if more than 3 (which works here) but where to stop? so i choose to make the maximum number 32 is this right?
2. is there a better way to add strings together the way i did it looks ugly 🥹

### CODE REVIEW

**Comment by cakebaker** [comment]
1. I think you can omit the max number and use `1..`
2. You could use `format!` to simplify it

File: tests/by-util/test_tr.rs
Comment (cakebaker) [inline tests/by-util/test_tr.rs:1]: Calling `pipe_in` is not necessary for these tests and unfortunately makes the tests fail intermittently (see https://github.com/uutils/coreutils/actions/runs/7809592276/job/21301687515?pr=5952). And the comments are not needed as they are incorrect ;-)

File: tests/by-util/test_tr.rs [hunk 1]
```diff
@@ -1159,3 +1159,33 @@ fn test_delete_flag_takes_only_one_operand() {
         "extra operand 'p'\nOnly one string may be given when deleting without squeezing repeats.",
     );
 }
+
+#[test]
+fn test_translate_flag_fails_with_more_than_two_operand() {
```
Comment (cakebaker) [inline tests/by-util/test_tr.rs:1164]: The long form of `-t` is `--truncate-set1` and not `--translate`, hence I would use something like:
```suggestion
fn test_truncate_flag_fails_with_more_than_two_operand() {
```

File: tests/by-util/test_tr.rs [hunk 2]
```diff
@@ -1159,3 +1159,33 @@ fn test_delete_flag_takes_only_one_operand() {
...
+        .pipe_in("abc")
+        .fails()
+        .stderr_contains("extra operand 'c'");
+}
+
+#[test]
+fn test_complement_flag_fails_with_more_than_two_operand() {
+    // gnu tr -d fails with more than 1 argument
+    new_ucmd!()
+        .args(&["-s", "a", "b", "c"])
```
Comment (cakebaker) [inline tests/by-util/test_tr.rs:1187]:
```suggestion
        .args(&["-c", "a", "b", "c"])
```

**Comment by BaherSalama** [comment]
sorry for the inconvenience 😅

File: src/uu/tr/src/tr.rs [hunk 3]
```diff
@@ -57,15 +57,29 @@ pub fn uumain(args: impl uucore::Args) -> UResult<()> {
...
+                    "{}\n{}",
+                    msg, "Only one string may be given when deleting without squeezing repeats."
+                );
+            }
+            return Err(UUsageError::new(1, msg));
+        }
+        if sets_len > 2 {
+            msg = format!("{} {}", msg, sets[2].quote());
+            return Err(UUsageError::new(1, msg));
+        }
```
Comment (cakebaker) [inline src/uu/tr/src/tr.rs:82]: I think you can simplify it even more by avoiding `mut` and returning a string from `if sets_len == 2`, something like:
```
let op = sets[1].quote();
let msg = if sets_len == 2 {
    format!(
        "{msg} {op}\n{}",
        "Only one string may be given when deleting without squeezing repeats."
    )
} else {
    format!("{msg} {op}")
};
```

The other changes look good.

**Review by cakebaker — APPROVED** [review]

**Comment by cakebaker** [comment]
Thanks for your PR :)
