### PR TITLE
Replace outdated time 0.1 dependancy with latest version of chrono

### LINKED ISSUE #2042: du date formatting is broken on linux
```
touch new_file
cargo run du --time new_file
```

outputs

```
0       1970-01-19 12:22        new_file
```

Which is wrong since I don't have my system clock set to the 70s.

---

The GNU version of du

```
du --time new_file
```

outputs

```
0       2021-04-06 18:55        new_file
```

which is correct.

### LINKED ISSUE #2043: du - time 0.1 is outdated
as per https://deps.rs/repo/github/uutils/coreutils

### PR DESCRIPTION
**Pull request by paulotten**
I also noticed that times are being miscalculated on linux, so I fixed that.

Fixes #2042 and fixes #2043.

### CODE REVIEW

**Comment by paulotten** [comment]
Re #2042 I'm thinking I should add a test.

I can use `touch` to set a file time to specific value (say Rust 1.0 release date) and then check that `du` returns the correct value. The only downside of this is windows doesn't ship with `touch` and coreutils doesn't have it ported to windows currently, so I can't use this to test on windows.

File: tests/by-util/test_du.rs [hunk 1]
```diff
@@ -172,3 +172,23 @@ fn test_du_h_flag_empty_file() {
     assert_eq!(result.stderr, "");
     assert_eq!(result.stdout, "0\tempty.txt\n");
 }
+
+// I don't have touch on windows so I can't run this test
+// if we port touch to windows then we can enable this test on windows
```
Comment (paulotten) [inline tests/by-util/test_du.rs:177]: Apparently if I build with `--features windows` we have `touch`. So I probably can update this test.
