### PR TITLE
df: fix rounding behavior in humanreadable mode

### LINKED ISSUE #3422: df -H and df -h have a different rounding behavior than GNU df
It seems like GNU df rounds the values in the `Size`, `Used`, and `Available` columns in such a way that they use up maximal four chars (including dot and unit), whereas uutils df doesn't.
```
$ ./target/debug/coreutils df -H
Filesystem               Size         Used    Available  Use% Mounted on       
dev                      4.1G            0         4.1G    0% /dev            
run                      4.1G         1.4M         4.1G    1% /run            
/dev/sda8              469.1G       130.9G       314.3G   30% /               
tmpfs                    4.1G        88.5M         4.0G    3% /dev/shm        
tmpfs                    4.1G         6.9M         4.1G    1% /tmp            
/dev/sda2              268.4M        86.1M       182.4M   33% /boot           
tmpfs                  822.2M        77.8k       822.2M    1% /run/user/1000

$ df -H
Filesystem      Size  Used Avail Use% Mounted on
dev             4.2G     0  4.2G   0% /dev
run             4.2G  1.4M  4.2G   1% /run
/dev/sda8       470G  131G  315G  30% /
tmpfs           4.2G   89M  4.1G   3% /dev/shm
tmpfs           4.2G  6.9M  4.2G   1% /tmp
/dev/sda2       269M   87M  183M  33% /boot
tmpfs           823M   78k  823M   1% /run/user/1000

$ ./target/debug/coreutils df -h
Filesystem               Size         Used    Available  Use% Mounted on       
dev                     3.8Gi            0        3.8Gi    0% /dev            
run                     3.8Gi        1.3Mi        3.8Gi    1% /run            
/dev/sda8             436.9Gi      121.9Gi      292.8Gi   30% /               
tmpfs                   3.8Gi       84.4Mi        3.7Gi    3% /dev/shm        
tmpfs                   3.8Gi        6.5Mi        3.8Gi    1% /tmp            
/dev/sda2             256.0Mi       82.1Mi      173.9Mi   33% /boot           
tmpfs                 784.1Mi       76.0Ki      784.1Mi    1% /run/user/1000

$ df -h
Filesystem      Size  Used Avail Use% Mounted on
dev             3.9G     0  3.9G   0% /dev
run             3.9G  1.4M  3.9G   1% /run
/dev/sda8       437G  122G  293G  30% /
tmpfs           3.9G   85M  3.8G   3% /dev/shm
tmpfs           3.9G  6.6M  3.9G   1% /tmp
/dev/sda2       256M   83M  174M  33% /boot
tmpfs           785M   76K  785M   1% /run/user/1000
```

### PR DESCRIPTION
**Pull request by cakebaker**
This PR makes the following changes:

- addition of `SuffixType` enum (replaces the suffix constants)
- usage of a single `to_magnitude_and_suffix` function (instead of three)
- removal of `number_prefix` dependency

Fixes #3422.

### CODE REVIEW

File: src/uu/df/src/blocks.rs [hunk 1]
```diff
@@ -220,56 +208,64 @@ mod tests {
 
     use std::env;
 
-    use crate::blocks::{to_magnitude_and_suffix, BlockSize};
+    use crate::blocks::{to_magnitude_and_suffix, BlockSize, SuffixType};
 
     #[test]
     fn test_to_magnitude_and_suffix_powers_of_1024() {
```
Comment (jfinkels) [inline src/uu/df/src/blocks.rs:214]: I have to admit, it's pretty difficult to follow the logic of `HumanReadable`, `SizeFormat`, `BlockSize`, `SuffixType`, and more, but if I'm reading this pull request correctly, we are just decoupling the value of the number (1024, 2048, 4096, etc.) from the decision of what suffix to apply (`SuffixType::IEC`, `SuffixType:SI`, etc.). So we could now call `to_magnitude_and_suffix(1024, SuffixType::SI)` if we wanted to. Is that right?

**Comment by cakebaker** [comment]
I'm not sure about the `upper_case_acronyms` lint (https://rust-lang.github.io/rust-clippy/master/index.html#upper_case_acronyms). I currently disabled it. Somehow it looks inconsistent to have `Iec` and `HumanReadableIEC`, and renaming it to `HumanReadableIec` looks a bit strange.

File: src/uu/df/src/blocks.rs (hunk 1 above)
Comment (cakebaker) [reply src/uu/df/src/blocks.rs:204]: Yes, that's correct.

Your comment made me rethink the enums you mentioned and I realized that `SizeFormat` is not necessary and I turned it into an `Option<HumanReadable>` with the latest push. I hope this reduces some of the complexity.

**Review by jfinkels — APPROVED** [review]
Fixes the bug, and removing one of the enums seems like an improvement to me.
