### PR TITLE
wc: remove leading space when printing multiple counts

### LINKED ISSUE #2173: wc: unexpected leading space when reporting two or more numbers for a given file
What happens now (using uutils `wc`):
```
$ echo "hello" > /tmp/test.txt && ./target/debug/coreutils wc -lc /tmp/test.txt
 1 6 /tmp/test.txt
```
(Notice the extra leading space in the output.)

What I expected (using GNU `wc`):
```
$ echo "hello" > /tmp/test.txt && wc -lc /tmp/test.txt
1 6 /tmp/test.txt
```

### PR DESCRIPTION
**Pull request by jfinkels**
Remove the leading space from the output of `wc` when printing two or
more types of counts.

Fixes #2173.

### CODE REVIEW

File: tests/by-util/test_wc.rs [hunk 1]
```diff
@@ -42,7 +42,7 @@ fn test_utf8() {
         .args(&["-lwmcL"])
         .pipe_in_fixture("UTF_8_test.txt")
         .run()
-        .stdout_is("   300  4969 22781 22213    79\n");
+        .stdout_is("  300  4969 22781 22213    79\n");
     // GNU returns "  300  2086 22219 22781    79"
```
Comment (jhscheer) [inline tests/by-util/test_wc.rs:46]: Is this comment/todo still relevant?

Comment (jfinkels) [reply tests/by-util/test_wc.rs:46]: Yes, the TODO is still relevant because the counts for words, characters, and bytes differ. This pull request eliminates the leading whitespace, but it does not fix any of the incorrect counts.

Comment (jfinkels) [reply tests/by-util/test_wc.rs:46]: I created issue #2185 to represent that issue.

File: src/uu/wc/src/wc.rs [hunk 2]
```diff
@@ -364,24 +369,54 @@ fn print_stats(
         min_width = 0;
     }
 
+    let mut is_first: bool = true;
+
     if settings.show_lines {
-        write!(stdout_lock, "{:1$}", result.count.lines, min_width)?;
+        if is_first {
+            write!(stdout_lock, "{:1$}", result.count.lines, min_width)?;
```
Comment (sylvestre) [inline src/uu/wc/src/wc.rs:376]: this is a lot of duplicate declarations
what about doing the string declaration (ex: "{:1$}") in the "if"
and do the write declaration online once?

Comment (jhscheer) [reply src/uu/wc/src/wc.rs:376]: this could help a little:
```rust
if !is_first {                                               
    write!(stdout_lock, " ")?;                               
}                                                            
write!(stdout_lock, "{:1$}", result.count.lines, min_width)?;
is_first = false;                                            
```

Comment (jfinkels) [reply src/uu/wc/src/wc.rs:376]: Yes, that's a bit better, I'll make that change.
