### PR TITLE
date: fix -s UTC conversion losing timezone offset

### LINKED ISSUE #10800: date: -u -s "10:30 EST" sets wrong time
```
$ TZ=UTC gdate -u -s "10:30 EST" "+%F %T %Z"
2026-02-07 15:30:00 UTC
```

```
$ TZ=UTC ./target/debug/date -u -s "10:30 EST" "+%F %T %Z"
```
Would set clock to 10:30 UTC instead of 15:30 UTC.

Potential root cause: [`date.datetime().to_zoned(TimeZone::UTC)` at line 320](https://github.com/uutils/coreutils/blob/fafa775/src/uu/date/src/date.rs#L320) strips the timezone offset and reinterprets wall-clock time as UTC.

### PR DESCRIPTION
**Pull request by yachi**
Fixes #10800

`-s` with `-u` reinterpreted wall-clock time as UTC, losing the timezone offset. Extracted the conversion into a helper to make it testable and fixed it to preserve the absolute instant.

### CODE REVIEW

File: tests/by-util/test_date.rs [hunk 1]
```diff
@@ -454,6 +454,21 @@ fn test_date_set_valid_2() {
     }
 }
 
+#[test]
+#[cfg(all(unix, not(any(target_os = "android", target_os = "macos"))))]
+fn test_date_set_utc_with_offset() {
```
Comment (ChrisDryden) [inline tests/by-util/test_date.rs]: I don't think this actually tests anything, it just checks to see if the user is root and fails. Maybe it would be better to add a unit test for this for the conversion?

Comment (ChrisDryden) [reply tests/by-util/test_date.rs]: I see there's other integration tests in here that use the -s flag, can you follow the format of those tests?

Comment (yachi) [reply tests/by-util/test_date.rs]: Thanks for the review\! Replaced the integration test with a unit test that verifies the conversion directly.

**Comment by ChrisDryden** [comment]
Thanks!
