### PR TITLE
tests/misc/coreutils.sh: Fail with invalid binary name

### LINKED ISSUE #10244: coreutils: Unknown program should fail (tests/misc/coreutils.sh)
The GNU multi-call coreutils does
```
$ /tmp/dummy
dummy: unknown program `dummy'
Try '/tmp/dummy --help' for more information.
```

### PR DESCRIPTION
**Pull request by oech3**
Fixes #10244
Also covers some (but no all of) use case for symlinking binary to `/bin/false`.

### CODE REVIEW

File: src/bin/coreutils.rs [hunk 1]
```diff
@@ -65,10 +65,12 @@ fn main() {
         if let Some(util) = validation::find_prefixed_util(binary_as_util, utils.keys().copied()) {
             // prefixed util => replace 0th (aka, executable name) argument
             Some(OsString::from(util))
-        } else {
-            // unmatched binary name => regard as multi-binary container and advance argument list
+        } else if binary_as_util.ends_with("coreutils") || binary_as_util.ends_with("box") {
```
Comment (oech3) [inline src/bin/coreutils.rs]: I don't like to have `.ends_with("box")` in the binary just for test suite. Should be covered by shebang wrapper (at different PR).

File: src/bin/coreutils.rs [hunk 2]
```diff
@@ -65,10 +65,12 @@ fn main() {
...
             uucore::set_utility_is_second_arg();
             args.next()
+        } else {
+            eprintln!("coreutils: I was probably called as symlink to false");
```
Comment (oech3) [inline src/bin/coreutils.rs]: Would not pass new `coreutils.sh`

File: src/bin/coreutils.rs (hunk 1 above)
Comment (oech3) [reply src/bin/coreutils.rs]: shebang does not work...

File: src/bin/coreutils.rs [hunk 3]
```diff
@@ -65,10 +65,13 @@ fn main() {
...
             // prefixed util => replace 0th (aka, executable name) argument
             Some(OsString::from(util))
-        } else {
-            // unmatched binary name => regard as multi-binary container and advance argument list
+        } else if binary_as_util.ends_with("utils") || binary_as_util.ends_with("box") {
+            // todo: Remove support of "*box" from binary
             uucore::set_utility_is_second_arg();
             args.next()
+        } else {
+            eprintln!("coreutils: I was probably called as symlink to false");
```
Comment (sylvestre) [inline src/bin/coreutils.rs]: could you please improve the error message ?

Comment (oech3) [reply src/bin/coreutils.rs]: `validation::not_found(&OsString::from(binary_as_util));` has everything we want to have.

**Comment by oech3** [comment]
>GNU test failed: tests/misc/coreutils.

Oops...

**Comment by sylvestre** [comment]
> GNU test failed: tests/misc/coreutils. tests/misc/coreutils is passing on 'main'. Maybe you have to rebase?

this should be fixed before

**Comment by oech3** [comment]
Waiting upstream: https://github.com/coreutils/coreutils/commit/6b32a0bbd#r174988370

**Comment by oech3** [comment]
https://github.com/uutils/coreutils/actions/runs/21112728722/job/60713727150?pr=10258#step:11:228
OK.

**Comment by sylvestre** [comment]
are you sure?

```
2026-01-18T13:51:53.7896007Z FAIL: tests/env/env
2026-01-18T13:51:53.7896197Z ===================
2026-01-18T13:51:53.7896307Z 
2026-01-18T13:51:53.7896395Z simple_echo ./simple_echo
2026-01-18T13:51:53.7896633Z error: unexpected argument '---' found
2026-01-18T13:51:53.7896815Z 
2026-01-18T13:51:53.7896918Z   tip: to pass '---' as a value, use '-- ---'
2026-01-18T13:51:53.7897104Z 
2026-01-18T13:51:53.7897250Z Usage: env [OPTION]... [-] [NAME=VALUE]... [COMMAND [ARG]...]
2026-01-18T13:51:53.7897483Z 
2026-01-18T13:51:53.7897575Z For more information, try '--help'.
2026-01-18T13:51:53.7897856Z env: use -[v]S to pass options in shebang lines
2026-01-18T13:51:53.7898225Z error: a value is required for '--unset <NAME>' but none was supplied
2026-01-18T13:51:53.7898490Z 
2026-01-18T13:51:53.7898587Z For more information, try '--help'.
2026-01-18T13:51:53.7898853Z env: use -[v]S to pass options in shebang lines
2026-01-18T13:51:53.7899146Z nice: .: Permission denied (os error 13)
2026-01-18T13:51:53.7899417Z env: '.': Permission denied
2026-01-18T13:51:53.7899652Z env: 'no_such': No such file or directory
2026-01-18T13:51:53.7899940Z env: use -[v]S to pass options in shebang lines
2026-01-18T13:51:53.7900242Z env: 'also_unlikely': No such file or directory
2026-01-18T13:51:53.7900819Z env: use -[v]S to pass options in shebang lines
2026-01-18T13:51:53.7901184Z env: '--': No such file or directory
2026-01-18T13:51:53.7901455Z env: use -[v]S to pass options in shebang lines
2026-01-18T13:51:53.7901736Z env: cannot unset 'a=b': Invalid argument
2026-01-18T13:51:53.7902010Z env: cannot unset '': Invalid argument
2026-01-18T13:51:53.7902437Z env: cannot change directory to 'empty/nonexistent': No such file or directory (os error 2)
2026-01-18T13:51:53.7902878Z FAIL tests/env/env.sh (exit status: 1)
```

**Comment by oech3** [comment]
No. needs investigation

**Comment by oech3** [comment]
merge branch was bit fast. I included invalid patch...
