### PR TITLE
nice -n huge_num true

### LINKED ISSUE #10200: nice: nice -n 2147483648 true fails
```
$ uu-nice -n 2147483648  true
nice: "2147483648" is not a valid number: number too large to fit in target type
$ gnu9.9/nice -n 4294967295 true
```

### PR DESCRIPTION
**Pull request by oech3**
Closes #10200

### CODE REVIEW

File: src/uu/nice/src/nice.rs [hunk 1]
```diff
@@ -127,10 +127,18 @@ pub fn uumain(args: impl uucore::Args) -> UResult<()> {
             match nstr.parse::<i32>() {
                 Ok(num) => num,
                 Err(e) => {
-                    return Err(USimpleError::new(
-                        125,
-                        translate!("nice-error-invalid-number", "value" => nstr.clone(), "error" => e),
-                    ));
+                    let trimmed = nstr.trim();
```
Comment (sylvestre) [inline src/uu/nice/src/nice.rs]: please add a comment

Comment (oech3) [reply src/uu/nice/src/nice.rs]: added

File: tests/by-util/test_nice.rs [hunk 2]
```diff
@@ -90,3 +90,15 @@ fn test_trailing_empty_adjustment() {
         "error: The argument '--adjustment <adjustment>' requires a value but none was supplied",
     );
 }
+
+#[test]
+fn test_nice_huge() {
+    new_ucmd!()
+        .args(&[
+            "-n",
```
Comment (sylvestre) [inline tests/by-util/test_nice.rs:98]: Only positive overflow is tested. Should add a test for negative overflow (e.g., `-999...9`) to ensure both clamping directions work.

**Comment by oech3** [comment]
Negative is root test, would not work on the CI.

File: tests/by-util/test_nice.rs (hunk 2 above)
Comment (oech3) [reply tests/by-util/test_nice.rs:98]: Negative is root test, would not work on the CI.
...
Oh yes. It should work with permission denied.

File: src/uu/nice/src/nice.rs [hunk 3]
```diff
@@ -127,10 +127,19 @@ pub fn uumain(args: impl uucore::Args) -> UResult<()> {
             match nstr.parse::<i32>() {
                 Ok(num) => num,
                 Err(e) => {
-                    return Err(USimpleError::new(
-                        125,
-                        translate!("nice-error-invalid-number", "value" => nstr.clone(), "error" => e),
-                    ));
+                    // clamp huge values
+                    let trimmed = nstr.trim();
+                    let is_num = trimmed
```
Comment (sylvestre) [inline src/uu/nice/src/nice.rs]: The variable name 'is_num' is not very descriptive - consider 'is_valid_number' or 'has_numeric_format'

File: src/uu/nice/src/nice.rs [hunk 4]
```diff
@@ -127,10 +127,19 @@ pub fn uumain(args: impl uucore::Args) -> UResult<()> {
...
+                        .chars()
+                        .all(|c| c.is_ascii_digit() || c == '-' || c == '+');
```
Comment (sylvestre) [inline src/uu/nice/src/nice.rs]: The character validation logic allows multiple '-' or '+' signs anywhere in the string (e.g., '1-2+3' would pass)

File: src/uu/nice/src/nice.rs [hunk 5]
```diff
@@ -127,10 +127,19 @@ pub fn uumain(args: impl uucore::Args) -> UResult<()> {
...
+                    if is_num {
+                        if trimmed.starts_with('-') { -30 } else { 30 }
```
Comment (sylvestre) [inline src/uu/nice/src/nice.rs]: Hard-coded magic numbers -30 and 30 should be constants with descriptive names

Comment (oech3) [reply src/uu/nice/src/nice.rs]: Is `i32::MIN` and `i32::MAX` OK?

File: src/uu/nice/src/nice.rs (hunk 3 above)
Comment (oech3) [reply src/uu/nice/src/nice.rs]: Switched to `is_valid_number`

File: src/uu/nice/src/nice.rs (hunk 4 above)
Comment (oech3) [reply src/uu/nice/src/nice.rs]: Updated

File: src/uu/nice/src/nice.rs [hunk 6]
```diff
@@ -127,10 +127,26 @@ pub fn uumain(args: impl uucore::Args) -> UResult<()> {
             match nstr.parse::<i32>() {
                 Ok(num) => num,
                 Err(e) => {
-                    return Err(USimpleError::new(
-                        125,
-                        translate!("nice-error-invalid-number", "value" => nstr.clone(), "error" => e),
-                    ));
+                    // clamp huge values
+                    let trimmed = nstr.trim();
```
Comment (sylvestre) [inline src/uu/nice/src/nice.rs]: i think moving it into a function could help with readability

File: tests/by-util/test_nice.rs [hunk 7]
```diff
@@ -90,3 +90,20 @@ fn test_trailing_empty_adjustment() {
...
+            "99999999999999999999999999999999999999999999999999999999999999999999999999999999999999999",
+            "true",
+        ])
+        .succeeds()
+        .no_stdout();
+}
+
+#[test]
+fn test_nice_huge_negative() {
+    new_ucmd!().args(&["-n", "-9999999999", "true"]).succeeds(); // permission denied
```
Comment (sylvestre) [inline tests/by-util/test_nice.rs]: please also test with -2+4 as input (things like this)

File: src/uu/nice/src/nice.rs (hunk 6 above)
Comment (oech3) [reply src/uu/nice/src/nice.rs]: Is this operation duplicated at somethere?

File: src/uu/nice/src/nice.rs [hunk 8]
```diff
@@ -126,12 +127,16 @@ pub fn uumain(args: impl uucore::Args) -> UResult<()> {
...
-                Err(e) => {
-                    return Err(USimpleError::new(
-                        125,
-                        translate!("nice-error-invalid-number", "value" => nstr.clone(), "error" => e),
-                    ));
-                }
+                Err(e) => match e.kind() {
+                    IntErrorKind::PosOverflow => i32::MAX,
+                    IntErrorKind::NegOverflow => i32::MIN,
+                    _ => {
```
Comment (oech3) [inline src/uu/nice/src/nice.rs]: Refactored via {Pos,Neg}Overflow

File: src/uu/nice/src/nice.rs (hunk 5 above)
Comment (oech3) [reply src/uu/nice/src/nice.rs]: Defined a var instead of using i32::MAX

File: tests/by-util/test_nice.rs [hunk 9]
```diff
@@ -90,3 +90,25 @@ fn test_trailing_empty_adjustment() {
...
+}
+
+#[test]
+fn test_sign_middle() {
+    new_ucmd!().args(&["-n", "-2+4", "true"]).fails();
```
Comment (sylvestre) [inline tests/by-util/test_nice.rs]: What is the error message?

Comment (oech3) [reply tests/by-util/test_nice.rs]:
```
.stderr_contains("invalid");
}
//uu: "-2+4" is not a valid number: invalid digit found in string
//gnu: invalid adjustment `-2+4'
//Both message is fine
```

File: src/uu/nice/src/nice.rs [hunk 10]
```diff
@@ -115,6 +116,7 @@ pub fn uumain(args: impl uucore::Args) -> UResult<()> {
             format!("getpriority: {}", Error::last_os_error()),
         ));
     }
+    let nice_bound = 50;
```
Comment (sylvestre) [inline src/uu/nice/src/nice.rs]: Hard-coded magic number 50 should be a named constant like MAX_NICE_OVERFLOW or similar

File: tests/by-util/test_nice.rs [hunk 11]
```diff
@@ -90,3 +90,32 @@ fn test_trailing_empty_adjustment() {
...
+            "99999999999999999999999999999999999999999999999999999999999999999999999999999999999999999",
+            "true",
+        ])
+        .succeeds()
+        .no_stdout();
+}
+
+#[test]
+fn test_nice_huge_negative() {
+    new_ucmd!().args(&["-n", "-9999999999", "true"]).succeeds(); // permission denied
```
Comment (sylvestre) [inline tests/by-util/test_nice.rs]: Negative overflow test should verify actual niceness value is clamped to expected bound
