### PR TITLE
cp: Do not dereference symlink even when dangling - fix issue #3364

### LINKED ISSUE #3364: cp: --no-dereference option should copy dangling symbolic link but doesn't
The `-P` (`--no-dereference`) option in uutils `cp` does not match the behavior of GNU `cp` when attempting to copy a symbolic link that points to a file that does not exist.

GNU cp:
```sh
$ ln -s no-such-file dangle && cp -P dangle d2
# no output, d2 is created
```

uutils cp:
```sh
$ ln -s no-such-file dangle && ./target/release/cp -P dangle d2
./target/release/cp: not writing through dangling symlink 'd2'
```

### PR DESCRIPTION
**Pull request by anastygnome**
Fixes an issue with cp not copying symlinks in spite of the -P  (no dereference option) 
fixes #3364
```console
> ln -s no-such-file dangle
> LANG=C cp dangle d2
cp: cannot stat 'dangle': No such file or directory
[1]> LANG=C cp -P dangle d2
> rm d2
>  ./uu_cp dangle d2
cp: cannot stat 'dangle': No such file or directory
[1]> ./uu_cp -P dangle d2
> rm d2
```

### CODE REVIEW

File: src/uu/cp/src/cp.rs [hunk 1]
```diff
@@ -1286,10 +1286,13 @@ fn copy_file(
...
     }
 
-    // Fail if dest is a dangling symlink or a symlink this program created previously
+    // Fail if upon dereferencing symlink,
+    // dest a dangling symlink or a symlink this program created previously.
+
     if fs::symlink_metadata(dest)
         .map(|m| m.file_type().is_symlink())
         .unwrap_or(false)
+        && !options.dereference
```
Comment (anastygnome) [inline src/uu/cp/src/cp.rs:1295]: maybe swapping the two clauses of the and test should be better to short-circuit the fs call.

File: tests/by-util/test_cp.rs [hunk 2]
```diff
@@ -1496,14 +1496,29 @@ fn test_copy_through_just_created_symlink() {
...
         .arg("target")
         .fails()
-        .stderr_only("cp: not writing through dangling symlink 'target'");
+        .stderr_only(
+        "cp: cannot stat 'dangle': No such file or directory (os error 2)",
+    );
+}
+
+#[test]
+fn test_copy_through_dangling_symlink_dereference() {
```
Comment (tertsdiepraam) [inline tests/by-util/test_cp.rs:1512]: Shouldn't the name here be "no_dereference"?

**Review by tertsdiepraam — COMMENTED** [review]
I think your test cases are backwards from your example in the PR. I.e. you do
```bash
cp (-P) link file # in the example
cp (-P) file link # in the test
```
It's probably best to test for both and check what the expected behaviour should be.

File: tests/by-util/test_cp.rs (hunk 2 above)
Comment (anastygnome) [reply tests/by-util/test_cp.rs:1512]: yup, will fix

**Comment by tertsdiepraam** [comment]
Did you remove the tests from the PR? I thought they were really close to being correct and it would be great to have them!

**Comment by tertsdiepraam** [comment]
Don't worry about the failing Windows tests, I'm trying to fix those here: https://github.com/uutils/coreutils/pull/3460

**Comment by anastygnome** [comment]
@tertsdiepraam I had forgot to add the tests. There are now back in the PR.

**Comment by anastygnome** [comment]
I'm cleaning UP history, please stop for now

**Comment by anastygnome** [comment]
@tertsdiepraam  @sylvestre 
please resume the workflow

**Comment by sylvestre** [comment]
please rename the commit for something more explicit

**Comment by anastygnome** [comment]
will do

**Comment by anastygnome** [comment]
@sylvestre

**Comment by anastygnome** [comment]
sorry for the hassle @sylvestre my PC is driving me nuts. 

Just caught a nasty bug.

**Comment by sylvestre** [comment]
yeah, please push when it is ready ;)

**Comment by anastygnome** [comment]
@sylvestre I'm done

**Comment by anastygnome** [comment]
Can we enable feature is symlink or do you want me to revert this part of the commit @sylvestre

**Comment by sylvestre** [comment]
For now, we haven't discussed about bumping MinRustV.

The error for others:
`error[E0658]: use of unstable library feature 'is_symlink'`

**Comment by anastygnome** [comment]
I've brung back the old method using metadata for now and added a comment.

**Comment by anastygnome** [comment]
rebased to pass tests  from main @sylvestre

**Comment by anastygnome** [comment]
@sylvestre failing test is unrelated, good to be merged

File: tests/by-util/test_cp.rs [hunk 3]
```diff
@@ -1505,6 +1505,18 @@ fn test_copy_through_dangling_symlink() {
...
         .stderr_only("cp: not writing through dangling symlink 'target'");
 }
+#[test]
+fn test_copy_through_dangling_symlink_no_dereference() {
+    let (at, mut ucmd) = at_and_ucmd!();
+    at.touch("file");
+    at.symlink_file("nonexistent", "target");
+    ucmd.arg("file")
+        .arg("-P")
+        .arg("target")
```
Comment (sylvestre) [inline tests/by-util/test_cp.rs:1515]: According to https://github.com/uutils/coreutils/issues/3364#issue-1191201385=
it should be a bit different (and renamed to facilitate the match)

```suggestion
    at.symlink_file("no-such-file", "dangle");
    ucmd.arg("-P")
        .arg("dangle")
        .arg("d2")
```

File: tests/by-util/test_cp.rs [hunk 4]
```diff
@@ -1505,6 +1505,17 @@ fn test_copy_through_dangling_symlink() {
         .fails()
         .stderr_only("cp: not writing through dangling symlink 'target'");
 }
+#[test]
```
Comment (sylvestre) [inline tests/by-util/test_cp.rs:1508]:
```suggestion
}

#[test]
```

**Comment by sylvestre** [comment]
why did you push over my changes ?

**Comment by anastygnome** [comment]
@sylvestre thank the colleague who put force by default in my pull and push parameters. 
fixed abd brought back yours. They had been squashed.

I just squashed the add space commit to reduce noised

**Comment by anastygnome** [comment]
failing test has been corrected

**Comment by sylvestre** [comment]
thanks :)
