### PR TITLE
Fix hardware capabilities detection; cksum --debug

### LINKED ISSUE #9518: cksum: Hardware detection fails to take `GLIBC_TUNABLES` env var into account
When trying to run the `cksum.sh` test, I realized that our implementation does not read `GLIBC_TUNABLES`.

Example:
```
(venv_pe) peron in ~/playground/coreutils on cksum-improvements λ GLIBC_TUNABLES='glibc.cpu.hwcaps=-AVX512F,-AVX2,-AVX,-PMULL' ../gnu/src/cksum --debug
cksum: avx512 support not detected
cksum: avx2 support not detected
cksum: pclmul support not detected

(venv_pe) peron in ~/playground/coreutils on cksum-improvements λ GLIBC_TUNABLES='glibc.cpu.hwcaps=-AVX512F,-AVX2,-AVX,-PMULL' ./target/debug/cksum --debug
cksum: avx512 support not detected
cksum: using avx2 hardware support
cksum: using pclmul hardware support

(venv_pe) peron in ~/playground/coreutils on cksum-improvements λ ./target/debug/cksum --debug            
cksum: avx512 support not detected
cksum: using avx2 hardware support
cksum: using pclmul hardware support
```

### PR DESCRIPTION
**Pull request by RenjiSann**
This MR fixes the GNU `cksum.sh` by correctly taking in account the `GLIBC_TUNABLES` env var

Fixes #9518

### CODE REVIEW

**Comment by naoNao89** [comment]
My string approach worked but was naive. Your enum-based design with TryFrom validation is the right way: type-safe, O(log n) lookups, feature alias support. Excellent work
```rust
            avx512: detect_avx512() && !disabled.contains(&"AVX512F".to_string()),
            avx2: detect_avx2() && !disabled.contains(&"AVX2".to_string()),
            pclmul: detect_pclmul() && !disabled.contains(&"PMULL".to_string()),
            vmull: detect_vmull() && !disabled.contains(&"VMULL".to_string()),
            sse2: detect_sse2() && !disabled.contains(&"SSE2".to_string()),
            asimd: detect_asimd() && !disabled.contains(&"ASIMD".to_string()),
```

File: src/uucore/src/lib/features/hardware.rs [hunk 1]
```diff
@@ -17,130 +22,158 @@
...
-            features.push("SSE2");
+        if detect_sse2() {
+            set.insert(HardwareFeature::Sse2);
         }
-        if self.asimd {
-            features.push("ASIMD");
+        if detect_asimd() {
+            set.insert(HardwareFeature::Asimd);
         }
-        features
```
Comment (cakebaker) [inline src/uucore/src/lib/features/hardware.rs]: Here a functional approach might be cleaner, something like:
```rust
        let set = [
            (HardwareFeature::Avx512, detect_avx512 as fn() -> bool),
            (HardwareFeature::Avx2, detect_avx2),
            (HardwareFeature::PclMul, detect_pclmul),
            (HardwareFeature::Vmull, detect_vmull),
            (HardwareFeature::Sse2, detect_sse2),
            (HardwareFeature::Asimd, detect_asimd),
        ]
        .into_iter()
        .filter_map(|(feature, detect_func)| detect_func().then_some(feature))
        .collect();
```

Comment (RenjiSann) [reply src/uucore/src/lib/features/hardware.rs]: Oh, that looks really clean, I will switch to that. Thanks !

**Comment by cakebaker** [comment]
> Congrats! The gnu test tests/cksum/cksum is no longer failing!

Kudos, good work!
