### PR TITLE
Fix edge case for du on mac

### LINKED ISSUE #1155: du on mac is subtly different
I have been able to get coreutils' du to give a different output to the standard du on my mac os: High Sierra. 

> 
> sudo ~/dev/rust/coreutils/target/release/uutils du -d 1 /private/var/db/ConfigurationProfiles/
> du: error: Operation not permitted (os error 1)
> 
> sudo du -d 1 /private/var/db/ConfigurationProfiles/
> 0	/private/var/db/ConfigurationProfiles//Settings
> 0	/private/var/db/ConfigurationProfiles//Setup
> du: /private/var/db/ConfigurationProfiles//Store: Operation not permitted
> 0	/private/var/db/ConfigurationProfiles/
> 
As you can see above coreutils' du exits on the first read error where as old du lists the error and then keeps working on the other files. 

Is this important enough to be investigated further? If this isn't important then just close this issue.

I'm happy to dig in to this a little more in the future.

### PR DESCRIPTION
**Pull request by bootandy**
When du encounters a file that cannot be read it logs an error and
continues to analysise the rest of the directory. This behaviour brings
it inline with the original du.

fixes #1155

### CODE REVIEW

File: src/du/du.rs [hunk 1]
```diff
@@ -91,16 +91,23 @@ fn du(mut my_stat: Stat, options: &Options, depth: usize) -> Box<DoubleEndedIter
...
-            if this_stat.is_dir {
-                futures.push(du(this_stat, options, depth + 1));
-            } else {
-                my_stat.size += this_stat.size;
-                my_stat.blocks += this_stat.blocks;
-                if options.all {
-                    stats.push(this_stat);
-                }
+            match f {
+                Ok(entry) => match fs::symlink_metadata(entry.path()) {
```
Comment (Arcterus) [inline src/du/du.rs]: I’d prefer if you just change `Stat::new()` so that it returns `io::Result<Stat>`.  That way we won’t have to call `fs::symlink_metadata()` twice for every entry.

Comment (bootandy) [reply src/du/du.rs]: I considered that but thought it would be weird for a constructor to return a result - Is it considered generally ok to do this in rust?

No problem though I'm happy to change it.

Comment (Arcterus) [reply src/du/du.rs]: It’s weirder for it to abort the program IMO.  I think it’s fine, but you could change `new` to `from_entry` or something if you’d prefer.

File: src/du/du.rs [hunk 2]
```diff
@@ -54,17 +54,21 @@ struct Stat {
...
-            path: path,
-            is_dir: metadata.is_dir(),
-            size: metadata.len(),
-            blocks: metadata.blocks() as u64,
-            nlink: metadata.nlink() as u64,
-            created: metadata.mtime() as u64,
-            accessed: metadata.atime() as u64,
-            modified: metadata.mtime() as u64,
+    fn new(path: PathBuf) -> Result<Stat> {
+        match fs::symlink_metadata(&path) {
```
Comment (Arcterus) [inline src/du/du.rs]: I’d prefer this to be:
```rust
let metadata = fs::symlink_metadata(&path)?;
Ok(Stat {
    // stuff
})
```

Comment (bootandy) [reply src/du/du.rs]: yes that's nicer. I'll fix.

**Comment by Arcterus** [comment]
Thanks!
