### PR TITLE
factor: trim also null-chars

### LINKED ISSUE #11097: factor: echo -e "3\0" | factor fails
```
$ echo -e "3\0" | latest-commit/uu-factor
factor: warning: $'3\x00': invalid digit found in string
$ echo -e "3\0" | gnu9.10/factor
3: 3
```

### PR DESCRIPTION
**Pull request by yotam-medini**
Closes #11097
In  fn write_factors_str() @ factor.rs  
trim also null characters.

### CODE REVIEW

**Comment by oech3** [comment]
Please move "Closes ISSUE_TAG" to 1st coment from title.

**Comment by cakebaker** [comment]
Can you please add a test to `tests/by_util/test_factor.rs` to ensure we don't regress in the future? Thanks.

**Comment by oech3** [comment]
This issue is pipe from stdin specific. Can we add test with our framework?

**Comment by cakebaker** [comment]
@oech3 I'm not sure I understand your question correctly, but `pipe_in` should work for this case.

**Comment by oech3** [comment]
Thankyou.

**Comment by yotam-medini** [comment]
Do I need to do anything here ?
Does this pull request depends on factor, coreutils: backport 2 GNU tests#11185 ?

**Comment by oech3** [comment]
You still need to add Rust native test if possible.

**Comment by yotam-medini** [comment]
Just added:
test_factor.rs += test_trim_null_chars

File: tests/by-util/test_factor.rs [hunk 1]
```diff
@@ -54,6 +54,15 @@ fn test_repeated_exponents() {
         .no_stderr();
 }
 
+#[test]
+fn test_trim_null_chars() {
+    new_ucmd!()
+        .pipe_in_fixture("42_with_null_char.txt")
```
Comment (cakebaker) [inline tests/by-util/test_factor.rs]: While this works fine, using a fixture is a bit overkill in this case and I would pipe in the input directly:

```suggestion
        .pipe_in("42\0")
```

**Comment by cakebaker** [comment]
Thanks for your PR!

**Comment by oech3** [comment]
Hmm... backported gnu test does not pass.

**Comment by yotam-medini** [comment]
This is my first uutils activity. Please forgive my basic naive questions:
1. How can I run this gnu test myself locally ?
2. Will you open a bug for this ? Shall I work on this referring to the same task ?

**Comment by oech3** [comment]
It seems new test what I tried to backport has more cases https://github.com/uutils/coreutils/actions/runs/22672349162/job/65719523099?pr=11185#step:8:3223 .

[This](https://github.com/uutils/coreutils/blob/e4d943bf07586951cda6c3b92d0b978b1b13c72b/DEVELOPMENT.md?plain=1#L226) is the guide to run GnuTests locally, but the doc is incomplete. It lacks some required utils to run it correctly e.g. `libacl`.

**Comment by yotam-medini** [comment]
@oech3, 
I build automake-1.18 from source. Put the executable in my PATH.
apt-get install quilt libacl1-dev .
Still bash util/build-gnu.sh failed with attached log
[build-gnu.log](https://github.com/user-attachments/files/25748226/build-gnu.log)

I wish I could help here - but I need an environment that is easier to set.

**Comment by oech3** [comment]
It is because GNU 9.10 tarball require too new automake
https://github.com/uutils/coreutils/blob/e4d943bf07586951cda6c3b92d0b978b1b13c72b/.github/workflows/GnuTests.yml#L60-L61
which is missing from Ubuntu LTS.

**Comment by yotam-medini** [comment]
The attached
[factor-test.py](https://github.com/user-attachments/files/25750531/factor-test.py)
is derived from gnu/tests/factor/factor.pl
I ignored the error cases.
All 45 positive test ran fine.
So it could be that handling error input is inconsistent.
