### PR TITLE
tac: support non-UTF-8 separator

### LINKED ISSUE #9502: `tac` cannot handle seperators that are not UTF-8.
Using uutils built from commit f6d581fc48027528a89e58236a66475aca4e3c80:
```
$ LC_ALL=en_US.iso8859-1 tac --separator=$(printf '\xe9') < /dev/null
error: invalid UTF-8 was detected in one or more arguments

For more information, try '--help'.
```

### PR DESCRIPTION
**Pull request by victor-prokhorov**
fixes #9502

open question: GNU tac also accepts non-UTF-8 separators in regex mode. right now, in this pr i return an error. should i handle this in the same PR, or i should do it in another?

### CODE REVIEW

**Comment by ChrisDryden** [comment]
The ultimate goal it to get the non utf-8 stuff to be fully matching how gnu handles it, can you try to handle it in the same pr?

**Comment by ChrisDryden** [comment]
By fixing this it should also fix the tac-locale test so you can use that to guide you on whether the fix is working properly

**Comment by victor-prokhorov** [comment]
i found this trick of turning the `u` flag here https://docs.rs/regex/1.10.4/regex/#opt-out-of-unicode-support, should it be included in the inline documentation?
i used `expect` because the invariance is upheld by construction, is returning a result preferred? please advise
the integration tests i wrote somewhat overlap gnu test scripts, let me know if you prefer them removed

File: src/uu/tac/src/tac.rs [hunk 1]
```diff
@@ -228,91 +233,102 @@ fn buffer_tac(data: &[u8], before: bool, separator: &str) -> std::io::Result<()>
...
+    let mut last_byte: Option<u8> = None;
 
-    while let Some(c) = chars.next() {
+    while let Some(b) = bytes.get(i) {
         let is_escaped = prev_was_backslash;
         prev_was_backslash = false;
 
-        match c {
+        match b {
+            _ if inside_brackets && !b.is_ascii() => {
```
Comment (ChrisDryden) [inline src/uu/tac/src/tac.rs:250]: TIL GNU also ignores non-ASCII bytes inside bracket expressions

File: src/uu/tac/src/tac.rs [hunk 2]
```diff
@@ -228,91 +233,102 @@ fn buffer_tac(data: &[u8], before: bool, separator: &str) -> std::io::Result<()>
...
-                    result.push('\\');
+                    result.push(b'\\');
                 }
-                result.push(c);
-                last_char = Some(c);
+                result.push(*b);
+                last_byte = Some(*b);
+            }
+            _ if !b.is_ascii() => {
+                let _ = write!(result, r"(?-u:\x{b:02x})");
```
Comment (ChrisDryden) [inline src/uu/tac/src/tac.rs:312]: Great find!

**Comment by ChrisDryden** [comment]
Thanks!
