### PR TITLE
cp: handle edge cases when dest is a symlink 

### LINKED ISSUE #2601: Cat Windows 10 does not work
when building on windows 10 trying to run cat gives this error
```

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: Uncategorized, message: "Incorrect function." }', src\uu\cat\src/cat.rs:375:71
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by miDeb**
- Refactor identical file detection into `uucore`
- Use refactored file identity detection in `cat` (fixes #2601)
- Fix edge cases in `cp` when the destination is a symlink.
  I also added some `FIXME` comments to `cp` about issues I found but didn't fix in this PR.

### CODE REVIEW

**Comment by sylvestre** [comment]
Sorry, it is conflicting, could you please fix that? thanks

**Comment by miDeb** [comment]
Should be fixed now! Sorry for being so slow, but since school started again I have much less time.

**Review by tertsdiepraam — APPROVED** [review]

**Comment by tertsdiepraam** [comment]
The tests doesn't seem to have been run. Has the "rerun checks" button disappeared from GitHub? @miDeb could you check whether you can trigger them?

**Comment by miDeb** [comment]
I also can't find it. I'll try closing and reopening the PR, I think that should trigger a rerun.

**Comment by miDeb** [comment]
A test on windows seems to be failing because of a bug in `sort`; I'll fix that in another PR.

**Comment by miDeb** [comment]
Not sure why all CI jobs got cancelled, I'll rerun them once more...

**Comment by tertsdiepraam** [comment]
Interesting, GitHub retriggered the CI because I made another PR with the same commits. I'll close that one and merge this, because it's all green.

File: src/uucore/src/lib/features/fs.rs [hunk 1]
```diff
@@ -32,6 +35,114 @@ macro_rules! has {
     };
 }
 
+/// Information to uniquely identify a file
+pub struct FileInformation(
```
Comment (tertsdiepraam) [inline src/uucore/src/lib/features/fs.rs:39]: I just wanted to comment that this API is really nice :)

**Comment by miDeb** [comment]
Thanks!
