### PR TITLE
``cp``: Added overwrite detection for existing symlinks

### LINKED ISSUE #6265: cp: symlink overwrite-detection is broken
Steps to reproduce:
- Create two regular files, `README.md` and `good/README.md`, and an initially-empty directory `tmp/`.
- Inside `tmp`, create an empty regular file `foo`, and a symlink `README.md` that points to `foo`.
- Try to copy `README.md` and `good/README.md` to `tmp/`

Expected result: `README.md` is copied to `tmp/` into the file `foo`, and the second attempt is **aborted**, leading to an error message and a non-zero (failure) exit code.

Actual result: `README.md` is copied to `tmp/` into the file `foo`, and the second attempt is **successful**, leading to `foo` containing the contents of the second file, no error message, and a zero (success) exit code.

Demonstrator:

```console
$ mkdir -p good && cp README.md good/README.md
$ rm -rf tmp/ && mkdir tmp/ && ln -s foo tmp/README.md && touch tmp/foo
$ ../gnu/src/cp README.md good/README.md tmp # Yes error!
../gnu/src/cp: will not copy 'good/README.md' through just-created symlink 'tmp/README.md'
[$? = 1]
$
```

```console
$ mkdir -p good && cp README.md good/README.md
$ rm -rf tmp/ && mkdir tmp/ && ln -s foo tmp/README.md && touch tmp/foo
$ cargo run cp README.md good/README.md tmp # No error?!
$
```

Found while reviewing #6208

### PR DESCRIPTION
**Pull request by AnirbanHalder654322**
Fixes #6265

### CODE REVIEW

**Review by BenWiederhake — CHANGES_REQUESTED** [review]
Thanks for tackling this issue!

By slightly changing the test setup, you (accidentally?) created another interesting test case, please keep it! :D

File: tests/by-util/test_cp.rs [hunk 1]
```diff
@@ -2660,6 +2660,42 @@ fn test_copy_through_dangling_symlink_no_dereference() {
...
+    let ts = TestScenario::new(util_name!());
+    let at = &ts.fixtures;
+
+    at.mkdir("good");
+    at.mkdir("tmp");
+    at.touch("README");
+    at.touch("good/README");
+
+    at.write("README", "file1");
+    at.write("good/README", "file2");
```
[the remark this answers is not in the document]
Comment (AnirbanHalder654322) [reply tests/by-util/test_cp.rs:2674]: Dang, thats so obvious but i missed it . I will remove the touch calls.

**Comment by AnirbanHalder654322** [comment]
The state can be refactored and encapsulated within a struct . Perhaps that can be addressed in a future PR .

File: src/uu/cp/src/copydir.rs [hunk 2]
```diff
@@ -213,14 +213,15 @@ where
     // `path.ends_with(".")` does not seem to work
     path.as_ref().display().to_string().ends_with("/.")
 }
-
+#[allow(clippy::too_many_arguments)]
```
Comment (BenWiederhake) [inline src/uu/cp/src/copydir.rs:216]: Oof. Yes, that's an okayish temporary solution.

Can I ask you to make an attempt to make a struct out of this in the next PR?

File: tests/by-util/test_cp.rs [hunk 3]
```diff
@@ -2660,6 +2660,71 @@ fn test_copy_through_dangling_symlink_no_dereference() {
...
+
+    ts.ucmd()
+        .arg("README")
+        .arg("good/README")
+        .arg("tmp")
+        .fails()
+        .stderr_only(if cfg!(target_os = "windows") {
+            "cp: will not copy 'good/README' through just-created symlink 'tmp\\README'\n"
+        } else if cfg!(target_os = "macos") {
+            "cp: will not overwrite just-created 'tmp/README' with 'good/README'\n"
```
Comment (BenWiederhake) [inline tests/by-util/test_cp.rs:2689]: Symlinks on windows? I thought windows doesn't have symlinks?

Why doesn't the macos error message say the same thing? I'm confused.

File: tests/by-util/test_cp.rs [hunk 4]
```diff
@@ -2660,6 +2660,71 @@ fn test_copy_through_dangling_symlink_no_dereference() {
...
+    at.mkdir("good");
+    at.mkdir("tmp");
+    at.write("README", "file1");
+    at.write("good/README", "file2");
+
+    ts.ccmd("ln")
+        .arg("-s")
+        .arg("foo")
+        .arg("tmp/README")
+        .succeeds();
```
Comment (BenWiederhake) [inline tests/by-util/test_cp.rs:2714]:
```suggestion
    at.symlink_file("foo", "tmp/README");
```
Same in the other places.

File: src/uu/cp/src/cp.rs [hunk 5]
```diff
@@ -1934,6 +1940,17 @@ fn copy_file(
                 dest.display()
             )));
         }
+        // Fail if cp tries to copy two sources of the same name into a single symlink
+        // Example: "cp file1 dir1/file1 tmp" where "tmp" is a directory containing a symlink "file1" pointing to a file named "foo".
+        // foo will contain the contents of "file1" and "dir1/file1" will not be copied over to "tmp/file1"
+        if copied_destinations.contains(dest) {
+            return Err(Error::Error(format!(
+                "will not copy '{}' through just-created symlink '{}'",
```
Comment (BenWiederhake) [inline src/uu/cp/src/cp.rs:1948]: Apparently there needs to be some other condition, too, because GNU does not always talk about a "just-created symlink", even though it was just created:

```console
$ mkdir src1 src2; touch src1/file src2/file  # setup
$ cp -vs src1/file src2/file .
'src1/file' -> './file'
cp: will not overwrite just-created './file' with 'src2/file'
[$? = 1]
$ rm file
$ cargo run -q cp -vs src1/file src2/file .
'src1/file' -> './file'
cp: will not copy 'src2/file' through just-created symlink './file'
[$? = 1]
```

However, there is no actual difference in behavior, so unless the GNU tests specifically check for this error message, I'd say this error message is good.

**Review by BenWiederhake — CHANGES_REQUESTED** [review]
Mostly just questions, there's probably not much to do anymore.

Also, can I convince you to remove `#[allow(clippy::too_many_arguments)]` in your next PR?

File: tests/by-util/test_cp.rs (hunk 3 above)
Comment (AnirbanHalder654322) [reply tests/by-util/test_cp.rs:2689]: I believe newer windows have symlinks. https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/
About the macos error message, i have no clue why it doesn't print the same thing. The CI was complaining so i changed it (its arguably lazy coding). We really need access to a mac for testing the cp behaviour on there.

File: src/uu/cp/src/copydir.rs (hunk 2 above)
Comment (AnirbanHalder654322) [reply src/uu/cp/src/copydir.rs:216]: Sure, i can make i can attempt at it, in a future PR sometime next week.  I was personally thinking about clumping the HashSet<FileInformation> types into a struct and keeping the rest of the arguments as it is . But we could discuss it in the future PR.

File: src/uu/cp/src/cp.rs (hunk 5 above)
Comment (AnirbanHalder654322) [reply src/uu/cp/src/cp.rs:1948]: Interesting, i wonder what other conditions they care about . It does seem like we are really lacking on the edge cases regarding symlinks and copying to directories in general.

**Review by BenWiederhake — APPROVED** [review]
LGTM! We're still bad at handling symlinks, but this is a step in the right direction. Yay! :)
