### PR TITLE
test_install: Add sleeps

### LINKED ISSUE #1927: test_install_copy_then_compare_file_with_extra_mode is broken
Since https://github.com/uutils/coreutils/pull/1811 landed, the travis CI is failing:
https://travis-ci.org/github/uutils/coreutils/jobs/764628239
@Goorzhel could you please have a look? thanks

```
---- test_install::test_install_copy_then_compare_file_with_extra_mode stdout ----

current_directory_resolved: 

touch: /tmp/.tmpMrXngr/test_install_copy_then_compare_file_with_extra_mode_a1

run: /home/travis/build/uutils/coreutils/target/debug/coreutils install -C test_install_copy_then_compare_file_with_extra_mode_a1 test_install_copy_then_compare_file_with_extra_mode_a2

run: /home/travis/build/uutils/coreutils/target/debug/coreutils install -C test_install_copy_then_compare_file_with_extra_mode_a1 test_install_copy_then_compare_file_with_extra_mode_a2 -m 1644

thread 'test_install::test_install_copy_then_compare_file_with_extra_mode' panicked at 'assertion failed: before != after_install_sticky', /home/travis/build/uutils/coreutils/tests/by-util/test_install.rs:487:5

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

failures:

    test_install::test_install_copy_then_compare_file_with_extra_mode
```

I fixed the /dev/null issue in https://github.com/uutils/coreutils/pull/1925

### PR DESCRIPTION
**Pull request by Goorzhel**
To ensure timestamps don't match. Fixes #1927.

### CODE REVIEW

File: tests/by-util/test_install.rs [hunk 1]
```diff
@@ -2,6 +2,7 @@ use crate::common::util::*;
 use filetime::FileTime;
 use rust_users::*;
 use std::os::unix::fs::PermissionsExt;
+use std::thread::sleep;
```
Comment (sylvestre) [inline tests/by-util/test_install.rs:5]:
```suggestion
#[cfg(target_os = "linux")]
use std::thread::sleep;
```

**Comment by Goorzhel** [comment]
```
❯ git pull origin 1927 && git log --oneline | head -1
<...>
a655117a `std::thread::sleep` needs target_os
```

Ah, okay, that emoji stuff is just GitHub being GitHub.
