### PR TITLE
kill: return 1 and gnu style stderr in case of no pid

### LINKED ISSUE #6221: kill: should fail if no PID is specified
When running GNU `kill` without a PID, it fails and shows an error message:
```
$ ~/projects/gnu/src/kill
/home/dho/projects/gnu/src/kill: no process ID specified
Try '/home/dho/projects/gnu/src/kill --help' for more information.
$ echo $?
1
```
uutils `kill`, on the other hand, doesn't fail and there is no output:
```
$ cargo run --features=unix kill
$ echo $?
0
```

### PR DESCRIPTION
**Pull request by jadijadi**
including a new test for "no pid provided" use case.

closes #6221

### CODE REVIEW

File: src/uu/kill/src/kill.rs [hunk 1]
```diff
@@ -64,8 +64,16 @@ pub fn uumain(args: impl uucore::Args) -> UResult<()> {
                 .try_into()
                 .map_err(|e| std::io::Error::from_raw_os_error(e as i32))?;
             let pids = parse_pids(&pids_or_signals)?;
-            kill(sig, &pids);
-            Ok(())
+            if pids.is_empty() {
+                Err(USimpleError::new(
+                    1,
+                    "no process ID specified\n\
+                              Try --help for more information.",
```
Comment (BenWiederhake) [inline src/uu/kill/src/kill.rs:71]: That indentation feels a bit excessive. How about this?
```suggestion
                    "no process ID specified\n\
                     Try --help for more information.",
```

**Review by BenWiederhake — COMMENTED** [review]
Does exactly what is says on the tin. Thank you!

Can I ask you to change the excessive indentation?

(Also, sorry about the "review self-request", I fully expected it to be an error message, because self-requesting makes to sense to me, and I was curious how github handled that edge case.)

**Comment by jadijadi** [comment]
> Does exactly what is says on the tin. Thank you!
> Can I ask you to change the excessive indentation?

Thank you @BenWiederhake . Also applied your suggested change.

**Comment by cakebaker** [comment]
Thanks!

**Comment by sylvestre** [comment]
@jadijadi thanks for sharing your experience here :) https://www.youtube.com/watch?v=wzWNkNPHJx0
