### PR TITLE
od: fix handling of non-ascii chars

### LINKED ISSUE #8202: od incorrectly handles non ascii chars
Trying to rebuld groff on current Ubuntu devel with coreutils-uutils leads to tests errors
https://launchpadlibrarian.net/798977884/buildlog_ubuntu-questing-amd64.groff_1.23.0-9_BUILDING.txt.gz

The problem seems to be due to the "od" handling of non ascii chars

Basic example

```
$ od --version
od (GNU coreutils) 9.5

$ echo '’' | LC_ALL=C od -t c
0000000 342 200 231  \n
0000004
```

but

```
$ od --version
od 0.0.30

$echo '’' | LC_ALL=C od -t c
0000000   ’  **  **  \n
0000004
```

Longer version from groff showing a similar issue on other chars

```
$ echo '!#$%&()*+,./0123456789:;<=>?@ ABCDEFGHIJKLMNOPQRSTUVWXYZ[]_ abcdefghijklmnopqrstuvwxyz{|} neutral double quote: " closing single quote: ’ hyphen: ‐ backslash: \ modifier circumflex: ˆ opening single quote: ‘ modifier tilde: ˜ end output' | LC_ALL=C od -t c
0000000   !   #   $   %   &   (   )   *   +   ,   .   /   0   1   2   3
0000020   4   5   6   7   8   9   :   ;   <   =   >   ?   @       A   B
0000040   C   D   E   F   G   H   I   J   K   L   M   N   O   P   Q   R
0000060   S   T   U   V   W   X   Y   Z   [   ]   _       a   b   c   d
0000100   e   f   g   h   i   j   k   l   m   n   o   p   q   r   s   t
0000120   u   v   w   x   y   z   {   |   }       n   e   u   t   r   a
0000140   l       d   o   u   b   l   e       q   u   o   t   e   :    
0000160   "       c   l   o   s   i   n   g       s   i   n   g   l   e
0000200       q   u   o   t   e   :     342 200 231       h   y   p   h
0000220   e   n   :     342 200 220       b   a   c   k   s   l   a   s
0000240   h   :       \       m   o   d   i   f   i   e   r       c   i
0000260   r   c   u   m   f   l   e   x   :     313 206       o   p   e
0000300   n   i   n   g       s   i   n   g   l   e       q   u   o   t
0000320   e   :     342 200 230       m   o   d   i   f   i   e   r    
0000340   t   i   l   d   e   :     313 234       e   n   d       o   u
0000360   t   p   u   t  \n
0000365
```

vs 

```
$ echo '!#$%&()*+,./0123456789:;<=>?@ ABCDEFGHIJKLMNOPQRSTUVWXYZ[]_ abcdefghijklmnopqrstuvwxyz{|} neutral double quote: " closing single quote: ’ hyphen: ‐ backslash: \ modifier circumflex: ˆ opening single quote: ‘ modifier tilde: ˜ end output' | LC_ALL=C od -t c
0000000   !   #   $   %   &   (   )   *   +   ,   .   /   0   1   2   3
0000020   4   5   6   7   8   9   :   ;   <   =   >   ?   @       A   B
0000040   C   D   E   F   G   H   I   J   K   L   M   N   O   P   Q   R
0000060   S   T   U   V   W   X   Y   Z   [   ]   _       a   b   c   d
0000100   e   f   g   h   i   j   k   l   m   n   o   p   q   r   s   t
0000120   u   v   w   x   y   z   {   |   }       n   e   u   t   r   a
0000140   l       d   o   u   b   l   e       q   u   o   t   e   :    
0000160   "       c   l   o   s   i   n   g       s   i   n   g   l   e
0000200       q   u   o   t   e   :       ’  **  **       h   y   p   h
0000220   e   n   :       ‐  **  **       b   a   c   k   s   l   a   s
0000240   h   :       \       m   o   d   i   f   i   e   r       c   i
0000260   r   c   u   m   f   l   e   x   :       ˆ  **       o   p   e
0000300   n   i   n   g       s   i   n   g   l   e       q   u   o   t
0000320   e   :       ‘  **  **       m   o   d   i   f   i   e   r    
0000340   t   i   l   d   e   :       ˜  **       e   n   d       o   u
0000360   t   p   u   t  \n
0000365
```

### PR DESCRIPTION
**Pull request by tgrez**
Fixes #8202

I'm not sure if this fix is complete, because I couldn't reproduce the original behavior of uutils impl with GNU od, so I don't know in which situations the previous implementation was valid (I assume there is/was a reason for implementing it the way it was implemented).

Regardless of the above, this fixes the reported issue. It still lacks localization support, but it works correctly for `LC_ALL=C` as well as `LC_ALL=en_US.UTF-8`.

### CODE REVIEW

File: src/uu/od/src/prn_char.rs [hunk 1]
```diff
@@ -51,33 +50,13 @@ fn format_item_c(bytes: &[u8]) -> String {
     let b = bytes[0];
 
     if b & 0x80 == 0x00 {
+        // // ASCII byte (0xxxxxxx)
```
Comment (RenjiSann) [inline src/uu/od/src/prn_char.rs]:
```suggestion
        // ASCII byte (0xxxxxxx)
```

**Comment by RenjiSann** [comment]
> It still lacks localization support

I'm not familiar with `od`, do you have an example of its behavior changing depending on the locale ?

**Comment by tgrez** [comment]
> > It still lacks localization support
> 
> I'm not familiar with `od`, do you have an example of its behavior changing depending on the locale ?

I'd say the difference could come from different encodings, eg:

```
$ echo -n 'ą' | iconv -f UTF-8 -t ISO-8859-2 | od -t c
0000000 261
0000001
$ echo -n 'ą' | od -t c
0000000 304 205
0000002
```

**Comment by tgrez** [comment]
And also:

```
$ echo -n 'ą' | LC_ALL=pl_PL.ISO-8859-2 od -t c
0000000   ? 205
0000002
$ echo -n 'ą' | LC_ALL=C od -t c
0000000 304 205
0000002
```

**Comment by RenjiSann** [comment]
> I'd say the difference could come from different encodings, eg:
> 
> ```
> $ echo -n 'ą' | iconv -f UTF-8 -t ISO-8859-2 | od -t c
> 0000000 261
> 0000001
> $ echo -n 'ą' | od -t c
> 0000000 304 205
> 0000002
> ```

Unless I'm mistaken, in this example, it's the input given to `od` that changes, so I don't think it changes anything for `od` in itself.

**Comment by RenjiSann** [comment]
I think this fix is good though, I'll happily merge it once the typo is addressed ^^'

**Comment by tgrez** [comment]
> Unless I'm mistaken, in this example, it's the input given to od that changes, so I don't think it changes anything for od in itself.

Ah, yes, you're correct.

>  I'll happily merge it once the typo is addressed ^^'

Sorry for the confusion, which typo? :)

**Comment by RenjiSann** [comment]
> Sorry for the confusion, which typo? :)


C.f. my comment https://github.com/uutils/coreutils/pull/8268#discussion_r2167448784

**Comment by tgrez** [comment]
Happy to adjust anything, including typos.

Sorry, but I can't see this comment, after I click the link I'm redirected only to this PR, adding some screenshots:

Screenshot 2025-06-26 at 22 16 27
Screenshot 2025-06-26 at 22 16 59

**Comment by RenjiSann** [comment]
That's absolutely my bad, I didn't see this was still pending
Sorry, thanks for noticing :sweat_smile:

**Comment by tgrez** [comment]
> That's absolutely my bad, I didn't see this was still pending Sorry, thanks for noticing 😅

No worries! And thank you for the review!

Fixed the typo, rebased on the latest `main` and retested.

**Comment by RenjiSann** [comment]
Thank you for your contribution ! :rocket:
