### PR TITLE
ls: update chrono crate version and switch to `new_lenient` use

### LINKED ISSUE #7802: ls: Do not crash on unknown format specifier (e.g. `+%Y %0`)
Found this while doing some optimization of `ls`.

```
$ ls -l --time-style="+%Y %0"
total 61600
-rw-r--r-- 1 drinkcat drinkcat 50337176 2025 %0 all
...
$ cargo run ls -l --time-style="+%Y %0"
thread 'main' panicked at /home/drinkcat/nobackup/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/string.rs:2783:14:
a Display implementation returned an error unexpectedly: Error
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
total 61600
```

Looks like this is known in #7687 (@tertsdiepraam, @Qelxiros).

So IIUC we just need to wait for the next chrono release and switch to `new_lenient`: https://github.com/chronotope/chrono/pull/1693 .

### PR DESCRIPTION
**Pull request by emar-kar**
Chrono just released a new version of their crate, introducing more flexible way to parse unknown format specifiers.

Closes #7802

### CODE REVIEW

File: src/uu/ls/src/ls.rs [hunk 1]
```diff
@@ -297,8 +297,11 @@ impl TimeStyler {
             // So it's not yet implemented
             TimeStyle::Locale => StrftimeItems::new("%b %e  %Y").parse(),
             TimeStyle::Format(fmt) => {
-                // TODO (#7802): Replace with new_lenient
-                StrftimeItems::new(custom_tz_fmt::custom_time_format(fmt).as_str()).parse_to_owned()
+                // Box the fmt value to make it static.
+                StrftimeItems::new_lenient(Box::leak(
```
Comment (drinkcat) [inline src/uu/ls/src/ls.rs:301]: Why the `Box::leak` change?

Comment (emar-kar) [reply src/uu/ls/src/ls.rs]: Oh, my bad. Was too concentrated on `parse()`, missed that it can be done much simpler

**Comment by cakebaker** [comment]
Thanks!
