### PR TITLE
ls: follow symlinks for xattrs, fix #8216

### LINKED ISSUE #8216: ls: doesn't list acl "+" status for symlinks
The acl package fails to rebuild on Ubuntu with coreutils-uutils
https://launchpadlibrarian.net/798206888/buildlog_ubuntu-questing-amd64.acl_2.3.2-2_BUILDING.txt.gz

```
$ ls --version
ls 0.0.30

$ mkdir d
$ setfacl -m u:bin:rwx d
$ ln -s d l
$ ls -lLd l
drwxrwxr-x 2 user user 2 Jun 18 09:20 l
```

using the coreutils version of `ls` it gives `drwxrwxr-x+` (including the `+` of the acl, same as directly listing the directory)

### PR DESCRIPTION
**Pull request by sudhackar**
```
$ strace -e llistxattr,listxattr,getxattr ./target/debug/coreutils ls -lLd l
listxattr("l", 0x1, 0)                  = 24
listxattr("l", "system.posix_acl_access\0", 24) = 24
drwxrwxr-x+ 2 sudhackar sudhackar 4096 Jun 18 16:47 l
+++ exited with 0 +++
```
as compared to no `+`

### CODE REVIEW

**Comment by sudhackar** [comment]
This should fix #8216

File: tests/by-util/test_ls.rs [hunk 1]
```diff
@@ -5716,3 +5716,37 @@ fn test_unknown_format_specifier() {
...
+
+    let (at, mut ucmd) = at_and_ucmd!();
+    let dir_name = "dir";
+    let link_name = "link";
+    at.mkdir(dir_name);
+
+    // calling the command directly. xattr requires some dev packages to be installed
+    // and it adds a complex dependency just for a test
+    match Command::new("setfacl")
+        .args(["-d", "-m", "u:bin:rwx", dir_name])
```
Comment (cakebaker) [inline tests/by-util/test_ls.rs]: I think you have to use `at.plus_as_string`:
```suggestion
        .args(["-d", "-m", "u:bin:rwx", &at.plus_as_string(dir_name)])
```
At least on my system the `setfacl` command fails otherwise and the `Ok(_)` arm is executed.

**Comment by sudhackar** [comment]
I have fixed the patch for the GNU test - that passes now instead of SKIP

**Comment by sudhackar** [comment]
`tests/misc/tee` seems flaky locally - failed 1 out of 10 runs for me

**Comment by sylvestre** [comment]
we know, just ignore it :)

**Comment by sylvestre** [comment]
(but don't hesitate to have a look to fix it if you can reproduce it easily :)
