### PR TITLE
ls: Fix error message for ls file/missing-file

### LINKED ISSUE #11325: ls doesn't gracefully handle all errors
```
$ ./coreutils ls --version
ls (uutils coreutils) 0.7.0
$ ./coreutils ls /bin/ls/foo
ls: unknown io error: '/bin/ls/foo', 'Os { code: 20, kind: NotADirectory, message: "Not a directory" }'
```

### PR DESCRIPTION
**Pull request by oech3**
Closes #11325

### CODE REVIEW

File: tests/by-util/test_ls.rs [hunk 1]
```diff
@@ -57,6 +57,19 @@ const COMMA_ARGS: &[&str] = &["-m", "--format=commas", "--for=commas"];
 
 const COLUMN_ARGS: &[&str] = &["-C", "--format=columns", "--for=columns"];
 
+#[test]
+#[cfg(unix)]
+#[ignore = "Ubuntu has different message with Arch Linux :|"]
```
Comment (sylvestre) [inline tests/by-util/test_ls.rs]: why ignore ?

File: tests/by-util/test_ls.rs [hunk 2]
```diff
@@ -57,6 +57,19 @@ const COMMA_ARGS: &[&str] = &["-m", "--format=commas", "--for=commas"];
...
+fn test_directory_in_file() {
+    let scene = TestScenario::new(util_name!());
+
+    scene
+        .ucmd()
+        .arg("/sbin/init/dir")
```
Comment (danielzgtg) [inline tests/by-util/test_ls.rs]: This might not work on Android or macOS. Also see my PR https://github.com/uutils/coreutils/pull/11341 which has the same goal

**Review by danielzgtg — CHANGES_REQUESTED** [review]

File: tests/by-util/test_ls.rs (hunk 1 above)
Comment (oech3) [reply tests/by-util/test_ls.rs]: I changed to make file by myself which is robust more than depending on system files.

**Comment by oech3** [comment]
Is this OK to merge?

**Comment by cakebaker** [comment]
Thanks!
