### PR TITLE
A better handler for `./coreutils date -f aze`

### LINKED ISSUE #4480: date -f should better handle non existing files
```
$ ../target/debug/coreutils date -f aze
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/sylvestre/dev/debian/coreutils/src/uu/date/src/date.rs:228:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Found with:
https://github.com/uutils/coreutils/pull/4389
```
$ cargo +nightly fuzz run fuzz_date -- -max_total_time=60 -detect_leaks=0
```

### PR DESCRIPTION
**Pull request by AbhinavMir**
./target/release/coreutils date -f aze doesn't result in panic anymore, instead gives Error: File not found at path <PATH>. Fixes https://github.com/uutils/coreutils/issues/4480

### CODE REVIEW

**Comment by AbhinavMir** [comment]
`./target/release/coreutils date -f aze` doesn't result in panic anymore, instead gives `Error: File not found at path <PATH>`. Fixes https://github.com/uutils/coreutils/issues/4480

File: src/uu/date/src/date.rs [hunk 1]
```diff
@@ -223,10 +223,17 @@ pub fn uumain(args: impl uucore::Args) -> UResult<()> {
...
-                Box::new(iter)
+                match File::open(path) {
+                    Ok(file) => {
+                        let lines = BufReader::new(file).lines();
+                        let iter = lines.filter_map(Result::ok).map(parse_date);
+                        Box::new(iter)
+                    }
+                    Err(_) => {
+                        eprintln!("Error: File not found at path {:?}", path);
+                        Box::new(std::iter::empty())
```
Comment (sylvestre) [inline src/uu/date/src/date.rs:234]: could you please add a test to make sure we don't regress ?

File: src/uu/date/src/date.rs [hunk 2]
```diff
@@ -223,10 +223,17 @@ pub fn uumain(args: impl uucore::Args) -> UResult<()> {
...
-                let iter = lines.filter_map(Result::ok).map(parse_date);
-                Box::new(iter)
+                match File::open(path) {
+                    Ok(file) => {
+                        let lines = BufReader::new(file).lines();
+                        let iter = lines.filter_map(Result::ok).map(parse_date);
+                        Box::new(iter)
+                    }
+                    Err(_) => {
+                        eprintln!("Error: File not found at path {:?}", path);
```
Comment (sylvestre) [inline src/uu/date/src/date.rs:233]: please use the same wording as GNU
```
$ LANG=C date -f file-non-existing
date: file-non-existing: No such file or directory
```

Comment (sylvestre) [reply src/uu/date/src/date.rs:233]: Also, I think the syntax should be like:
https://github.com/uutils/coreutils/blob/a75cfd96555f44198b5410f65ec501f89cc6ef30/src/uu/sum/src/sum.rs#L88-L93

and the error code should be 1

File: src/uu/date/src/date.rs (hunk 1 above)
Comment (AbhinavMir) [reply src/uu/date/src/date.rs:234]: Sure! Where would the tests for this go?

File: src/uu/date/src/date.rs (hunk 2 above)
Comment (AbhinavMir) [reply src/uu/date/src/date.rs]: My bad! Fixed :)

File: src/uu/date/src/date.rs (hunk 1 above)
Comment (AbhinavMir) [reply src/uu/date/src/date.rs:234]: Sure, the tests should go in `test_date.rs` right? Can't see a test for file stuff on there.

Comment (sylvestre) [reply src/uu/date/src/date.rs:234]: yeah

File: src/uu/date/src/date.rs (hunk 2 above)
Comment (sylvestre) [reply src/uu/date/src/date.rs]: this isn't resolved ;) see my second comment (using USimpleError)

**Comment by sylvestre** [comment]
and please fix the clippy warning

File: src/uu/date/src/date.rs (hunk 2 above)
Comment (AbhinavMir) [reply src/uu/date/src/date.rs]: Aye! Sorry!

Would this work? I'm sorry for bugging you, just new to GNU contributions!

```rust
Err(err) => {
                        return Err(USimpleError::new(
                            1,
                            format!("failed to open {}: {}", path.display(), err),
                        ));
                    }
```

Comment (sylvestre) [reply src/uu/date/src/date.rs]: please try
but the error message isn't the one I asked you to update ;)

Comment (AbhinavMir) [reply src/uu/date/src/date.rs]: Error code now: `date: aze: No such file or directory`
Tests: All passed (added one for testing valid and then one for testing invalid files)
Clippy: No warnings

Comment (AbhinavMir) [reply src/uu/date/src/date.rs]: Error code now: `date: aze: No such file or directory`
Tests: All passed (added one for testing valid and then one for testing invalid files)
Clippy: No warnings

File: tests/by-util/test_date.rs [hunk 3]
```diff
@@ -198,6 +198,25 @@ fn test_date_set_valid_2() {
...
 
+#[test]
+fn test_date_for_invalid_file() {
+    let result = new_ucmd!()
+        .arg("--file")
+        .arg("invalid_file")
+        .fails();
+    result.no_stdout();
+    // should fail
+    assert!(result.stderr_str().starts_with("date: "));
```
Comment (sylvestre) [inline tests/by-util/test_date.rs:209]: please test the error message too here

File: src/uu/date/src/date.rs [hunk 4]
```diff
@@ -204,7 +204,7 @@ pub fn uumain(args: impl uucore::Args) -> UResult<()> {
         return set_system_datetime(date);
     } else {
         // Declare a file here because it needs to outlive the `dates` iterator.
-        let file: File;
+        let _file: File;
```
[the remark this answers is not in the document]
Comment (AbhinavMir) [reply src/uu/date/src/date.rs:207]: To keep clippy happy, seems it was only being used for the previous implementation, should I keep it as is?

File: src/uu/date/src/date.rs [hunk 5]
```diff
@@ -223,10 +223,19 @@ pub fn uumain(args: impl uucore::Args) -> UResult<()> {
                 Box::new(iter)
             }
             DateSource::File(ref path) => {
-                file = File::open(path).unwrap();
-                let lines = BufReader::new(file).lines();
-                let iter = lines.filter_map(Result::ok).map(parse_date);
-                Box::new(iter)
+                match File::open(path) {
```
Comment (sylvestre) [inline src/uu/date/src/date.rs:226]: rustfmt isn't happy :)

File: tests/by-util/test_date.rs [hunk 6]
```diff
@@ -198,6 +198,27 @@ fn test_date_set_valid_2() {
     }
 }
 
+#[test]
```
Comment (sylvestre) [inline tests/by-util/test_date.rs:201]: rustfmt isn't happy either

File: src/uu/date/src/date.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (tertsdiepraam) [reply src/uu/date/src/date.rs:207]: Surprisingly, it's even unnecessary in the old code :) Seems like the original implementor just assumed that it was necessary even though the `BufReader::new` and all the other functions take owned values to `file` isn't dropped anyway. So yeah, let's remove it.

[the remark this answers is not in the document]
Comment (AbhinavMir) [reply src/uu/date/src/date.rs:207]: Ah, great! Thx!

**Comment by AbhinavMir** [comment]
Fixed fmt warnings. Anything else I missed?

File: src/uu/date/src/date.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (sylvestre) [reply src/uu/date/src/date.rs:207]: why you didn't remove it ? :)

[the remark this answers is not in the document]
Comment (AbhinavMir) [reply src/uu/date/src/date.rs:207]: Oh, no particular reason. Let me remove it then.

**Comment by sylvestre** [comment]
thanks :)
