### PR TITLE
df: fix "Size" column header

### LINKED ISSUE #3193: df: incorrect size column header
For block sizes that are not divisible by 1024, the column header of the "size" column in the table produced by `df` does not match GNU. (For block sizes divisible by 1024, see pull request #3191.) For example,

GNU df:
```
$ df --block-size=1234 | head -n1
Filesystem                1.3kB-blocks     Used Available Use% Mounted on
```

uutils df:
```
$ ./target/debug/df --block-size=1234 | head -n1
Filesystem          1k-blocks         Used    Available  Use% Mounted on       
```
(For this issue, let's ignore the differences in whitespace.) GNU df produces "1.3kB-blocks", uutils df produces "1k-blocks".

The output format seems similar to that of numfmt:
```
$ numfmt --to=si 1234
1.3K
```

### PR DESCRIPTION
**Pull request by cakebaker**
Implement "Size" column header for block sizes that are not multiples of 1024.

Fixes #3193.

### CODE REVIEW

File: src/uu/df/src/blocks.rs [hunk 1]
```diff
@@ -57,6 +73,37 @@ fn to_magnitude_and_suffix_1024(n: u128) -> Result<String, ()> {
     Err(())
 }
 
+/// Convert a number, except multiples of 1024, into a string like "12kB" or "34MB".
+///
+/// Powers of 1000 become "1kB", "1MB", "1GB", etc.
+///
+/// The returned string has a maximum length of 5 chars, for example: "1.1kB", "999kB", "1MB".
+fn to_magnitude_and_suffix_not_powers_of_1024(n: u128) -> Result<String, ()> {
```
Comment (jfinkels) [inline src/uu/df/src/blocks.rs:81]: Seems like there is never an `Err` returned, so does this need to return a `Result`? Maybe there wants to be an `Err` if `n` is larger than 10^27, I'm not sure.

File: src/uu/df/src/blocks.rs [hunk 2]
```diff
@@ -66,8 +113,7 @@ fn to_magnitude_and_suffix(n: u128) -> Result<String, ()> {
     if n % 1024 == 0 {
         to_magnitude_and_suffix_1024(n)
     } else {
-        // TODO Implement this, probably using code from `numfmt`.
```
Comment (jfinkels) [inline src/uu/df/src/blocks.rs:69]: I'm curious if you looked into the code for `numfmt`? I have not looked in detail, so I don't know if there's anything there to refactor.

**Review by jfinkels — APPROVED** [review]
Cool!

File: src/uu/df/src/blocks.rs (hunk 2 above)
Comment (cakebaker) [reply src/uu/df/src/blocks.rs:69]: I looked into the code of `numfmt` and found it difficult to extract some commonalities because `df` uses different SI-suffixes than `numfmt`.

File: src/uu/df/src/blocks.rs (hunk 1 above)
Comment (cakebaker) [reply src/uu/df/src/blocks.rs:81]: Yes, you are right, technically no `Result` is needed. I used it for consistency reasons because `to_magnitude_and_suffix()` returns a `Result` and the following looks cleaner
```rust
fn to_magnitude_and_suffix(n: u128) -> Result<String, ()> {
   if n % 1024 == 0 {    
       to_magnitude_and_suffix_1024(n)
   } else {
       to_magnitude_and_suffix_not_powers_of_1024(n)
   }
}
```
than
```rust
fn to_magnitude_and_suffix(n: u128) -> Result<String, ()> {
   if n % 1024 == 0 {    
       to_magnitude_and_suffix_1024(n)
   } else {
       Ok(to_magnitude_and_suffix_not_powers_of_1024(n))
   }
}
```
I don't think an `Err` is necessary because there is already a "block size too large" error when parsing the provided argument.

**Review by jfinkels — APPROVED** [review]
@sylvestre seems good to me
