### PR TITLE
tail: fix panic on write error in bounded_tail

### LINKED ISSUE #11809: tail huge-file >/dev/full panics with unwrap()
```
$ truncate -s 1GB /tmp/huge
$ tail /tmp/huge > /dev/full

thread 'main' (3191) panicked at src/uu/tail/src/tail.rs:594:37:
called `Result::unwrap()` on an `Err` value: Os { code: 28, kind: StorageFull, message: "No space left on device" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by rossilor95**
Fixes #11809

`tail huge-file > /dev/full` panicked with `unwrap()` at `tail.rs:594` because
`bounded_tail` and `print_target_section` did not propagate write errors.

- Change `print_target_section` to return `UResult<()>`, replacing `.unwrap()`
  with `?`
- Change `bounded_tail` to return `UResult<()>` and propagate the error to its
  caller
- Add `test_failed_write_is_reported_on_seekable_input` (Linux-only, uses
  `/dev/full` with a large seekable file to exercise the `bounded_tail` path)

### CODE REVIEW

File: tests/by-util/test_tail.rs [hunk 1]
```diff
@@ -5086,6 +5086,21 @@ fn test_failed_write_is_reported() {
         .stderr_is("tail: No space left on device\n");
 }
 
+#[cfg(target_os = "linux")]
+#[test]
+fn test_failed_write_is_reported_on_seekable_input() {
+    let ts = TestScenario::new("tail");
+    let at = &ts.fixtures;
+
+    at.write("bigfile", &"x\n".repeat(100_000));
```
Comment (cakebaker) [inline tests/by-util/test_tail.rs]: I don't know if it's machine-specific, but on my machine I have to use a much higher value (`1_100_000`) to make this test fail when running it without your changes to `tail.rs`.

Comment (rossilor95) [reply tests/by-util/test_tail.rs]: Hey @cakebaker, thank you for your review! I think it's system-specific, but I'd like to use a value high enough to exceed any realistic block size. I bumped it to `1_100_000`.

**Comment by cakebaker** [comment]
Thanks for your PR!
