### PR TITLE
cp: fix update prompting

### LINKED ISSUE #7660: cp: -i --update=none prompts but shouldn't
Environment: Ubuntu 24.04, uutils `main` branch (git commit 3971bb3b0cdc83d5554f72f88106c1f9c43c2461), GNU coreutils v9.6.38-2b088-modified

Steps to reproduce:
```
echo f > f
echo g > g
cp -i --update=none f g
```

What happens now: uutils `cp` prompts the user with
```
cp: overwrite 'g'?
```
even though the file is not copied regardless of the answer.

What I expected to happen: GNU `cp` does not print any prompt and no changes are made to the files.

Notes: this is causing a failure in GNU test file `tests/cp/cp-i.sh`.

### PR DESCRIPTION
**Pull request by hz2**
- added logic to check in `copy_source` after resolving src and dst to compare
  timestamps
   - if dst is newer, we skip the operation and prevent prompting the user
   - else, proceed to copy
 
Fixes #7660

### CODE REVIEW

**Comment by cakebaker** [comment]
Can you please run the tests? Your solution currently breaks two tests.

**Comment by hz2** [comment]
sorry about that, not sure how i missed that.

**Comment by hz2** [comment]
Apologizes for the failed checks still, could I get some help/clarification on the errors I'm seeing?

- https://github.com/uutils/coreutils/blob/main/tests/by-util/test_install.rs?plain=#L644
- https://github.com/uutils/coreutils/blob/main/tests/by-util/test_tail.rs?plain=#L1993

Are these failed tests actionable for me? If so, are there starting steps I should take?

The patience and feedback is much appreciated!

**Comment by cakebaker** [comment]
@hz2 no, those failing tests are unrelated to your PR.

File: tests/by-util/test_cp.rs [hunk 1]
```diff
@@ -6172,3 +6172,21 @@ fn test_cp_update_older_interactive_prompt_no() {
...
+    let old_file = "old";
+    let new_file = "new";
+
+    at.write(old_file, "old content");
+    at.write(new_file, "new content");
+
+    ucmd.args(&["-i", "--update=none", new_file, old_file])
+        .succeeds()
+        .no_stderr()
+        .no_stdout();
```
Comment (cakebaker) [inline tests/by-util/test_cp.rs:6188]: A detail: you can simplify it to:
```suggestion
        .no_output();
```

**Comment by hz2** [comment]
@cakebaker much cleaner, thank you!

**Comment by cakebaker** [comment]
Thanks for your PR :)
