### PR TITLE
tr: fix octal interpretation of repeat count string

### LINKED ISSUE #3168: `tr`: Incorrect parsing of the repeat count in `[c*n]`
In `tr`, character repetition (`[c*n]`) is always being parsed as octal.  But as mentioned in [GNU docs](https://www.gnu.org/software/coreutils/manual/html_node/Character-sets.html) for 'Repeated characters':
> If n begins with ‘0’, it is interpreted in octal, otherwise in decimal.

GNU tr:
```
$ /usr/bin/tr '[a*9]' 'b' <<< 'ab'
bb
```

uutils tr:
```
$ ./target/debug/tr '[a*9]' 'b' <<< 'ab'
./target/debug/tr: invalid repeat count '9' in [c*n] construct
```

### PR DESCRIPTION
**Pull request by DevSabb**
Closes #3168 

Fix repeat count processing of `tr` to interpret as octal only if prefixed with `0`.

### CODE REVIEW

File: src/uu/tr/src/operation.rs [hunk 1]
```diff
@@ -277,13 +278,19 @@ impl Sequence {
...
             tag("]"),
         )(input)
-        .map(|(l, (c, str))| {
+        .map(|(l, (c, cnt_str))| {
+            let result: Result<usize, ParseIntError>;
+            if cnt_str.chars().next().unwrap() == '0' {
+                result = usize::from_str_radix(cnt_str, 8);
+            } else {
+                result = usize::from_str_radix(cnt_str, 10);
+            };
```
Comment (tertsdiepraam) [inline src/uu/tr/src/operation.rs:287]:
```suggestion
            let result = cnt_str.starts_with('0') {
                usize::from_str_radix(cnt_str, 8);
            } else {
                usize::from_str_radix(cnt_str, 10);
            };
```

**Review by tertsdiepraam — COMMENTED** [review]
Clippy and spelling check found some issues, but looks like it's going in the right direction! Thanks!

File: src/uu/tr/src/operation.rs (hunk 1 above)
Comment (tertsdiepraam) [reply src/uu/tr/src/operation.rs]: Thanks! You can add those "words" to the `// spell-checker:ignore` comments in that file.

Comment (DevSabb) [reply src/uu/tr/src/operation.rs]: This PR has way too many commits than I wanted. Will you be able to squash them while merging or should I try to squash them and send another PR?

Also, please review and let me know if this looks okay.

**Comment by tertsdiepraam** [comment]
All good! Thanks!
