### PR TITLE
expr: Refactor AST evaluation to avoid stack overflow

### LINKED ISSUE #7338: expr: Segmentation fault on big inputs
This behaviour happens when the list of inputs is quite large (it starts happening on my machine around N=2850, but it's not absolute.

```
$ export N=3000
$ cargo run -p uu_expr -- $(seq -s" + " $N)
[1]    2144088 segmentation fault  cargo run -p uu_expr -- $(seq -s" + " $N)
```

### PR DESCRIPTION
**Pull request by LouisDISPA**
## Overview

This pull request addresses a stack overflow issue in the `expr` utility when handling deeply nested expressions.

Fixes #7338

## Changes

- Replaced recursive tree traversal with stack-based approach
- Add identifiers for AST nodes
- Use a BTreeMap with node IDs for the result stack

## Testing

The implementation includes a new test case that verifies the ability to handle large expressions that would previously cause stack overflow.

## Notes

A simpler solution would be to use the [decurse](https://crates.io/crates/decurse) crate.

### CODE REVIEW

**Comment by sylvestre** [comment]
Windows isn't happy :)
Did you look at the performance impact of this change? Thanks

File: tests/by-util/test_expr.rs [hunk 1]
```diff
@@ -364,3 +364,17 @@ fn test_eager_evaluation() {
         .fails()
         .stderr_contains("division by zero");
 }
+
+#[test]
+fn test_long_input() {
+    const MAX_NUMBER: usize = 40000;
```
Comment (RenjiSann) [inline tests/by-util/test_expr.rs:370]:
```suggestion
    // Giving expr an arbitrary long expression should succeed rather than end with a segfault due to a stack overflow.
    const MAX_NUMBER: usize = 40000;
```

I would add this comment, so people reading the code know why it exists.

Comment (LouisDISPA) [reply tests/by-util/test_expr.rs:370]: Ah yes good point I'll add this.

**Comment by LouisDISPA** [comment]
> Windows isn't happy :) Did you look at the performance impact of this change? Thanks

The algorithm is just wrong sorry, I wanted to avoid adding an id on the nodes but it doesn't work.
For the windows issue I suspect it's related to the [8191 characters limit](https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/command-line-string-limitation#more-information).

I'll push fixes and update the PR description.

**Comment by LouisDISPA** [comment]
I did some quick benchmarking by simulating the long input here are the results:
```sh
bash-3.2$ export N=10000
bash-3.2$ echo $(seq -s" + " $N)1 > tmp.txt
bash-3.2$ hyperfine -n expr "expr $(cat tmp.txt)" -n main_uu_expr "./main_uu_expr $(cat tmp.txt)" -n new_uu_expr "./new_uu_expr $(cat tmp.txt)" -N --warmup 300 -i
```

| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `expr` | 3.3 ± 0.6 | 2.8 | 13.8 | 1.00 |
| `main_uu_expr` | 5.7 ± 0.4 | 5.1 | 7.4 | 1.73 ± 0.31 |
| `new_uu_expr` | 5.6 ± 0.3 | 5.1 | 7.3 | 1.70 ± 0.31 |

And with the input that the current implementation on the main branch can't handle:

```sh
bash-3.2$ export N=30000
bash-3.2$ echo $(seq -s" + " $N)1 > tmp.txt
bash-3.2$ hyperfine -n expr "expr $(cat tmp.txt)" -n main_uu_expr "./main_uu_expr $(cat tmp.txt)" -n new_uu_expr "./new_uu_expr $(cat tmp.txt)" -N --warmup 300 -i
```

| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `expr` | 7.1 ± 0.4 | 6.6 | 11.0 | 1.00 |
| `main_uu_expr (ignoring error)` | 10.1 ± 0.4 | 9.6 | 11.9 | 1.43 ± 0.10 |
| `new_uu_expr` | 14.3 ± 0.5 | 13.4 | 16.1 | 2.03 ± 0.14 |

**Comment by RenjiSann** [comment]
What does the " (ignoring error)" mean in your second table ?

**Comment by LouisDISPA** [comment]
> What does the " (ignoring error)" mean in your second table ?

It's relate to the `-i` option of hyperfine: 
```
  -i, --ignore-failure
          Ignore non-zero exit codes of the benchmarked programs
```

The command runs but the exit code is a failure because of the stack overflow.
I find interesting to see the benchmark of it, it should be mostly the parsing time with a bit of function calls until the overflow.

**Comment by RenjiSann** [comment]
It sounds strange to me, because when I tried, the segfault happened instantly, not after 10 seconds :thinking:

File: src/uu/expr/src/syntax_tree.rs [hunk 2]
```diff
@@ -5,6 +5,11 @@
 
 // spell-checker:ignore (ToDO) ints paren prec multibytes
 
+use std::{
+    collections::BTreeMap,
+    sync::atomic::{AtomicU16, Ordering},
```
Comment (RenjiSann) [inline src/uu/expr/src/syntax_tree.rs:10]: Is there a specific reason for using atomics here ?
I'm not very familiar with it, I thought it was only useful in threaded environments.

**Comment by RenjiSann** [comment]
> Yes the benchmarks are in milliseconds
Duh, didn't see it :sob: 

Anyway, this Pr is about fixing a SEGFAULT, not improving the performance, so it's OK if you manage to keep the same performance without immproving it.

File: src/uu/expr/src/syntax_tree.rs (hunk 2 above)
Comment (LouisDISPA) [reply src/uu/expr/src/syntax_tree.rs:10]: There is no way for the compiler to assert that the function `fn get_next_id() -> u16` isn't used by another thread. The simplest solution is to use an atomic value.

Another solution would be to use a thread local variable but it would be a bit more verbose. With thread locals every thread has a unique counter and it would break the code if the parser becomes multi-threaded.

Comment (RenjiSann) [reply src/uu/expr/src/syntax_tree.rs:10]: > if the parser becomes multi-threaded

I don't think this is likely to happen.
After all, this is "just" a simple CLI arithmetic expression evaluator.
Making it multi-threaded seems a bit overkill to me, like if you really need that level of performance, use a dedicated tool, rather than a command from the coreutils.

In the single-threaded case, using an atomic add is just gonna make the process a tiny bit slower for no real reason.

**Review by RenjiSann — CHANGES_REQUESTED** [review]
Nothing to say on the logic part.
I'd rather remove the use of atomics though, as the tool is not likely to get multi-threading support.

Apart from that, I think you could stash your commits in only 2 (changes to the code, and to the test), so we keep the main branch clean from implementation details.

Good job !

File: src/uu/expr/src/syntax_tree.rs (hunk 2 above)
Comment (LouisDISPA) [reply src/uu/expr/src/syntax_tree.rs]: Yes make sense, I moved the implementation to use thread locals.

**Comment by LouisDISPA** [comment]
> Nothing to say on the logic part. I'd rather remove the use of atomics though, as the tool is not likely to get multi-threading support.
> 
> Apart from that, I think you could stash your commits in only 2 (changes to the code, and to the test), so we keep the main branch clean from implementation details.
> 
> Good job !

- Moved the ID generation to thread locals
- Squashed the PR into 2 commits (test, impl)

**Review by RenjiSann — APPROVED** [review]
