### PR TITLE
date: fix invalid argument error for RFC 3339

### LINKED ISSUE #4530: `date --rfc-3339 foo` error should be managed properly
Found with the fuzzer introduced in https://github.com/uutils/coreutils/pull/4389

```
$ ./target/debug/coreutils date --rfc-3339 foo      
thread 'main' panicked at 'Invalid format: foo', src/uu/date/src/date.rs:136:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

with GNU:
```
date --rfc-3339 foo
date: invalid argument 'foo' for '--rfc-3339'
Valid arguments are:
  - 'date'
  - 'seconds'
  - 'ns'
Try 'date --help' for more information.
```

Similar too https://github.com/uutils/coreutils/pull/4499 . cc @shanmukhateja if you want to do it here too

### PR DESCRIPTION
**Pull request by shanmukhateja**
Fixes #4530 

@sylvestre

### CODE REVIEW

File: tests/by-util/test_date.rs [hunk 1]
```diff
@@ -43,6 +43,14 @@ fn test_date_rfc_3339() {
     }
 }
 
+
```
Comment (sylvestre) [inline tests/by-util/test_date.rs:46]: please run runfmt

Comment (shanmukhateja) [reply tests/by-util/test_date.rs]: [This](https://github.com/uutils/coreutils/pull/4535/commits/1eb9299c780fc35d9d1fdcaa0c233abe75f0899a) commit should fix it.
