### PR TITLE
fix(numfmt): format output on error messages

### LINKED ISSUE #11116: numfmt does not load numfmt-error-invalid-input from *.ftl
```
> cat /bin/numfmt | numfmt
numfmt: numfmt-error-invalid-input
```

### PR DESCRIPTION
**Pull request by FidelSch**
fixes #11116

### CODE REVIEW

File: src/uu/numfmt/src/format.rs [hunk 1]
```diff
@@ -452,6 +452,20 @@ fn format_string(
     ))
 }
 
+/// Encodes a byte slice as a string, representing non-UTF-8 bytes as octal escapes.
+/// Used to safely format invalid input in error messages.
+pub(crate) fn escape_line(line: &[u8]) -> String {
+    line.iter()
+        .map(|&b| {
+            if b.is_ascii_graphic() || b.is_ascii_whitespace() {
```
Comment (cakebaker) [inline src/uu/numfmt/src/format.rs]: It's unfortunately more complex because `line` also can contain valid UTF-8 multi-byte characters:
```
$ printf "10\n\xFF🦀" | cargo run -q numfmt
10
numfmt: invalid number: '\377\360\237\246\200'
$ printf "10\n\xFF🦀" | numfmt
10
numfmt: invalid number: ‘\377🦀’
```
I don't know if you want to address it in this PR, otherwise a TODO would be helpful.

Comment (FidelSch) [reply src/uu/numfmt/src/format.rs]: ouch, will give it a shot

File: src/uu/numfmt/src/format.rs [hunk 2]
```diff
@@ -452,6 +452,26 @@ fn format_string(
     ))
 }
 
+/// Encodes a byte slice as a string, representing non-UTF-8 bytes and non-printable ASCII
+/// bytes as octal escapes. Valid UTF-8 multi-byte characters pass through unchanged.
+/// Used to safely format invalid input in error messages.
+pub(crate) fn escape_line(line: &[u8]) -> String {
+    let mut result = String::new();
+    for chunk in line.utf8_chunks() {
```
Comment (cakebaker) [inline src/uu/numfmt/src/format.rs:460]: Nice, I didn't know there is such a function in the std :)

**Comment by cakebaker** [comment]
Thanks!
