### PR TITLE
uucore: tr, nice -n . 2>/dev/full does not abort

### LINKED ISSUE #10621: tr 2>/dev/full has wrong exit code (using UUsageError)

### LINKED ISSUE #10747: nice -n . 2>/dev/full SIGABRT
I have no idea how to fix it. Errors are abstracted.

### PR DESCRIPTION
**Pull request by oech3**
Closes #10747 . Removes Try `--help` message which matches with gnu 9.10.
[Edit] Closes #10621

### CODE REVIEW

File: src/uu/nice/src/nice.rs [hunk 1]
```diff
@@ -121,10 +121,13 @@ pub fn uumain(args: impl uucore::Args) -> UResult<()> {
 
     let adjustment = if let Some(nstr) = matches.get_one::<String>(options::ADJUSTMENT) {
         if !matches.contains_id(options::COMMAND) {
-            return Err(UUsageError::new(
-                125,
-                translate!("nice-error-command-required-with-adjustment"),
-            ));
+            let _ = writeln!(
```
Comment (ChrisDryden) [inline src/uu/nice/src/nice.rs]: I'm a bit suspicious that this is the right place to do it? 

I'm curious if you think that it would be possible to fix this in the procs lib at:

src/uucore_procs/src/lib.rs:59

Comment (oech3) [reply src/uu/nice/src/nice.rs]: looks more generic (if possible).

File: src/uu/nice/src/nice.rs
Comment (oech3) [inline src/uu/nice/src/nice.rs:154]: We should cleanup this too.

File: src/uu/nice/src/nice.rs (hunk 1 above)
Comment (sylvestre) [reply src/uu/nice/src/nice.rs]: i think Err(UUsageError::new( 
was better in term of readability
can we update it instead ?

Comment (oech3) [reply src/uu/nice/src/nice.rs]: done

**Comment by oech3** [comment]
what happened

**Comment by oech3** [comment]
is this ok to merge?

**Comment by oech3** [comment]
I'm not sore should I make this Green. But I try.

**Comment by oech3** [comment]
is this ok to merge?
