### PR TITLE
rm: add verbose output and trim multiple slashes

### LINKED ISSUE #1829: rm: should match GNU's output if multiple slashes in argument
rm fails this test: https://github.com/coreutils/coreutils/blob/master/tests/rm/v-slash.sh
The directory and the file are removed, but the stdout doesn't match GNU's stdout.

If ported to rust:
```rust
#[test]
fn test_rm_verbose_slash() {
    let (at, mut ucmd) = at_and_ucmd!();
    let dir = "test_rm_verbose_slash_directory";
    let file_a = &format!("{}/test_rm_verbose_slash_file_a", dir);

    at.mkdir(dir);
    at.touch(file_a);

    ucmd.arg("-r")
        .arg("-f")
        .arg("-v")
        .arg(&format!("{}///", dir))
        .succeeds()
        .stdout_only(format!(
            "removed '{}'\nremoved directory '{}'\n",
            file_a, dir
        ));

    assert!(!at.dir_exists(dir));
    assert!(!at.file_exists(file_a));
}
```
the output is:
```bash
'test_rm::test_rm_verbose_slash' panicked at 'assertion failed: `(left == right)`
  left: `"removed directory \'test_rm_verbose_slash_directory///\'\n"`,
 right: `"removed \'test_rm_verbose_slash_directory/test_rm_verbose_slash_file_a\'\nremoved directory \'test_rm_verbose_slash_directory\'\n"`'
```

Related #1768

### PR DESCRIPTION
**Pull request by reggaemuffin**
Fixes #1829

Uses the `normalize_path` used in cargo to strip duplicate slashes
With a link to a std rfc https://github.com/rust-lang/rfcs/issues/2208

This fixes #1829

This also touches #1768 
but does not attempt to fully solve it, as I rather have that be a separate pr

The fix to enable any output was to use the recursive version whenever we want to be verbose. https://github.com/uutils/coreutils/issues/1768#issuecomment-796162092 suggests to anyway run `remove_dir_all` after we do the recursive delete but I feel more tests are needed

I also updated the test proposed in #1829 to account for windows having a different normalized path using `\\`

### CODE REVIEW

File: tests/by-util/test_rm.rs [hunk 1]
```diff
@@ -263,3 +263,33 @@ fn test_rm_no_operand() {
...
         .stderr_is("rm: error: missing an argument\nrm: error: for help, try 'rm --help'\n");
 }
+
+#[test]
+fn test_rm_verbose_slash() {
+    let (at, mut ucmd) = at_and_ucmd!();
+    let dir = "test_rm_verbose_slash_directory";
+    let file_a = &format!("{}/test_rm_verbose_slash_file_a", dir);
+
+    at.mkdir(dir);
```
Comment (sylvestre) [inline tests/by-util/test_rm.rs:273]: please run rustfmt

Comment (reggaemuffin) [reply tests/by-util/test_rm.rs:273]: I thought I did run it :o maybe the change got lost bisecting unrelated formatting, will run it again :)

Comment (reggaemuffin) [reply tests/by-util/test_rm.rs:273]: Figured it out: `cargo fmt` does not run the formatter on tests so I had to manually run `rustfmt` on the specific file

https://github.com/rust-lang/rustfmt/issues/803

Should be fixed now

File: tests/by-util/test_rm.rs [hunk 2]
```diff
@@ -263,3 +263,29 @@ fn test_rm_no_operand() {
...
+    at.touch(file_a);
+
+    let separator = if cfg!(windows) { "\\" } else { "/" };
```
Comment (jhscheer) [inline tests/by-util/test_rm.rs:276]: consider using:
https://doc.rust-lang.org/std/path/constant.MAIN_SEPARATOR.html

Comment (reggaemuffin) [reply tests/by-util/test_rm.rs]: great point! fixed

File: src/uu/rm/src/rm.rs [hunk 3]
```diff
@@ -370,6 +370,45 @@ fn prompt_file(path: &Path, is_dir: bool) -> bool {
     }
 }
 
+// copied from https://github.com/rust-lang/cargo/blob/2e4cfc2b7d43328b207879228a2ca7d427d188bb/src/cargo/util/paths.rs#L65-L90
+// both projects are MIT https://github.com/rust-lang/cargo/blob/master/LICENSE-MIT
+// for std impl progress see rfc https://github.com/rust-lang/rfcs/issues/2208
+// replace this once that lands
+pub fn normalize_path(path: &Path) -> PathBuf {
```
Comment (reggaemuffin) [inline src/uu/rm/src/rm.rs:377]: Since some of the lines of this function were not covered by the test case, I see three options:

1. Ignore the checks (probably not desired)
2. Add extra tests to `rm`
3. Promote this into a core util function and write unit tests for it for coverage
4. do both 2. and 3.

Let me know what you think

Comment (sylvestre) [reply src/uu/rm/src/rm.rs:377]: please, do 3 :)

Comment (reggaemuffin) [reply src/uu/rm/src/rm.rs:377]: Hey @sylvestre,

I am trying to write unit tests for the now extracted function and noticed that there is no framework to actually test those

I started laying the foundation for that but came to a blocker where the tests I write can't actually detect if a dependency has a feature enabled, which is important as I can only run those tests if `uucore/fs` is enabled

My options now are:

1. putting it into core and skipping unit tests
2. feature gate the tests for the `rm` feature (means it can get out of sync)
3. You might have an idea how to better test `uucore`

**Comment by reggaemuffin** [comment]
Should be ready to review now :)

- extracted utility function into `uucore`
- enabled tests for `uucore` with full coverage of diff

File: src/uucore/src/lib/features/fs.rs [hunk 4]
```diff
@@ -266,3 +297,61 @@ pub fn display_permissions_unix(mode: u32) -> String {
...
+        NormalizePathTestCase {
+            path: "\\networkshare/a//foo//./bar",
+            test: "\\networkshare/a/foo/bar",
+        },
+    ];
+
+    #[test]
+    fn test_normalize_path() {
+        for test in NORMALIZE_PATH_TESTS.iter() {
+            let path = Path::new(test.path);
```
Comment (sylvestre) [inline src/uucore/src/lib/features/fs.rs:349]: please run rustfmt :)

Comment (reggaemuffin) [reply src/uucore/src/lib/features/fs.rs:349]: done :)

**Comment by reggaemuffin** [comment]
@sylvestre let me know if anything is still missing :)

File: .github/workflows/CICD.yml [hunk 5]
```diff
@@ -150,7 +150,7 @@ jobs:
       uses: actions-rs/cargo@v1
       with:
         command: test
-        args: --features "feat_os_unix"
+        args: --features "feat_os_unix" -p uucore -p coreutils
```
Comment (sylvestre) [inline .github/workflows/CICD.yml:153]: please remove this
```suggestion
        args: --features "feat_os_unix"
```

please create a separate PR for this with the rational

File: .github/workflows/CICD.yml [hunk 6]
```diff
@@ -536,6 +536,17 @@ jobs:
         CARGO_UTILITY_LIST_OPTIONS="$(for u in ${UTILITY_LIST}; do echo "-puu_${u}"; done;)"
         echo set-output name=UTILITY_LIST::${UTILITY_LIST}
         echo ::set-output name=CARGO_UTILITY_LIST_OPTIONS::${CARGO_UTILITY_LIST_OPTIONS}
+    - name: Test uucore
```
Comment (sylvestre) [inline .github/workflows/CICD.yml:539]: Ditto

File: README.md [hunk 7]
```diff
@@ -226,6 +226,11 @@ If you would prefer to test a select few utilities:
 $ cargo test --features "chmod mv tail" --no-default-features
 ```
```
Comment (sylvestre) [inline README.md:228]: same

File: src/uu/rm/Cargo.toml [hunk 8]
```diff
@@ -18,9 +18,11 @@ path = "src/rm.rs"
...
 remove_dir_all = "0.5.1"
-uucore = { version=">=0.0.8", package="uucore", path="../../uucore" }
+
+uucore = { version=">=0.0.8", package="uucore", path="../../uucore", features=["fs"] }
 uucore_procs = { version=">=0.0.5", package="uucore_procs", path="../../uucore_procs" }
 
 [[bin]]
 name = "rm"
 path = "src/main.rs"
+
```
Comment (sylvestre) [inline src/uu/rm/Cargo.toml:28]: please remove this change

File: .github/workflows/CICD.yml (hunk 5 above)
Comment (reggaemuffin) [reply .github/workflows/CICD.yml:153]: created #2030 which now blocks this pr :)
