### PR TITLE
shuf: try Vec first and fallback to HashMap if it cause OOM

### LINKED ISSUE #11105: shuf_input_range benchmark is flakey
https://github.com/uutils/coreutils/pull/11068#issuecomment-3958544199 Maybe. caused by https://github.com/uutils/coreutils/commit/74b89246825085b95aad5e5151ffab5770c9907d . We cannot simply revert it for performance.

### LINKED ISSUE #11167: shuf -i 1-100000000000 -n 256 cause memory allocation failure
```
$ target/release/shuf -i 1-100000000000 -n 256
memory allocation of 799999998208 bytes failed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Maybe, we should optimize
https://github.com/uutils/coreutils/blob/ba94c6960d4246ab1dcd092f43e2e51d9eaa9080/src/uu/shuf/src/nonrepeating_iterator.rs#L53

for -n .

### PR DESCRIPTION
**Pull request by oech3**
Closes #11167 Closes #11105 ?
Closes #11168 (this is cleaner approach). Perf is same (bit flakey, but not 5%).

### CODE REVIEW

File: src/uu/shuf/src/nonrepeating_iterator.rs [hunk 1]
```diff
@@ -49,13 +49,25 @@ enum Values {
...
-        let values = Values::Sparse(
-            range,
-            FxHashMap::with_capacity_and_hasher(capacity, rustc_hash::FxBuildHasher),
-        );
+    pub(crate) fn new(
+        range: RangeInclusive<u64>,
+        rng: &'a mut WrappedRng,
+        head_count: Option<usize>,
+    ) -> Self {
+        const TOO_LARGE_VEC_SIZE: usize = 16_777_216;
```
Comment (sylvestre) [inline src/uu/shuf/src/nonrepeating_iterator.rs:58]: please add a comment explaining the why
