### PR TITLE
fix(numfmt): Read lines only up to null byte (as GNU does)

### LINKED ISSUE #11109: echo -e "3\0" | numfmt fails
```
$ echo -e "3\0" | gnu9.10/numfmt
3
$ echo -e "3\0" | uu-numfmt
numfmt: invalid suffix in input: $'3\x00'
```

### PR DESCRIPTION
**Pull request by FidelSch**
Fixes #11109

In cases such as "1000\x002000\n3000" `numfmt` outputs "1000\n3000\n", strongly suggesting it reads input until encountering a null byte, which makes sense in a C context.

Should now mimic this behavior.

Added integration tests for this as well

### CODE REVIEW

File: tests/by-util/test_numfmt.rs [hunk 1]
```diff
@@ -1249,3 +1249,24 @@ fn test_empty_delimiter_whitespace_rejection() {
         .fails_with_code(2)
         .stderr_contains("invalid suffix in input");
 }
+
+#[test]
+fn test_null_byte_input() {
+    new_ucmd!()
+        .pipe_in("1000\x00")
+        .succeeds()
+        .stdout_is("1000\n");
```
Comment (cakebaker) [inline tests/by-util/test_numfmt.rs:1258]: GNU `numfmt` doesn't add a newline in such a case:
```bash
$ printf "1000\x00" | numfmt | cat -A
1000
$ printf "1000\x00" | cargo run -q numfmt | cat -A
1000$
```

```suggestion
        .stdout_is("1000");
```

File: tests/by-util/test_numfmt.rs [hunk 2]
```diff
@@ -1249,3 +1249,24 @@ fn test_empty_delimiter_whitespace_rejection() {
...
+fn test_null_byte_input_multiline() {
+    new_ucmd!()
+        .pipe_in("1000\x00\n2000\x00")
+        .succeeds()
+        .stdout_is("1000\n2000\n");
+
+    new_ucmd!()
+        .pipe_in("1000\x002000\n3000")
+        .succeeds()
+        .stdout_is("1000\n3000\n");
```
Comment (cakebaker) [inline tests/by-util/test_numfmt.rs]: See my previous comment.
```suggestion
        .stdout_is("1000\n2000");

    new_ucmd!()
        .pipe_in("1000\x002000\n3000")
        .succeeds()
        .stdout_is("1000\n3000");
```

File: tests/by-util/test_numfmt.rs (hunk 1 above)
Comment (FidelSch) [reply tests/by-util/test_numfmt.rs:1258]: Interesting case. Seems to work differently with echo:
```bash
$ printf "1000\x00" | numfmt | cat -A
1000
$ echo -e "1000\x00" | numfmt | cat -A
1000$
$ echo -e "1000\0" | numfmt | cat -A
1000$
```

Comment (cakebaker) [reply tests/by-util/test_numfmt.rs:1258]: `echo` adds a trailing newline by default. You can disable it with `-n`:
```bash
$ echo -e -n "1000\x00" | numfmt | cat -A
1000
```

**Comment by cakebaker** [comment]
Thanks!
