### PR TITLE
ls: fix zero block size handling to match GNU ls

### LINKED ISSUE #8917: ls: zero block size leads to "divide by zero" error
When providing `--block-size=0 -l` we panic with:
```
$ cargo run -q ls --block-size=0 -l

thread 'main' panicked at src/uu/ls/src/ls.rs:2691:34:
attempt to divide by zero
```
GNU `ls`, on the other hand, shows an error message:
```
$ ls --block-size=0 -l
ls: invalid --block-size argument '0'
```

### PR DESCRIPTION
**Pull request by yrakcaz**
Fixes #8917

### CODE REVIEW

File: src/uu/ls/src/ls.rs [hunk 1]
```diff
@@ -903,19 +903,31 @@ impl Config {
         let (file_size_block_size, block_size) = if !opt_si && !opt_hr && !raw_block_size.is_empty()
         {
             match parse_size_u64(&raw_block_size.to_string_lossy()) {
```
Comment (Ada-Armstrong) [inline src/uu/ls/src/ls.rs]: You can simplify this once #8932 is merged by replacing `parse_size_u64` with `parse_size_non_zero_u64` instead of having a special case for 0.

Comment (cakebaker) [reply src/uu/ls/src/ls.rs]: @Ada-Armstrong good suggestion.

Comment (cakebaker) [reply src/uu/ls/src/ls.rs]: @yrakcaz #8932 is merged and `parse_size_non_zero_u64` is now available.

Comment (yrakcaz) [reply src/uu/ls/src/ls.rs]: Will do, thanks for the suggestion!

Comment (yrakcaz) [reply src/uu/ls/src/ls.rs]: Fixed.

**Comment by cakebaker** [comment]
Thanks for your PR!
