### PR TITLE
df: fix incorrect whitespace between columns

### LINKED ISSUE #3194: df: incorrect whitespace between columns in output table
This whitespace between columns in the table produced by `df` does not match that of GNU df.

GNU df:
```
$ df | head -n4
Filesystem                1K-blocks     Used Available Use% Mounted on
udev                        3858016        0   3858016   0% /dev
tmpfs                        782624     2112    780512   1% /run
/dev/mapper/vgubuntu-root 242791844 94907344 135481608  42% /

```

uutils df:
```
$ ./target/debug/df | head -n4
Filesystem          1k-blocks         Used    Available  Use% Mounted on       
udev                  3858016            0      3858016    0% /dev            
tmpfs                  782624         2112       780512    0% /run            
/dev/mapper/vgubuntu-root    242791844     94907356    147884488   39% /  
```

It appears that the column width depends on the length of the largest entry in the column.

### PR DESCRIPTION
**Pull request by cakebaker**
The main idea behind this PR is to introduce a `Table` struct to print a table. The print process now consists of two steps: 1) calculate the widths of the columns and 2) print the data. 

`Header` and `DisplayRow` (which has been renamed to `RowFormatter` (I'm not sure about this name, I struggled to find a name for it)) no longer do any output, they simply prepare the strings used by the table.

Fixes #3194.

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
Super cool! It'd be interesting to find similar cases in other utils and put this functionality in uucore (after this PR of course). There are plenty of utils that have some table-like format (`ls` and `wc` come to mind).

File: src/uu/df/src/table.rs [hunk 1]
```diff
@@ -240,82 +238,161 @@ impl<'a> DisplayRow<'a> {
...
+    /// The `options` control which column headers are returned.
+    fn get_headers(options: &Options) -> Vec<String> {
+        let mut headers = Vec::new();
+
+        for column in &options.columns {
+            let header = match column {
+                // We use a header's width as the minimum column width. To make this approach work
+                // with the "Filesystem" column with its wider minimum column width, we have to pad
+                // its header.
+                Column::Source => String::from("Filesystem    "),
```
Comment (jfinkels) [inline src/uu/df/src/table.rs:288]: Instead of trying to encode the minimum width in the length of the string, could we instead make an associated function on `Column`, say `Column::min_width()`? Then below in `Table::new()` you could have
```rust
         let mut widths: Vec<_> = options.columns.iter().map(Column::min_width).collect();
```

File: tests/by-util/test_df.rs [hunk 2]
```diff
@@ -279,15 +298,7 @@ fn test_output_file_specific_files() {
...
-    assert_eq!(
-        actual,
-        vec![
-            "File            ",
-            "a               ",
-            "b               ",
-            "c               "
-        ]
-    );
+    assert_eq!(actual, vec!["File", "a   ", "b   ", "c   "]);
```
Comment (jfinkels) [inline tests/by-util/test_df.rs:301]: This is certainly an improvement but it doesn't quite match the behavior of GNU. The last column in the table does not have trailing spaces.

This is certainly an improvement so I'm okay with merging this as-is, but just bringing it up as another opportunity to improve the output of `df`.

**Review by jfinkels — APPROVED** [review]

File: src/uu/df/src/table.rs (hunk 1 above)
Comment (cakebaker) [reply src/uu/df/src/table.rs:288]: Good point. I will move the minimum width to `Column`.

File: tests/by-util/test_df.rs (hunk 2 above)
Comment (cakebaker) [reply tests/by-util/test_df.rs:301]: Hm, I think you misread the snippet above. It contains a single column with a header and three values. And the trailing spaces are there because those values are shorter than the header.

**Comment by sylvestre** [comment]
Could you please fix the conflict? thanks

File: src/uu/df/src/columns.rs [hunk 3]
```diff
@@ -183,4 +183,31 @@ impl Column {
             _ => Err(()),
         }
     }
+
+    /// Return the alignment of the specified column.
+    pub(crate) fn align(column: &Self) -> Alignment {
```
Comment (tertsdiepraam) [inline src/uu/df/src/columns.rs:188]: A nit, but `align` is a verb and hence this sounds like it would change the alignment somehow, so I'd call this `alignment` instead.

File: src/uu/df/src/table.rs [hunk 4]
```diff
@@ -261,84 +259,163 @@ impl<'a> DisplayRow<'a> {
...
+impl fmt::Display for Table {
     fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
-        for column in &self.options.columns {
-            match column {
-                Column::Source => write!(f, "{0: <16} ", "Filesystem")?,
-                // `Display` is implemented for `BlockSize`, but
-                // `Display` only works when formatting an object into
-                // an empty format, `{}`. So we use `format!()` first
-                // to create the string, then use `write!()` to align
-                // the string and pad with spaces.
```
Comment (tertsdiepraam) [inline src/uu/df/src/table.rs:326]: Is this workaround no longer necessary?

**Review by tertsdiepraam — COMMENTED** [review]
Two small nits/questions, but looks good!

File: src/uu/df/src/columns.rs (hunk 3 above)
Comment (cakebaker) [reply src/uu/df/src/columns.rs]: Makes sense.

File: src/uu/df/src/table.rs (hunk 4 above)
Comment (cakebaker) [reply src/uu/df/src/table.rs:326]: No, I simply use `to_string()`, and the padding is no longer done in `Header` but in `Table`.

File: tests/by-util/test_df.rs (hunk 2 above)
Comment (jfinkels) [reply tests/by-util/test_df.rs:358]: Yes, I understand. When I said "the last column" I should have said "the last and only column in this test case". What I meant is that in GNU df there are no trailing spaces in the rightmost column of the output table:
```
$ touch a && df --output=file a | tr " " "_"
File
a
```

But in this branch there are trailing spaces:
```
$ touch a && ./target/debug/df --output=file a | tr " " "_"
File
a___
```

I'm okay with it, I just wanted to mention it as a follow-up improvement for a future pull request.

Comment (cakebaker) [reply tests/by-util/test_df.rs:358]: Thanks for the explanation, that makes sense.

**Review by tertsdiepraam — APPROVED** [review]

**Comment by tertsdiepraam** [comment]
Excellent work!
