### PR TITLE
mv: fix moving FIFO to a different filesystem

### LINKED ISSUE #7076: mv: fails to copy special files across filesystems
Environment: Ubuntu 20.04, uutils main branch (git commit 1e8e16b79c1d7ecaa248b4faa8e399ccdc8ba285), GNU coreutils v8.30

Steps to reproduce: 
```
# create a directory on a different filesystem
mkdir /dev/shm/tmp
# create a special file, in this case a FIFO
mknod pipe p
mv pipe /dev/shm/tmp
```

What happens now: uutils `mv` hangs indefinitely and never terminates.

What I expected to happen: GNU `mv` copies the special file to the target directory

Notes: this is causing a failure in the GNU test file `tests/mv/mv-special-1.sh`.

Because the source file and the destination are on different filesystems, the file is copied to the destination and then the source file is removed; this can be seen by passing the `--verbose` option:
```
$ mv --verbose pipe /dev/shm/tmp
copied 'pipe' -> '/dev/shm/tmp/pipe'
removed 'pipe'
```

### PR DESCRIPTION
**Pull request by jfinkels**
Fix a bug in `mv` where it would hang indefinitely while trying to copy
a FIFO across filesystems. The solution is to remove the old FIFO and
create a new one on the new filesystem.

~The first commit factors out helper functions from the `rename_with_fallback()` function
so that there is one fallback helper per file type (symlink, directory,
or file). This doesn't change the functionality of `mv`, it is just a
re-organization of the code.~ This was done in pull request https://github.com/uutils/coreutils/pull/7774

Fixes #7076

### CODE REVIEW

File: src/uu/mv/src/mv.rs [hunk 1]
```diff
@@ -650,139 +658,184 @@ fn rename(
...
-                .and_then(|_| fs::remove_file(from))?;
-            #[cfg(any(target_os = "macos", target_os = "redox", not(unix)))]
-            fs::copy(from, to).and_then(|_| fs::remove_file(from))?;
+            rename_file_fallback(from, to)
         }
+    })
+}
+
+#[cfg(unix)]
+fn make_fifo(path: &Path) -> io::Result<()> {
```
Comment (sylvestre) [inline src/uu/mv/src/mv.rs:695]: we have a similar code here:
https://github.com/uutils/coreutils/blob/1cd78c7a2b30baad4bfcf0aba5ca652b08519874/src/uu/cp/src/cp.rs#L2472

maybe we should create a function in uucore for this

Comment (jfinkels) [reply src/uu/mv/src/mv.rs]: I have factored the common `make_fifo` function out into `uucore::fs`.

File: src/uu/cp/src/cp.rs [hunk 2]
```diff
@@ -2475,12 +2471,10 @@ fn copy_fifo(dest: &Path, overwrite: OverwriteMode, debug: bool) -> CopyResult<(
...
     }
 
-    let name = CString::new(dest.as_os_str().as_bytes()).unwrap();
-    let err = unsafe { mkfifo(name.as_ptr(), 0o666) };
-    if err == -1 {
-        return Err(format!("cannot create fifo {}: File exists", dest.quote()).into());
+    match make_fifo(dest) {
+        Ok(_) => Ok(()),
+        Err(_) => Err(format!("cannot create fifo {}: File exists", dest.quote()).into()),
     }
```
Comment (sylvestre) [inline src/uu/cp/src/cp.rs:2477]:
```suggestion
makefifo(dest).map_err(|_| format!("cannot create fifo {}: File exists", dest.quote()).into())
```

probably more rust idiomatic

File: tests/by-util/test_mv.rs [hunk 3]
```diff
@@ -1791,3 +1793,16 @@ fn test_mv_error_msg_with_multiple_sources_that_does_not_exist() {
         .stderr_contains("mv: cannot stat 'a': No such file or directory")
         .stderr_contains("mv: cannot stat 'b/': No such file or directory");
 }
+
+#[cfg(not(windows))]
+#[ignore = "requires access to a different filesystem"]
+#[test]
+fn test_special_file_different_filesystem() {
+    let (at, mut ucmd) = at_and_ucmd!();
```
Comment (sylvestre) [inline tests/by-util/test_mv.rs:1801]: https://github.com/uutils/coreutils/pull/7249
might be useful :)

Comment (jfinkels) [reply tests/by-util/test_mv.rs:1801]: I just now tried to use the new `TestScenario::mount_temp_fs()` but I couldn't figure out how to get this test working with it. I just left a TODO comment mentioning it.

Comment (sylvestre) [reply tests/by-util/test_mv.rs:1801]: @matrixhead any idea ? :)

**Comment by sylvestre** [comment]
@jfinkels sorry but could you please rebase it?

**Comment by jfinkels** [comment]
I'll do that, but I'll also break some of these changes out into smaller pull requests.
