### PR TITLE
truncate: change cli error return code

### LINKED ISSUE #2951: truncate: exit status should be 1, not 2, on invalid arguments
The GNU version of `truncate` returns exit status 1 when the arguments are invalid, but the uutils version of `truncate` returns exit status 2.

GNU truncate
```
$ truncate file
truncate: you must specify either ‘--size’ or ‘--reference’
Try 'truncate --help' for more information.
$ echo $?
1
```

uutils truncate
```
$ ./target/debug/truncate file
error: The following required arguments were not provided:
    --reference <RFILE>
    --size <SIZE>

USAGE:
    ./target/debug/truncate [OPTION]... [FILE]...

For more information try --help
$ echo $?
2
```

In order to get the first two test cases in the GNU test file `tests/misc/truncate-parameters.sh` to pass, the uutils version needs to return exit status 1 in this situation.

### PR DESCRIPTION
**Pull request by shoriminimoe**
Exit with status code 1 for argument parsing errors in `truncate`. When `clap` encounters an error during argument parsing, it exits with status code 2. This causes some GNU tests to fail since they expect status code 1.

Closes #2951

### CODE REVIEW

File: src/uu/truncate/src/truncate.rs [hunk 1]
```diff
@@ -115,7 +115,16 @@ pub fn uumain(args: impl uucore::Args) -> UResult<()> {
     let matches = uu_app()
         .override_usage(&usage[..])
         .after_help(&long_usage[..])
-        .get_matches_from(args);
+        .try_get_matches_from(args)
+        .unwrap_or_else(|e| {
+            e.print().expect("Error writing clap::Error");
+            match e.kind {
+                clap::ErrorKind::DisplayHelp | clap::ErrorKind::DisplayVersion => {
+                    std::process::exit(0)
```
Comment (tertsdiepraam) [inline src/uu/truncate/src/truncate.rs:123]: Nit to make it a bit cleaner using `UResult` and so that we don't have to call `std::process:exit`:
```rust
.map_err(|e| {
    e.print().expect("Error writing clap::Error");
    match e.kind {
        clap::ErrorKind::DisplayHelp | clap::ErrorKind::DisplayVersion => 0,
        _ => 1,
    }
})?;
```

**Review by tertsdiepraam — COMMENTED** [review]
Thanks! Looks good! Could you add a small test for this behaviour? Just testing that `truncate --this-arg-does-not-exist` returns `1` is fine.

File: src/uu/truncate/src/truncate.rs (hunk 1 above)
Comment (shoriminimoe) [reply src/uu/truncate/src/truncate.rs:123]: I love it. Working on it now.

**Review by tertsdiepraam — APPROVED** [review]
