### PR TITLE
`tests/tail`: Fix tests to reflect changes from the refactoring #3905

### LINKED ISSUE #3881: `tail`: piped or redirected input on windows and android platforms is not implemented
When input comes from a pipe or fifo on windows and android platforms there is no output and no processing of that input, at all. This is part of the problem when determining if the input is a fifo, pipe, file etc. A related issue is #3845. The if check here

https://github.com/uutils/coreutils/blob/0dbcdde64e1ef35ff79122622a9c4fbe3d251292/src/uu/tail/src/tail.rs#L439

fails because path_is_tailable resolves to false because the check in `path.is_tailable()`

https://github.com/uutils/coreutils/blob/0dbcdde64e1ef35ff79122622a9c4fbe3d251292/src/uu/tail/src/tail.rs#L1635

returns false. On windows platforms (and I assume on android platforms, too) the statement `self.is_file() || self.exists() = false` resolves to false. This leads to the input not handled and silently ignored, since the `if ... else if .. else if` chain above misses an `else` branch, where I would at least expect an error message. To me, the determination of `tailable` and if a path is `fifo, pipe` looks broken and is scattered over a 2000 lines file. Wouldn't it be clearer to determine with which kind of input and files we're dealing with right from the start when parsing the settings, store what we've found in a struct or enum and then handle all cases? Looking at this big tail file. refactoring tail.rs to be clearer would help resolving the different handling of input on different platforms.

### PR DESCRIPTION
**Pull request by Joining7943**
This is a follow up pr to #3905 (refactoring tail), in which the tests for tail are updated to reflect the current state of tail's implementation. 

I removed all cfg attributes from the tests which limited the tests by vendor, os ([ci 8594](https://github.com/uutils/coreutils/actions/runs/3101684375)), then added cfg attributes again for the tests failing in the ci for a specific target os ([ci 8604](https://github.com/uutils/coreutils/actions/runs/3107790421), [ci 8605](https://github.com/uutils/coreutils/actions/runs/3108275942), [ci 8606](https://github.com/uutils/coreutils/actions/runs/3109053464), [ci 8607](https://github.com/uutils/coreutils/actions/runs/3109572586)). This is a quick overview over the outcome and the main differences to before the refactoring:

+ Piped input: works now for all platforms; worked before for all oses but windows and android
+ Redirected input: before: linux; after: all but apple
+ There are also some additional general and --follow tests working
+ ... See diff to main or the summary below

<details>
<summary>Summary and curated diff from this branch to main</summary>

```diff
-#[cfg(all(unix, not(any(target_os = "android", target_vendor = "apple"))))]
+#[cfg(not(target_vendor = "apple"))]
test_stdin_redirect_file

-#[cfg(all(unix, not(any(target_os = "android", target_vendor = "apple"))))]
+#[cfg(not(target_vendor = "apple"))]
test_stdin_redirect_offset

 #[test]
-#[cfg(all(unix, not(any(target_os = "android", target_vendor = "apple"))))]
+#[cfg(all(not(target_vendor = "apple"), not(target_os = "windows")))]
test_stdin_redirect_offset2

-#[cfg(all(unix, not(target_os = "freebsd")))]
+#[cfg(unix)]
test_permission_denied

-#[cfg(all(unix, not(target_os = "freebsd")))]
+#[cfg(unix)]
test_permission_denied_multiple
-#[cfg(target_os = "linux")]
test_follow_redirect_stdin_name_retry

-#[cfg(not(target_os = "macos"))]
-#[cfg(all(unix, not(any(target_os = "android", target_os = "freebsd"))))]
+#[cfg(all(
+    not(target_vendor = "apple"),
+    not(target_os = "windows"),
+    not(target_os = "android"),
+    not(target_os = "freebsd")
+))]
test_stdin_redirect_dir

-#[cfg(target_os = "linux")]
test_follow_stdin_descriptor

-#[cfg(target_os = "linux")]
test_follow_stdin_name_retry

-#[cfg(target_os = "linux")]
-#[cfg(disable_until_fixed)]
test_follow_bad_fd

-#[cfg(unix)]
+#[cfg(not(target_os = "windows"))]
test_follow_single

-#[cfg(unix)]
+#[cfg(not(target_os = "windows"))]
test_follow_non_utf8_bytes

-#[cfg(unix)]
+#[cfg(not(target_os = "windows"))]
test_follow_multiple

-#[cfg(unix)]
+#[cfg(not(target_os = "windows"))]
test_follow_name_multiple

-#[cfg(unix)]
test_follow_multiple_untailable

-#[cfg(all(unix, not(target_os = "android")))]
test_follow_stdin_pipe

-#[cfg(unix)]
+#[cfg(not(target_os = "windows"))]
test_follow_invalid_pid

-#[cfg(disable_until_fixed)]
+#[cfg(all(
+    not(target_vendor = "apple"),
+    not(target_os = "windows"),
+    not(target_os = "android")
+))]
test_follow_with_pid

-#[cfg(all(unix, not(target_os = "android")))]
test_bytes_stdin

-#[cfg(all(unix, not(target_os = "android")))]
test_positive_bytes

-#[cfg(all(unix, not(target_os = "android")))]
test_positive_zero_bytes

-#[cfg(all(unix, not(target_os = "android")))]
test_positive_lines

-#[cfg(all(unix, not(target_os = "android")))]
test_obsolete_syntax_positive_lines

-#[cfg(all(unix, not(target_os = "android")))]
test_small_file

-#[cfg(all(unix, not(target_os = "android")))]
test_obsolete_syntax_small_file

-#[cfg(all(unix, not(target_os = "android")))]
test_positive_zero_lines

-#[cfg(all(unix, not(target_os = "android")))]
test_invalid_num

-#[cfg(all(unix, not(target_os = "android")))]
test_num_with_undocumented_sign_bytes

-#[cfg(unix)]
test_retry1

-#[cfg(unix)]
test_retry2

-#[cfg(target_os = "linux")]
+#[cfg(not(target_os = "windows"))]
test_retry6

-#[cfg(all(unix, not(any(target_os = "android", target_vendor = "apple"))))]
+#[cfg(all(not(target_os = "windows"), not(target_os = "freebsd")))]
test_retry9

-#[cfg(target_os = "linux")]
+#[cfg(all(
+    not(target_vendor = "apple"),
+    not(target_os = "windows"),
+    not(target_os = "freebsd")
+))]
test_follow_descriptor_vs_rename1

-#[cfg(target_os = "linux")]
+#[cfg(all(
+    not(target_vendor = "apple"),
+    not(target_os = "windows"),
+    not(target_os = "freebsd")
+))]
test_follow_descriptor_vs_rename2

-#[cfg(all(unix, not(target_os = "android")))]
+#[cfg(all(not(target_os = "windows"), not(target_os = "android")))]
test_follow_name_remove

 #[test]
-#[cfg(target_os = "linux")]
+#[cfg(all(
+    not(target_os = "windows"),
+    not(target_os = "android"),
+    not(target_os = "freebsd")
+))]
test_follow_name_truncate1

-#[cfg(target_os = "linux")]
+#[cfg(all(
+    not(target_os = "windows"),
+    not(target_os = "android"),
+    not(target_os = "freebsd")
+))]
test_follow_name_truncate2

-#[cfg(target_os = "linux")]
+#[cfg(not(target_os = "windows"))]
test_follow_name_truncate3

-#[cfg(unix)]
+#[cfg(not(target_os = "windows"))]
test_follow_name_truncate4

-#[cfg(all(unix, not(target_os = "android")))]
+#[cfg(not(target_os = "windows"))]
test_follow_truncate_fast

-#[cfg(target_os = "linux")]
+#[cfg(all(
+    not(target_vendor = "apple"),
+    not(target_os = "windows"),
+    not(target_os = "freebsd")
+))]
test_follow_name_move_create2

-#[cfg(all(unix, not(target_os = "freebsd")))]
+#[cfg(not(target_os = "windows"))]
test_follow_inotify_only_regular

-#[cfg(unix)]
take_stdout_stderr

-#[cfg(all(unix, not(target_os = "android")))]
test_no_trailing_newline

-#[cfg(all(unix, not(target_os = "android")))]
test_lines_zero_terminated

-#[cfg(all(unix, not(target_os = "android")))]
test_presume_input_pipe_default

-#[cfg(unix)]
+#[cfg(not(windows))]
test_fifo

-#[cfg(all(not(target_os = "android"), not(target_os = "windows")))]
mod pipe_tests
```

</details>

For completeness:
I needed to keep 2 piped input tests for windows switched off which are not working in the ci because the tests timed out. I couldn't reproduce locally why they are hanging and they ran successfully in a Windows 10 Virtualbox image.

Fixes #3881

### CODE REVIEW

File: tests/by-util/test_tail.rs [hunk 1]
```diff
@@ -148,6 +150,7 @@ fn test_stdin_redirect_offset2() {
         .succeeded();
 }
 
+// TODO: Use a debug_assert() instead
```
Comment (tertsdiepraam) [inline tests/by-util/test_tail.rs:153]: Instead of what? Also `debug_assert` is not very meaningful in tests. Tests are not included in regular binaries and should probably always fail early if something yas gone wrong, even when run with `--release`

File: tests/by-util/test_tail.rs [hunk 2]
```diff
@@ -169,37 +172,9 @@ fn test_nc_0_wo_follow() {
         .succeeded();
 }
 
+// TODO: Add similar test for windows
 #[test]
-#[cfg(all(unix, not(target_os = "freebsd")))]
-fn test_nc_0_wo_follow2() {
```
Comment (tertsdiepraam) [inline tests/by-util/test_tail.rs:174]: Why is this removed?

File: tests/by-util/test_tail.rs [hunk 3]
```diff
@@ -266,8 +241,12 @@ fn test_follow_redirect_stdin_name_retry() {
...
 
 #[test]
-#[cfg(not(target_os = "macos"))] // See test_stdin_redirect_dir_when_target_os_is_macos
-#[cfg(all(unix, not(any(target_os = "android", target_os = "freebsd"))))] // FIXME: fix this test for Android/FreeBSD
+#[cfg(all(
+    not(target_vendor = "apple"),
+    not(target_os = "windows"),
+    not(target_os = "android"),
+    not(target_os = "freebsd")
+))] // FIXME:
```
Comment (tertsdiepraam) [inline tests/by-util/test_tail.rs:249]: There's a couple of these `FIXME:` comments. I'd say either give an explanation or remove the colon :)

File: tests/by-util/test_tail.rs [hunk 4]
```diff
@@ -266,8 +241,12 @@ fn test_follow_redirect_stdin_name_retry() {
 }
 
 #[test]
-#[cfg(not(target_os = "macos"))] // See test_stdin_redirect_dir_when_target_os_is_macos
-#[cfg(all(unix, not(any(target_os = "android", target_os = "freebsd"))))] // FIXME: fix this test for Android/FreeBSD
+#[cfg(all(
+    not(target_vendor = "apple"),
```
Comment (tertsdiepraam) [inline tests/by-util/test_tail.rs:245]: Not really a comment, more a question. Why are you using `target_vendor` instead of `target_os`? One includes iOS and the other one doesn't?

File: tests/by-util/test_tail.rs [hunk 5]
```diff
@@ -363,7 +340,6 @@ fn test_follow_stdin_name_retry() {
 }
 
 #[test]
-#[cfg(target_os = "linux")]
```
Comment (tertsdiepraam) [inline tests/by-util/test_tail.rs:366]: Is this test gonna work on all platforms eventually or can it only be fixed for some platforms?

File: tests/by-util/test_tail.rs [hunk 6]
```diff
@@ -1119,13 +1092,13 @@ fn test_invalid_num() {
...
         .stderr_str()
         .starts_with("tail: invalid number of lines: '1024R'");
-    #[cfg(not(target_pointer_width = "128"))]
+
     new_ucmd!()
         .args(&["-c", "1Y", "emptyfile.txt"])
         .fails()
         .stderr_str()
         .starts_with("tail: invalid number of bytes: '1Y': Value too large for defined data type");
-    #[cfg(not(target_pointer_width = "128"))]
```
Comment (tertsdiepraam) [inline tests/by-util/test_tail.rs:1128]: Feels like we should definitely keep these? CI can't cover every possible arch and OS we want to run the tests on

File: tests/common/random.rs [hunk 7]
```diff
@@ -310,5 +310,25 @@ mod tests {
             random_string.as_bytes().iter().filter(|p| **p == 0).count()
         );
         assert!(random_string.as_bytes().ends_with(&[0]));
+
+        // This test exists to exclude an error (timeout) occurred during system tests on windows
```
Comment (tertsdiepraam) [inline tests/common/random.rs:314]: How does it do this?

**Review by tertsdiepraam — COMMENTED** [review]
Looks like you forgot to include the changes in `tail.rs`? I only see `test_tail.rs` and `random.rs`.

**Comment by Joining7943** [comment]
> Looks like you forgot to include the changes in `tail.rs`? I only see `test_tail.rs` and `random.rs`.

I didn't change anything in `tail.rs` since the refactoring.

File: tests/by-util/test_tail.rs (hunk 1 above)
Comment (Joining7943) [reply tests/by-util/test_tail.rs:153]: Sorry, seems my TODOs are only meant for me. This is a quick one about adding a debug_assert() in tail.rs() after the immediate exit because of `-[nc]0` instead of trying to provoke an error like passing a missing file to tail. A debug_assert() is more precise in my eyes.

File: tests/by-util/test_tail.rs (hunk 4 above)
Comment (Joining7943) [reply tests/by-util/test_tail.rs:245]: I looked through the repo and it seems like this is the preferred method to switch off tests for macos or apple in general. We only test on macos in the CI, but most probably this test won't work on iOS or something else from apple.

File: tests/by-util/test_tail.rs (hunk 6 above)
Comment (Joining7943) [reply tests/by-util/test_tail.rs:1128]: ok

File: tests/common/random.rs (hunk 7 above)
Comment (Joining7943) [reply tests/common/random.rs:314]: It does so because this is the exact code from the test in which I used the random generator and the test timed out. But there's more code in the test, so to exclude the possibility that it has something to do with the random string generator, I added these lines from the test here and test them separately.

File: tests/by-util/test_tail.rs (hunk 5 above)
Comment (Joining7943) [reply tests/by-util/test_tail.rs:366]: Good question...

File: tests/by-util/test_tail.rs (hunk 2 above)
Comment (Joining7943) [reply tests/by-util/test_tail.rs:174]: Because the test is platform specific in contrast to `test_nc_0_wo_follow` and it doesn't add value. In my eyes the `test_nc_0_wo_follow` test was sufficient. However, it could be more precise with the debug_assert(). If you like to, I can readd it.

File: tests/by-util/test_tail.rs (hunk 3 above)
Comment (Joining7943) [reply tests/by-util/test_tail.rs:249]: However, I'll write a short explanation for the standalone FIXMEs :)

**Comment by Joining7943** [comment]
@tertsdiepraam A little addition to my last comment. I'm not sure if my explanation in the header of this pr was a little bit short. This pr doesn't change any production code. I've already done this in the refactoring pr. I'm kind of summarizing in this pr, what was achieved in the refactoring pr #3905.

File: tests/by-util/test_tail.rs (hunk 2 above)
Comment (jhscheer) [reply tests/by-util/test_tail.rs:174]: I can't follow your reasoning.
> Because the test is platform specific in contrast to test_nc_0_wo_follow

This should not be a reason to remove a test.

> and it doesn't more information.

But the two tests check different things.

File: tests/common/random.rs (hunk 7 above)
Comment (tertsdiepraam) [reply tests/common/random.rs:314]: Hmm, ok, I'm not 100% if this is useful, but I think it's a vit better to at least add that explanation to the code here

File: tests/by-util/test_tail.rs (hunk 5 above)
Comment (tertsdiepraam) [reply tests/by-util/test_tail.rs:366]: We should probably keep the `cfg` then, ut was probably added for a reason.

**Comment by tertsdiepraam** [comment]
I see. That makes sense, but indeed wasn't totally clear to me from the title and description.

**Comment by Joining7943** [comment]
@tertsdiepraam I updated the title and description

File: tests/by-util/test_tail.rs (hunk 5 above)
Comment (Joining7943) [reply tests/by-util/test_tail.rs:366]: ok

File: tests/by-util/test_tail.rs [hunk 8]
```diff
@@ -148,6 +150,8 @@ fn test_stdin_redirect_offset2() {
         .succeeded();
 }
 
+// TODO: Use a debug_assert() in tail.rs, which is more precise, to verify we're
+// exiting immediately instead of the approach below.
```
Comment (tertsdiepraam) [inline tests/by-util/test_tail.rs:154]: Please remove this TODO

File: tests/by-util/test_tail.rs [hunk 9]
```diff
@@ -94,15 +92,15 @@ fn test_stdin_redirect_file() {
         .run_no_wait();
 
     sleep(Duration::from_millis(500));
-    p.kill().unwrap();
+    let _ = p.kill();
```
Comment (tertsdiepraam) [inline tests/by-util/test_tail.rs:95]: Is this a fix for something? I'd prefer unwrap, because it fails explicitly.

**Review by tertsdiepraam — COMMENTED** [review]
I generally like this change. Enabling more tests is always good. I have two more small comments and please put the removed test back from the last review.

File: tests/by-util/test_tail.rs (hunk 9 above)
Comment (Joining7943) [reply tests/by-util/test_tail.rs:95]: Yes, this change made the test work on windows and maybe other platforms, I don't remeber currently. The cause may be, that it's an error on windows to try to kill a non running or already stopped process in contrast to unix. However, if the child can be killed successfully or not is not essential for this test. The `p.kill()` at this point only cleanups the test and the `_` indicates the `don't care for the result`. I don't want to be nitpicky but in tests I would actually prefer using an assertion, if I wanted or needed to be explicit about a result.

**Comment by Joining7943** [comment]
> I generally like this change.

Thanks :) and thanks for the review.

> Enabling more tests is always good. 

Generally, I like more tests, too. But here, I also wanted to cement what we gained so far.

> I have two more small comments and please put the removed test back from the last review.

Concerning the TODO and tests, please let me propose an alternative solution, which improves these tests a little bit. Originally, I didn't want to alter production files in this pr, so I kept this TODO. However, I added an additional commit, so you can see, what I meant with the TODO.

File: tests/by-util/test_tail.rs (hunk 9 above)
Comment (jhscheer) [reply tests/by-util/test_tail.rs:93]: This is super useful information, please add a comment to the line so we don't regress.

**Comment by jhscheer** [comment]
> Concerning the TODO and tests, please let me propose an alternative solution, which improves these tests a little bit.

Please do not remove the two `nc_0_wo_follow` tests, they're there to ensure we don't regress and fail `gnu/tests/tail-2/tail-n0f.sh`.

**Comment by Joining7943** [comment]
@tertsdiepraam Did you already have a look at the last commit?

**Comment by tertsdiepraam** [comment]
Sorry, I don't like the `debug_assert` approach. One reason is that the assert is disjointed from the actual testing code, making it so that it's easily removed by an unsuspecting contributor. Secondly, tests can also be run in release mode in which case the `debug_assert` is removed. What was wrong with the original test? It also feels like it's just testing whether if expressions and `std::process::exit` work? It's reusing the logic within `tail`, making the test less meaningful if that makes sense.

**Comment by Joining7943** [comment]
@tertsdiepraam No problem.

**Comment by Joining7943** [comment]
@tertsdiepraam I took care of all your comments. The macos timeout looks like a ci problem. All other tests on macos have been running successfully...

File: tests/by-util/test_tail.rs (hunk 9 above)
Comment (tertsdiepraam) [reply tests/by-util/test_tail.rs:93]: @Joining7943 this is still unresolved :)

File: tests/by-util/test_tail.rs [hunk 10]
```diff
@@ -1512,7 +1540,7 @@ fn test_retry8() {
 }
 
 #[test]
-#[cfg(all(unix, not(any(target_os = "android", target_vendor = "apple"))))] // FIXME: make this work not just on Linux
+#[cfg(all(not(target_os = "windows"), not(target_os = "freebsd")))] // FIXME: for currently not working platforms
```
Comment (jhscheer) [inline tests/by-util/test_tail.rs:1543]: This test is problematic. It has been observed to sometimes fail on MinRustV and now macOS.
https://github.com/uutils/coreutils/issues/3929
Until this is fixed I would not relax the cfg.

File: tests/by-util/test_tail.rs [hunk 11]
```diff
@@ -2512,722 +2590,721 @@ fn test_illegal_seek() {
...
-        new_ucmd!()
-            .args(&["-n", "+0"])
-            .pipe_in(random_string)
-            .ignore_stdin_write_error()
-            .succeeds()
-            .stdout_only(random_string);
+// FIXME: windows: this test failed with timeout in the CI. Running this test in
+// a Windows VirtualBox image produces no errors.
+#[test]
+#[cfg(not(target_os = "windows"))]
```
Comment (jhscheer) [inline tests/by-util/test_tail.rs:2911]: In case a test runs locally but not in the CI, I would use `is_ci()`, instead of disabling the test completely.
e.g.
```rust
if cfg!(windows) && is_ci() {
    println!("TEST SKIPPED (<reason>)");
    return;
}
```

File: tests/by-util/test_tail.rs [hunk 12]
```diff
@@ -2512,722 +2590,721 @@ fn test_illegal_seek() {
...
+}
 
-    #[test]
-    fn test_pipe_when_bytes_option_given_input_size_has_multiple_size_of_buffer_size() {
-        let random_string = RandomString::generate(AlphanumericNewline, CHUNK_BUFFER_SIZE * 3);
-        let random_string = random_string.as_str();
+// FIXME: windows: this test failed with timeout in the CI. Running this test in
+// a Windows VirtualBox image produces no errors.
+#[test]
+#[cfg(not(target_os = "windows"))]
```
Comment (jhscheer) [inline tests/by-util/test_tail.rs:3218]: See comment about `is_ci()` above.

**Review by jhscheer — CHANGES_REQUESTED** [review]
Looks good to me.
Please consider my suggestions.

Thanks for all the extensive testing on the various platforms.

File: tests/by-util/test_tail.rs (hunk 10 above)
Comment (Joining7943) [reply tests/by-util/test_tail.rs:1543]: won't fix

File: tests/by-util/test_tail.rs (hunk 12 above)
Comment (Joining7943) [reply tests/by-util/test_tail.rs:3218]: won't fix

File: tests/by-util/test_tail.rs (hunk 10 above)
Comment (tertsdiepraam) [reply tests/by-util/test_tail.rs:1543]: Are you aware that this comes across as quite rude? Why is this a won't fix? @jhscheer brings up a valid problem with your PR, so that needs to be fixed before we can merge this. I'm unresolving this conversation until it is actually resolved.

Comment (Joining7943) [reply tests/by-util/test_tail.rs:1543]: It's a won't fix because this is actually valuable information about the intermittenly failing tests. Additionally, these intermittently failing tests are not part of this pr nor the refactoring on which this pr is based on. You may wish to disable the test until it is fixed, but I would suggest another pr for this.

Comment (tertsdiepraam) [reply tests/by-util/test_tail.rs:1543]: But this PR enables the test on mac, which is not correct. So this PR should not introduce that change in the first place.

Comment (Joining7943) [reply tests/by-util/test_tail.rs:1543]: The retry9 test is failing intermittently, but not because of the refactoring pr. It also does on macos but now you can notice this fact and maybe it helps figuring out the problem. The test usually passes and if not then because of #3929.

Comment (tertsdiepraam) [reply tests/by-util/test_tail.rs:1543]: We try to keep intermittent failure to a minimum, because it affects everyone's CI for PRs. We can't accept PRs that knowingly introduce more intermittent failures.

The refactoring PR has nothing to do with this. There is a test that fails (intermittently) and this PR enables it, which is a problem and that is why this PR has to just not do that.

> It also does on macos but now you can notice this fact and maybe it helps figuring out the problem.

We now indeed know this and that is helpful, but that's not a valid reason that we should ignore the problem here. We're not asking you to fix anything, just to revert the change that you made for this specific test.

Comment (Joining7943) [reply tests/by-util/test_tail.rs]: I'm not sure this is going into the right direction, but if dsabling this test on macos is all you want, it's done.

File: tests/by-util/test_tail.rs (hunk 11 above)
Comment (Joining7943) [reply tests/by-util/test_tail.rs:2915]: won't fix

Comment (sylvestre) [reply tests/by-util/test_tail.rs:2915]: Please explain why "Won't fix"

Comment (Joining7943) [reply tests/by-util/test_tail.rs:2915]: I won't change it, because it's correct the way it is. It clearly indicates the implementation has a problem on windows. The comment just explains what I've found out and is a help for others. Sure it's failing in the ci and passing on my pc and my virtualbox but that doesn't mean there's something wrong with the implementation for windows, so it is switched off entirely. Windows pipes are different from unix pipes and fixing this in this pr is out of the scope of this pr. Additionally, if someone's running the test suite on windows but working on uutils in a different place he may probably run in this timeout.

Comment (sylvestre) [reply tests/by-util/test_tail.rs:2915]: @jhscheer ok with you?

Comment (jhscheer) [reply tests/by-util/test_tail.rs:2915]: Yes.
