### PR TITLE
`expr`: fix expr syntax error

### LINKED ISSUE #5377: expr: 12 \| 9a + 1 causes a syntax error
GNU expr:
```
$ expr 12 \| 9a + 1
12
```
uutils expr:
```
$ cargo run expr 12 \| 9a + 1
expr: syntax error (first RPN token does not represent the root of the expression AST)
```

### PR DESCRIPTION
**Pull request by Luv-Ray**
fix #5377 
`+` may escape such as `expr + 1` and `expr 1 + + 1`, and the cause of syntex error of `expr 12 \| 9a + 1` is the `+` escaped incorrectly.

Now the condition for escape is `!(pre_prev.1.is_a_value() || pre_prev.1.is_a_close_paren())`, but I'm not sure if the condition is identical to GNU.

I have add the test set for escape, and it would be better to have more test cases.

### CODE REVIEW

File: src/uu/expr/src/tokens.rs [hunk 1]
```diff
@@ -131,14 +126,14 @@ fn maybe_dump_tokens_acc(tokens_acc: &[(usize, Token)]) {
 }
 
 fn push_token_if_not_escaped(acc: &mut Vec<(usize, Token)>, tok_idx: usize, token: Token, s: &str) {
-    // Smells heuristics... :(
+    // `+` may escaped such as `expr + 1` and `expr 1 + + 1`
```
Comment (cakebaker) [inline src/uu/expr/src/tokens.rs:129]:
```suggestion
    // `+` may be escaped such as `expr + 1` and `expr 1 + + 1`
```

**Review by cakebaker — APPROVED** [review]

**Comment by cakebaker** [comment]
Thanks!
