### PR TITLE
chmod: supress verbose output when not verbose

### LINKED ISSUE #4381: chmod: Extra verbosity for symlink creation is wrong
MRE
```
>touch a
>ln -s a b
rm a
```
Produces different output
```
uu_chmod u+x b
failed to change mode of 'b' from 0000 (---------) to 0000 (---------)
./target/debug/chmod: cannot operate on dangling symlink 'b'
```
GNU 
```
chmod u+x b
chmod: cannot operate on dangling symlink 'b'
```
However, if the `--verbose` flag is used, then the messages match , but still the `uu_chmod` is wrong, as :

```
uu_chmod u+x --verbose b
failed to change mode of 'b' from 0000 (---------) to 0000 (---------)
./target/debug/chmod: cannot operate on dangling symlink 'b'
```

GNU 
```
chmod u+x --verbose b
chmod: cannot operate on dangling symlink 'b'
failed to change mode of 'b' from 0000 (---------) to 1500 (r-x-----T)
```
Notice the `r-x-----T` and the `1500`, whereas `uu_chmod` has a hardcoded failure message(for mode)
Introduced in #1967

### PR DESCRIPTION
**Pull request by dmatos2012**
Closes #4381.  Shows verbose output only when `--verbose` flag is used instead

### CODE REVIEW

File: src/uu/chmod/src/chmod.rs [hunk 1]
```diff
@@ -190,16 +190,18 @@ impl Chmoder {
...
                             1,
                             format!("cannot operate on dangling symlink {}", filename.quote()),
                         ));
                     }
+                    if self.verbose {
+                        println!(
+                            "failed to change mode of {} from 0000 (---------) to 1500 (r-x-----T)",
+                            filename.quote()
+                        );
+                    }
```
Comment (tertsdiepraam) [inline src/uu/chmod/src/chmod.rs:204]: Not your fault, but it's weird that quiet and verbose are separate booleans isn't it? Those options should override each other, so that
```
chmod --verbose --quiet
```
is the same as
```
chmod --quiet
```

And it's also not currently possible to do, for example,
```
chmod --verbose --verbose
```

Maybe this is a good opportunity to fix that?

Comment (tertsdiepraam) [reply src/uu/chmod/src/chmod.rs:204]: Well, nevermind, that's not how GNU chmod works! `--verbose --quiet` and `--quiet` _are_ different.

**Comment by tertsdiepraam** [comment]
Thanks! If you're up for it, you can fix that `--verbose --verbose` and `--quiet --quiet` should be allowed.
