### PR TITLE
Fix Du mac/inodes

### LINKED ISSUE #1163: du on mac does not calculate block size correctly
> target/debug/du  -d 1 ../dus/src/test_dir/many/b
> 16	../dus/src/test_dir/many/b

> du ../dus/src/test_dir/many/b
> 32	../dus/src/test_dir/many/b

Fairly sure the block size is just half of what it should be on mac. 
Fix: Use the specific metadata functions that can be called for each OS.

https://doc.rust-lang.org/std/os/linux/fs/trait.MetadataExt.html

I can fix this.

### PR DESCRIPTION
**Pull request by bootandy**
fixes #1163 #1164 
Fixes block size on mac
Fixes du counting files with the same inode
Adds tests for du

### CODE REVIEW

File: tests/test_du.rs [hunk 1]
```diff
@@ -0,0 +1,124 @@
...
+fn test_du_hard_link() {
+    let ts = TestScenario::new("du");
+
+    let link = ts.cmd("ln").arg(SUB_FILE).arg(SUB_LINK).run();
+    assert!(link.success);
+
+    let result = ts.ucmd().arg(SUB_DIR_LINKS).run();
+    assert!(result.success);
+    assert_eq!(result.stderr, "");
+    // We do not double count hard links as the inodes are identicle
```
Comment (Arcterus) [inline tests/test_du.rs]: "identicle" should be "identical"

File: tests/test_du.rs [hunk 2]
```diff
@@ -0,0 +1,124 @@
+use common::util::*;
+
+static SUB_DIR: &str = "subdir/deeper";
```
Comment (Arcterus) [inline tests/test_du.rs]: Can you change these to `const` instead of `static`?  Most of the things in the codebase using `static` just haven't been updated (that used to be the only to have constants).

File: src/du/du.rs [hunk 3]
```diff
@@ -398,7 +422,9 @@ Try '{} --help' for more information.",
                     }
                 }
             }
-            Err(error) => show_error!("{}", error),
+            Err(_) => {
+                show_info!("{}: {}", path_str, "No such file or directory");
```
Comment (Arcterus) [inline src/du/du.rs]: These seems like it should be reported as an error, so I think `show_error!` is the correct macro to use here.

File: src/du/du.rs [hunk 4]
```diff
@@ -62,16 +64,32 @@ impl Stat {
...
             created: metadata.mtime() as u64,
             accessed: metadata.atime() as u64,
             modified: metadata.mtime() as u64,
         })
     }
 }
 
+#[cfg(target_os = "macos")]
+fn get_default_blocks() -> u64 {
+    512
```
Comment (Arcterus) [inline src/du/du.rs]: I just ran `gdu` on my Mac, and it seems to be using 1024-byte blocks AFAICT.  The default `du` (inherited from BSD) does seem to use 512-byte blocks though.  As we are trying to mimic the behavior of the GNU version, 1024 seems to make the most sense by default.

I have found [this](https://www.gnu.org/software/coreutils/manual/html_node/Block-size.html) though (which I was not aware of before), so perhaps you can implement this?  It sounds the GNU version isn't technically correct according to POSIX, unlike the Mac version, which is the source of the discrepancy.

File: src/du/du.rs (hunk 3 above)
Comment (bootandy) [reply src/du/du.rs]: I considered that. Yes it does seem to be an error but if we call _show_error!_ then the string 'Error' appears in the middle of the output. This makes the output different to 'C' du which does not have this. 

Quite happy to change this, just letting you know the error message will then be different to 'C' du.

File: src/du/du.rs (hunk 4 above)
Comment (bootandy) [reply src/du/du.rs]: I'm happy to make it read the POSIXLY_CORRECT flag. But I don't think we've got to the root cause of confusion yet. 

env | grep POS
env | grep BLOCK
returns nothing on my macbook or my linux server.

Going to do some digging.

Comment (bootandy) [reply src/du/du.rs]: Yes looks like you are right with du / gdu. 

Strangely I'd started implementing the BLOCK_SIZE environment variables on a branch as I'd noticed they were missing. I'll incorporate that work.

File: src/du/du.rs (hunk 3 above)
Comment (Arcterus) [reply src/du/du.rs]: I don't think the GNU utils ever print `error: blah`, so basically everything that uses `show_error!` isn't 100% the same as the GNU version.  Maybe we should eventually add a `GNULY_COMPLIANT` variable or something lol.

File: src/du/du.rs [hunk 5]
```diff
@@ -62,16 +65,39 @@ impl Stat {
...
+            inode: metadata.ino() as u64,
             created: metadata.mtime() as u64,
             accessed: metadata.atime() as u64,
             modified: metadata.mtime() as u64,
         })
     }
 }
 
+fn get_default_blocks() -> u64 {
+    for env_var in ["DU_BLOCK_SIZE", "BLOCK_SIZE", "BLOCKSIZE"].into_iter() {
```
Comment (Arcterus) [inline src/du/du.rs]: It seems that `gdu` doesn't actually error if the variable value is wrong, so you could just do this instead:
```rust
for env_var in &["DU_BLOCK_SIZE", "BLOCK_SIZE", "BLOCKSIZE"] {
    if let Some(result) = env::var(env_var).ok().and_then(|val| val.parse().ok()) {
        return result;
    }
}
```

Also apparently the block size can use suffixes like `kB`.  There should be some code that can help in `uucore` or one of the other utils that deals with that sort of stuff.  If you don't want to implement that in this pull request then please open an issue so we can keep track 😄.

**Comment by Arcterus** [comment]
You should probably just squash the last two commits into one.  Seems good other than that though.

**Comment by bootandy** [comment]
last 2 commits squashed @Arcterus

**Comment by Arcterus** [comment]
Thanks!
