### PR TITLE
stat: improve handling of stdin/fifo (fix #3485)

### LINKED ISSUE #3485: stat: panic on calling with `-` and an open pipe/fifo
The workaround from https://github.com/uutils/coreutils/pull/3280 does not distinguish between calling `stat -` with an open pipe/fifo or without.

GNU stat:
```bash
 $ stat -
  File: -
  Size: 0               Blocks: 0          IO Block: 1024   character special file
```
```bash
$ echo | stat -
  File: -
  Size: 0               Blocks: 0          IO Block: 4096   fifo
```
uu_stat:
```bash
$ target/debug/stat -
  File: /dev/pts/7
  Size: 0               Blocks: 0          IO Block: 1024   character special file
```
```bash
$ echo | target/debug/stat -
thread 'main' panicked at 'unable to canonicalize /dev/stdin: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/uu/stat/src/stat.rs:482:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by jhscheer**
* fix https://github.com/uutils/coreutils/issues/3485
* improve the workaround from #3280
* add tests

### CODE REVIEW

File: src/uu/stat/src/stat.rs [hunk 1]
```diff
@@ -471,24 +473,10 @@ impl Stater {
     }
 
     fn new(matches: &ArgMatches) -> UResult<Self> {
-        let mut files: Vec<String> = matches
+        let files = matches
             .values_of(ARG_FILES)
```
Comment (tertsdiepraam) [inline src/uu/stat/src/stat.rs:477]: If we're using `OsString` anyway, this can be `.values_of_os(ARG_FILES)`, right?

**Review by tertsdiepraam — COMMENTED** [review]
Cool!

File: src/uu/stat/src/stat.rs (hunk 1 above)
Comment (jhscheer) [reply src/uu/stat/src/stat.rs]: Thanks for making me aware of this. I changed it.
