### PR TITLE
hashsum: test b3sum::test_nonames for real

### LINKED ISSUE #3818: Test `test_hashsum::b3sum::test_nonames` for real
Improved in https://github.com/uutils/coreutils/pull/3816 but not enough as it isn't testing it. This patch runs it:

```
diff --git a/tests/by-util/test_hashsum.rs b/tests/by-util/test_hashsum.rs
index 06d039d59..7a87125c8 100644
--- a/tests/by-util/test_hashsum.rs
+++ b/tests/by-util/test_hashsum.rs
@@ -34,7 +34,7 @@ macro_rules! test_digest {
         fn test_nonames() {
             let ts = TestScenario::new("hashsum");
             // EXPECTED_FILE has no newline character at the end
-            if DIGEST_ARG == "b3sum" {
+            if DIGEST_ARG == "--b3sum" {
                 // Option only available on b3sum
                 assert_eq!(format!("{0}\n{0}\n", ts.fixtures.read(EXPECTED_FILE)),
                        ts.ucmd().arg(DIGEST_ARG).arg(BITS_ARG).arg("--no-names").arg("input.txt").arg("-").pipe_in_fixture("input.txt")

```

But fails with:
```

---- test_hashsum::b3sum::test_nonames stdout ----
current_directory_resolved: 
open: /tmp/.tmpc8CYCJ/b3sum.expected
open: /tmp/.tmpc8CYCJ/input.txt
run: /home/sylvestre/dev/debian/coreutils/target/debug/coreutils hashsum --b3sum --bits=256 --no-names input.txt -
thread 'test_hashsum::b3sum::test_nonames' panicked at 'assertion failed: `(left == right)`
  left: `"a1a55887535397bf461902491c8779188a5dd1f8c3951b3d9cf6ecba194e87b0\na1a55887535397bf461902491c8779188a5dd1f8c3951b3d9cf6ecba194e87b0\n"`,
 right: `"a1a55887535397bf461902491c8779188a5dd1f8c3951b3d9cf6ecba194e87b0  input.txt\na1a55887535397bf461902491c8779188a5dd1f8c3951b3d9cf6ecba194e87b0  -\n"`', /home/sylvestre/dev/debian/coreutils/tests/by-util/test_hashsum.rs:83:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

To run it:
```
cargo test test_hashsum::b3sum::test_nonames      
```

### PR DESCRIPTION
**Pull request by huijeong-kim**
Resolves #3818 

Signed-off-by: Huijeong Kim <herehuijeong@gmail.com>

### CODE REVIEW

File: src/uu/hashsum/src/hashsum.rs [hunk 1]
```diff
@@ -297,7 +297,7 @@ pub fn uumain(mut args: impl uucore::Args) -> UResult<()> {
     };
     let check = matches.contains_id("check");
     let tag = matches.contains_id("tag");
-    let nonames = if binary_name == "b3sum" {
+    let nonames = if binary_name == "b3sum" || matches.try_contains_id("b3sum").is_ok() {
```
Comment (tertsdiepraam) [inline src/uu/hashsum/src/hashsum.rs:300]: I think checking whether it is `Ok` is not enough. `try_contains_id` returns `Ok` when the `id` is valid (i.e. there is an `Arg` in `Command` with that `id`). We also need it to be present, so `Ok(true)`, otherwise `nonames` can be true when an algorithm other than `b3sum` is used (I put a `dbg!(nonames)` on line 305):

```
❯ cargo run -- hashsum --b2sum --no-names
[src/uu/hashsum/src/hashsum.rs:305] nonames = true
```

Note that we can assume that `b3sum` is a valid id, so `matches.contains_id("b3sum)` should be good enough.

Comment (huijeong-kim) [reply src/uu/hashsum/src/hashsum.rs:300]: I used `try_contains_id` because it panics in test_hashsum::test_check_sha1 due to 
```
thread 'test_hashsum::test_check_sha1' panicked at 'Command was expected to succeed.
stdout =
 stderr = thread 'main' panicked at 'Mismatch between definition and access of `b3sum`. Unknown argument or group id.  Make sure you are using the argument id and not the short or long flags
```

I thought about using `try_contains_id("b3sum").unwrap_or(false)`, but when I run `cargo run -- hashsum --b2sum --no-names` `nonames` is false and it's unexpected.

If `nonames` should be set for all other algorithms according to the `no-names` argument, how about this?

```
let nonames = matches.try_contains_id("no-names").
```

Comment (tertsdiepraam) [reply src/uu/hashsum/src/hashsum.rs:300]: Oh I see! try_contains is correct then but we need `matches.try_contains("b3sum") == Some(true)`.

Comment (huijeong-kim) [reply src/uu/hashsum/src/hashsum.rs:300]: Okay! Thanks! I'll work on it 😃👍🏻

File: src/uu/hashsum/src/hashsum.rs [hunk 2]
```diff
@@ -297,7 +297,7 @@ pub fn uumain(mut args: impl uucore::Args) -> UResult<()> {
     };
     let check = matches.contains_id("check");
     let tag = matches.contains_id("tag");
-    let nonames = if binary_name == "b3sum" || matches.try_contains_id("b3sum").is_ok() {
+    let nonames = if binary_name == "b3sum" || matches.try_contains_id("b3sum").unwrap_or(false) {
```
Comment (huijeong-kim) [inline src/uu/hashsum/src/hashsum.rs:300]: I used unwrap_or(false) as the return value of try_contains_id is Result<bool, MatchesError>

**Comment by tertsdiepraam** [comment]
Okay, so a funny thing happened because we merged clap 4. Now, `--b3sum` is marked with `ArgAction::SetTrue` and clap has the (questionable) behaviour `contains_id` is always true for a flag with `SetTrue`. So this happens again:

```bash
❯ cargo run -- hashsum --b2sum --no-names
[src/uu/hashsum/src/hashsum.rs:305] nonames = true
```

But, that might not be a problem, because we don't actually need `nonames` to be `false` for the other algorithms, we just don't care (although we might want to show an error that it's useless with other algorithms). What we actually about is that we can only check the flag if `--no-names` is registered as an argument (otherwise clap panics). Your solution does this correctly, however, it is not quite obvious what it actually checks. Therefore, I propose the following:

```rust
    let nonames = *matches.get_one("no-names").unwrap_or(&false);
```

Sorry for introducing the weird behaviour with clap and changing my mind about this :)

**Comment by huijeong-kim** [comment]
Oh.. that's weird. No problem, I will change as you suggested!

File: src/uu/hashsum/src/hashsum.rs [hunk 3]
```diff
@@ -276,11 +276,7 @@ pub fn uumain(mut args: impl uucore::Args) -> UResult<()> {
     };
     let check = matches.get_flag("check");
     let tag = matches.get_flag("tag");
-    let nonames = if binary_name == "b3sum" {
-        matches.get_flag("no-names")
-    } else {
-        false
-    };
+    let nonames = *matches.try_get_one("no-names").unwrap_or(Some(&false)).unwrap();
```
Comment (huijeong-kim) [inline src/uu/hashsum/src/hashsum.rs:279]: While I change my code, I found another weird behavior of clap. 
`get_one("no-names")` panics inside the function call if the flag not exist (in test_check_sha1 test), so that it can't handle `unwrap_or()`.

So I used `try_get_one()` and it returns `Result<Option<T>, MatchesError>`. That's why I have two unwrap here..

Comment (tertsdiepraam) [reply src/uu/hashsum/src/hashsum.rs:279]: Oh yeah it should have been `try_get_one`! I made a mistake indeed :)

**Comment by sylvestre** [comment]
@tertsdiepraam are we good here? thanks

**Comment by tertsdiepraam** [comment]
Yeah, looks good! Thanks @huijeong-kim!

**Comment by huijeong-kim** [comment]
Thank you for your kind review  @tertsdiepraam 😄👍

**Comment by sylvestre** [comment]
Terts is the best! ;)

**Comment by tertsdiepraam** [comment]
That's very kind 😄 Some GNU tests seem to be failing when after merged this: https://github.com/uutils/coreutils/actions/runs/3302752256. I can't reproduce the failure locally though. I'll check whether the issue persists in other runs.

**Comment by huijeong-kim** [comment]
Oh it fails 🥲 I'll try to find out something from logs..!
