### PR TITLE
chown: change first file with --reference

### LINKED ISSUE #1309: Chown fails to modify first file when using --reference
When using chown with --reference the first file is not changed due to an unconditional removal of the first argument.

Example:
```
$ ls -l
total 20
-rw-rw-r--. 1 mmillin mmillin   352 Sep  1 18:35 Cargo.toml
-rw-rw-r--. 1 mmillin mmillin 14518 Oct 29 05:25 chown.rs
-rw-rw-r--. 1 mmillin wheel       0 Oct 29 05:26 test
-rw-rw-r--. 1 mmillin wheel       0 Oct 29 05:26 test2

$ ../../target/debug/chown --reference chown.rs test test2

$ ls -l                                                                 
total 20                                                                
-rw-rw-r--. 1 mmillin mmillin   352 Sep  1 18:35 Cargo.toml    
-rw-rw-r--. 1 mmillin mmillin 14518 Oct 29 05:25 chown.rs     
-rw-rw-r--. 1 mmillin wheel       0 Oct 29 05:26 test      
-rw-rw-r--. 1 mmillin mmillin     0 Oct 29 05:26 test2  
```

### PR DESCRIPTION
**Pull request by dvrax**
Fixes #1309

### CODE REVIEW

File: src/chown/chown.rs [hunk 1]
```diff
@@ -169,8 +169,11 @@ pub fn uumain(args: Vec<String>) -> i32 {
             }
         }
     }
+    let using_ref = matches.opt_str("reference").is_some();
     let mut files = matches.free;
-    files.remove(0);
+    if !using_ref {
```
Comment (Arcterus) [inline src/chown/chown.rs]: It would probably make more sense to move this into the `if` body above.

Comment (dvrax) [reply src/chown/chown.rs]: I've done this, although it looks a bit messy as I had to work around mutably borrowing `matches.free` too early.

**Comment by Arcterus** [comment]
Thanks!
