### PR TITLE
chmod: change permissions for files present even when there is a missing file

### LINKED ISSUE #4355: chmod fails to change permissions if files missing
This behaviour is different to the GNU utilities:
Tested with coreutils ver. 0.0.17

In a directory that contains only .py files (and therefore no .sh files)
chmod u+x *.sh *.py

Rust reports: chmod: cannot access '*.sh': No such file or directory
and does NOT change the execute bit on any files.

gnu reports: /usr/bin/chmod: cannot access '*.sh': No such file or directory
but DOES change the permissions of existing .py files

### PR DESCRIPTION
**Pull request by dmatos2012**
Fixes #4355. Basically now it allows to set permissions for files present, and ignoring the missing files by just printing a "warning" that the particular file could not be found.

### CODE REVIEW

File: src/uu/chmod/src/chmod.rs [hunk 1]
```diff
@@ -206,13 +207,23 @@ impl Chmoder {
...
-                            "cannot access {}: No such file or directory",
+                    if files.len() == 1 {
+                        return Err(USimpleError::new(
+                            1,
+                            format!(
+                                "cannot access {}: No such file or directory",
+                                filename.quote()
+                            ),
+                        ));
+                    } else {
```
Comment (tertsdiepraam) [inline src/uu/chmod/src/chmod.rs:218]: I don't think we need this distinction if we `continue` anyway. You can get both cases with something like this:
```rust
show!(USimpleError::new(
    1,
    "cannot access {}: No such file or directory",
    format!(
        "cannot access {}: No such file or directory",
        filename.quote()
    ),
));
continue;
```

File: src/uu/chmod/src/chmod.rs [hunk 2]
```diff
@@ -206,13 +207,23 @@ impl Chmoder {
...
+                            uucore::util_name(),
                             filename.quote()
-                        ),
-                    ));
+                        );
+                        set_exit_code(1);
+                        continue;
+                    }
                 }
                 return Err(ExitCode::new(1));
```
Comment (tertsdiepraam) [inline src/uu/chmod/src/chmod.rs:228]: Have you checked the behaviour for these other `return`s? They might also not exit in GNU.

File: src/uu/chmod/src/chmod.rs (hunk 1 above)
Comment (dmatos2012) [reply src/uu/chmod/src/chmod.rs]: Oh yeah, of course :see_no_evil: thanks for pointing it out!

File: src/uu/chmod/src/chmod.rs [hunk 3]
```diff
@@ -195,21 +195,24 @@ impl Chmoder {
...
                     );
                     if !self.quiet {
-                        return Err(USimpleError::new(
+                        show!(USimpleError::new(
                             1,
                             format!("cannot operate on dangling symlink {}", filename.quote()),
                         ));
                     }
+                    set_exit_code(1);
+                    continue;
```
Comment (tertsdiepraam) [inline src/uu/chmod/src/chmod.rs:204]: Not something to fix for this PR, but we might be able to build something like this in `uucore` maybe some verbosity level that determines whether an error is printed and always sets the exit code.

Comment (tertsdiepraam) [inline src/uu/chmod/src/chmod.rs:204]: This is quite subjective, but in my opinion it becomes clearer if we remove these 2 lines. It simplifies the control flow a bit because there's only one `continue` in that case.

File: src/uu/chmod/src/chmod.rs [hunk 4]
```diff
@@ -195,21 +195,24 @@ impl Chmoder {
...
                         1,
                         format!(
                             "cannot access {}: No such file or directory",
                             filename.quote()
-                        ),
+                        )
                     ));
                 }
-                return Err(ExitCode::new(1));
+                set_exit_code(1);
```
Comment (tertsdiepraam) [inline src/uu/chmod/src/chmod.rs:214]: Could you add a small comment explaining that this is necessary for the case where `self.quiet` is `true`?

**Review by tertsdiepraam — COMMENTED** [review]
Looking good! I have 2 more small suggestions.

**Comment by tertsdiepraam** [comment]
> Is the difference there expected ? I see previous tests covered that, but I dont see the same output on GNU.

I have no clue 😄 But that might be something we need to fix. Maybe you could look at the commit/PR that introduced that error for context.

File: src/uu/chmod/src/chmod.rs (hunk 3 above)
Comment (dmatos2012) [reply src/uu/chmod/src/chmod.rs]: Yeah you are for sure 100% right, I  guess i duplicated it while looking at some many `if` and `else if`. But thanks for noticing it!

File: src/uu/chmod/src/chmod.rs (hunk 4 above)
Comment (dmatos2012) [reply src/uu/chmod/src/chmod.rs:213]: I just added it because noticed GNU did it :stuck_out_tongue: (but added the comment anyway)

File: src/uu/chmod/src/chmod.rs (hunk 3 above)
Comment (dmatos2012) [reply src/uu/chmod/src/chmod.rs]: Yeah, I think for this case, it would simplify the need for the `if self.quiet`s  and setting the exit code separately when quiet is `true`. 

I thought of two options, 
1.
```
#[macro_export]
macro_rules! show_verbose_level(
    ($err:expr, $verbose: expr) => ({
        let e = $err;
        $crate::error::set_exit_code(e.code());
        if $verbose == 1 {
            eprintln!("{}: {}", $crate::util_name(), e);
        }
    })
);
```

2. 
```

#[macro_export]
macro_rules! show_verbose_level(
    ($err:expr) => ({
        let e = $err;
        $crate::error::set_exit_code(e.code());
        eprintln!("{}: {}", $crate::util_name(), e);
    });
    ($err:expr, $verbose: expr) => ({
        let e = $err;
        $crate::error::set_exit_code(e.code());
        if $verbose == 1 {
            eprintln!("{}: {}", $crate::util_name(), e);
        }
    })
);
```

The benefit of 2) is that I guess there is no need to modify any of the existing `show!()` macros, but I guess 1) makes more sense, while we provide just 1 for verbose and 0 for non-verbose. 

This might make not too much sense, but I think thats sort of what you mean. The `macro!` name would have to show because a `show!()` without showing anything doesnt seem like the right name.

File: src/uu/chmod/src/chmod.rs (hunk 4 above)
Comment (tertsdiepraam) [reply src/uu/chmod/src/chmod.rs:213]: Oh yeah I understand you're just matching the behaviour! I was thinking a comment along these lines:
```
// GNU exits with exit code 1 even if -q or --quiet are passed
// So we set the exit code, because it hasn't been set yet if `self.quiet` is true.
```

Comment (dmatos2012) [reply src/uu/chmod/src/chmod.rs:214]: Ah, my bad. Basically copy pasted your comment on the code. This should have been a straightforward PR, yet I have managed to make it difficult :P

Comment (tertsdiepraam) [reply src/uu/chmod/src/chmod.rs:214]: No worries!

**Review by tertsdiepraam — APPROVED** [review]

**Comment by tertsdiepraam** [comment]
Nice! This can be merged once the CI passes.
