### PR TITLE
fmt: value of minlength should not be negative

### LINKED ISSUE #6354: fmt: Crashes for some inputs (?)
```console
$ yes a | head -n50 > 50a.txt
$ fmt -w 75 -g 10 50a.txt 
a a a a a a
a a a a a a a
a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a
$ cargo run -q fmt -w 75 -g 10 50a.txt 
thread 'main' panicked at 'attempt to subtract with overflow', src/uu/fmt/src/linebreak.rs:242:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
a[$? = 101]
```

I have no idea why it crashes here. It seems to crash for any "goal" of 37 or less.

Might be related to #5162, might not.

### PR DESCRIPTION
**Pull request by ahmadabd**
closes #6354

### CODE REVIEW

**Comment by cakebaker** [comment]
Can you please add a test so we don't regress in the future?

**Comment by ahmadabd** [comment]
> Can you please add a test so we don't regress in the future?

Done

File: tests/by-util/test_fmt.rs [hunk 1]
```diff
@@ -130,6 +130,15 @@ fn test_fmt_goal_bigger_than_default_width_of_75() {
     }
 }
 
+#[test]
+fn test_fmt_goal_too_small_to_check_negetive_minlength() {
```
Comment (cakebaker) [inline tests/by-util/test_fmt.rs:134]:
```suggestion
fn test_fmt_goal_too_small_to_check_negative_minlength() {
```

File: src/uu/fmt/src/linebreak.rs [hunk 2]
```diff
@@ -239,7 +239,11 @@ fn find_kp_breakpoints<'a, T: Iterator<Item = &'a WordInfo<'a>>>(
     let mut next_active_breaks = vec![];
 
     let stretch = args.opts.width - args.opts.goal;
-    let minlength = args.opts.goal - stretch;
+    let minlength = if args.opts.goal >= stretch {
+        args.opts.goal - stretch
+    } else {
+        DEFAULT_GOAL_TO_WIDTH_RATIO
```
Comment (cakebaker) [inline src/uu/fmt/src/linebreak.rs:245]: I think this is incorrect because `DEFAULT_GOAL_TO_WIDTH_RATIO` represents a ratio, 93% in this case, and not an absolute value.

Comment (ahmadabd) [reply src/uu/fmt/src/linebreak.rs:245]: I dont know what should be value of -g when minlength is negetive

Comment (BenWiederhake) [reply src/uu/fmt/src/linebreak.rs:245]: How about using 1? The old code seems to use `stretch` as a guess for how much wiggle-room there is. And if `minlength` has to be at least 1 anyway, well, then just use 1 as the minimum value.

````rust
    // Would like to write (args.opts.goal - stretch).max(1), but that can underflow the unsigned integer:
    let minlength = args.opts.goal.max(stretch + 1) - stretch;

Comment (cakebaker) [reply src/uu/fmt/src/linebreak.rs:245]: Sounds reasonable.

Comment (ahmadabd) [reply src/uu/fmt/src/linebreak.rs]: Yes sounds reasonable

File: tests/by-util/test_fmt.rs [hunk 3]
```diff
@@ -130,6 +130,15 @@ fn test_fmt_goal_bigger_than_default_width_of_75() {
     }
 }
 
+#[test]
+fn test_fmt_goal_too_small_to_check_negative_minlength() {
+    for param in ["-g", "--goal"] {
+        new_ucmd!()
+            .args(&["one-word-per-line.txt", "--width=75", param, "10"])
+            .succeeds();
```
Comment (BenWiederhake) [inline tests/by-util/test_fmt.rs:138]: Also check that the output is sane:
```suggestion
            .succeeds()
            .stdout_is("this is a file with one word per line\n");
```

**Review by BenWiederhake — APPROVED** [review]
LGTM

**Comment by BenWiederhake** [comment]
Remaining failure is #6275 and #6333
