### PR TITLE
numfmt: fix #11935 --invalid=warn/ignore/fail ignores mode when rejecting scientific notation

### LINKED ISSUE #11935: numfmt: `--invalid=warn/ignore/fail` ignores mode when rejecting scientific notation
## Summary

Follow-on to #11655. Scientific-notation inputs are now correctly rejected in the default `--invalid=abort` mode, but the rejection path bypasses `--invalid=warn/ignore/fail` handling — uutils halts after the first invalid value and exits 2 regardless of the requested mode, while GNU prints the bad value, continues with the remaining inputs, and exits 0 for `warn`/`ignore`.

Regular invalid inputs (random garbage strings) behave correctly; only the scientific-notation rejection path is broken.

Found by `fuzz_numfmt`.

## Reproduction

```console
$ LC_ALL=C /usr/bin/numfmt --invalid=warn 100 1e5 200
100
numfmt: invalid suffix in input: '1e5'
1e5
200
(rc=0)

$ LC_ALL=C target/debug/numfmt --invalid=warn 100 1e5 200
100
numfmt: invalid suffix in input: '1e5'
(rc=2)
```

Same divergence for `--invalid=ignore` and `--invalid=fail` (for `fail`, both should exit 2 but GNU still prints all three numbers).

Sanity check — other invalid inputs handle `--invalid=warn` correctly:

```console
$ numfmt --invalid=warn 100 garbage 200   # both print all three, rc=0
```

### PR DESCRIPTION
**Pull request by Devel08**
This PR resolves #11935.

When I fixed the issue where scientific notation is accepted, but it shouldn't be, I manually returned an error instead of letting "result" to do that. I fixed that and I apologize.
Ran cargo fmt and cargo test.

### CODE REVIEW

**Comment by cakebaker** [comment]
Can you please add a test to `tests/by_util/test_numfmt.rs` to ensure we don't regress in the future? Thanks.

**Comment by Devel08** [comment]
@cakebaker Sure

File: tests/by-util/test_numfmt.rs [hunk 1]
```diff
@@ -1513,3 +1513,12 @@ fn test_locale_c_uses_period() {
...
         .stdout_is("1.5K\n");
 }
+
+// https://github.com/uutils/coreutils/issues/11935
+// the rejection path bypasses --invalid=warn/ignore/fail handling
+#[test]
+fn test_ignores_invalid_mode_issue11935() {
+    new_ucmd!()
+        .args(&["--invalid=warn", "100 1e5 200"])
+        .succeeds();
```
Comment (cakebaker) [inline tests/by-util/test_numfmt.rs]: I would also check for the expected output because in #11935 some data was missing in the output.

Comment (Devel08) [reply tests/by-util/test_numfmt.rs]: Alright, should I skip CI though? I read somewhere that it is pricey

Comment (cakebaker) [reply tests/by-util/test_numfmt.rs]: No, don't worry about the CI :)

**Comment by cakebaker** [comment]
Thanks!
