### PR TITLE
tr: process octal escape sequences

### LINKED ISSUE #1817: tr does not handle escape sequences correct
autoconf relies on the following snippet to generate a CRLF character:

```shell
echo X | tr X '\015'
```

which is broken in uutils-coreutils and returns a ``0``:

uutils-tr
```shell
$ echo X | tr X '\015' | /bin/xxd
00000000: 300a                                     0.
```

gnus tr:
```shell
echo X | tr X '\015' | /bin/xxd
00000000: 0d0a                                     ..
```

### PR DESCRIPTION
**Pull request by drocco007**
closes #1817

### CODE REVIEW

File: src/uu/tr/src/expand.rs [hunk 1]
```diff
@@ -14,17 +14,43 @@ use std::cmp::min;
...
-        'f' => 0x0cu8 as char,
-        'v' => 0x0bu8 as char,
-        'n' => '\n',
-        'r' => '\r',
-        't' => '\t',
-        _ => c,
+fn parse_sequence(s: &str) -> (char, usize) {
+    let c = s.chars().next().expect("invalid escape: empty string");
+
+    if ('0'..='7').contains(&c) {
```
Comment (sylvestre) [inline src/uu/tr/src/expand.rs:27]: error here

Comment (drocco007) [reply src/uu/tr/src/expand.rs]: It should be fixed now. :)

**Comment by sylvestre** [comment]
Kudos for the coverage :)
 62.42% (+0.12%)
