### PR TITLE
cksum: Fix #6375 and un-ignore now passing tests

### LINKED ISSUE #6375: " --binary --tag --untagged --binary" should display the asterisk
This code only considers the *first* occurrence of each flag, which leads to no meaningful behavior, because all subsequent flags get ignored. This is demonstrably wrong:

```console
$ cargo run -q --features cksum cksum -a md5 --binary --tag --untagged --binary README.md 
e5773576fc75ff0f8eba14f61587ae28  README.md
$ cksum -a md5 --binary --tag --untagged --binary README.md 
e5773576fc75ff0f8eba14f61587ae28 *README.md
```

_Originally posted by @BenWiederhake in https://github.com/uutils/coreutils/pull/6256#discussion_r1592286500_

### PR DESCRIPTION
**Pull request by RenjiSann**
Fixes #6375, and 2 other ignored tests

### CODE REVIEW

File: tests/by-util/test_cksum.rs [hunk 1]
```diff
@@ -602,7 +602,6 @@ fn test_reset_binary() {
         .stdout_contains("d41d8cd98f00b204e9800998ecf8427e  ");
 }
 
-#[ignore = "issue #6375"]
 #[test]
```
Comment (cakebaker) [inline tests/by-util/test_cksum.rs:605]: I guess the comment at the end of the function (line 621) is no longer needed?

Comment (RenjiSann) [reply tests/by-util/test_cksum.rs:605]: It is not indeed, thanks for catching this !

File: src/uucore/src/lib/features/checksum.rs [hunk 2]
```diff
@@ -710,6 +710,11 @@ fn identify_algo_name_and_length(
     }
 
     let bytes = if let Some(bitlen) = line_info.algo_bit_len {
+        if algorithm != ALGORITHM_OPTIONS_BLAKE2B {
+            // An invalid "bits" part was given to the regex
+            // eg: MD5-128 (foo.txt) = fffffffff
+            return None;
+        }
         if bitlen % 8 != 0 {
             // The given length is wrong
```
Comment (cakebaker) [inline src/uucore/src/lib/features/checksum.rs:719]: Wouldn't it be easier to read if you check for the positive case? Something like
```rust
if algorithm == ALGORITHMS_OPTIONS_BLAKE2B && bitlen % 8 == 0 {
    Some(bitlen / 8)
} else {
    return None;
}
```

File: tests/by-util/test_cksum.rs (hunk 1 above)
Comment (RenjiSann) [reply tests/by-util/test_cksum.rs:605]: done :+1:

File: src/uu/cksum/src/cksum.rs
Comment (cakebaker) [inline src/uu/cksum/src/cksum.rs:1]: Much cleaner than the previous approach :)

File: src/uucore/src/lib/features/checksum.rs (hunk 2 above)
Comment (RenjiSann) [reply src/uucore/src/lib/features/checksum.rs]: I merged both conditions in a single if statement, but I find it is more understandable to check for the negative case. I've also slightly refactored the `identify_algo_name_and_length` function to make it return an error instead of an option. It helps making the difference between the error case and the case where no bit size was given.

WDYT ?

File: src/uucore/src/lib/features/checksum.rs [hunk 3]
```diff
@@ -710,6 +710,11 @@ fn identify_algo_name_and_length(
     }
 
     let bytes = if let Some(bitlen) = line_info.algo_bit_len {
+        if algorithm != ALGORITHM_OPTIONS_BLAKE2B {
+            // An invalid "bits" part was given to the regex
```
[the remark this answers is not in the document]
Comment (RenjiSann) [reply src/uucore/src/lib/features/checksum.rs]: fair enough, I'll rephrase this

File: src/uu/cksum/src/cksum.rs
Comment (RenjiSann) [reply src/uu/cksum/src/cksum.rs:1]: Yup, it's smaller, only iterates once, and is actually the expected behavior :)

**Comment by cakebaker** [comment]
Thanks!
