### PR TITLE
fix(numfmt):fix precision loss for large numbers in #11654

### LINKED ISSUE #11654: numfmt: large integers lose precision (f64 rounding) vs GNU
## Summary

`numfmt` rounds large integers to the nearest representable `f64`, while GNU `numfmt` preserves the exact value when no scaling is needed.

Found by `fuzz_numfmt`.

## Reproduction

```console
$ /usr/bin/numfmt --from=iec 9153396227555392131
9153396227555392131

$ target/debug/numfmt --from=iec 9153396227555392131
9153396227555392512
```

`9153396227555392131` is greater than `2^53`, so it can't be represented exactly as `f64`; uutils appears to parse the input through `f64` and loses the last few digits.

### PR DESCRIPTION
**Pull request by THEMIScale**
Fixes #11654

- Add `numeric.rs` to preserve precision for large integers
- Modify related functions in `format.rs`
- Adjust some float related test cases in `format.rs`
- Large integer values are now accurate
- Float precision remains limited by `f64` and is worse than GNU
- `cargo test --features` unix passes for numfmt

### CODE REVIEW

**Comment by THEMIScale** [comment]
There's a remaining problem here:
```
┌──(kali㉿KaliOnHP)-[~/coreutils]
└─$ ./target/debug/numfmt --from=iec 915339622.7555392131
915339622.7555391788

┌──(kali㉿KaliOnHP)-[~/coreutils]
└─$ /usr/bin/numfmt --from=iec 915339622.7555392131
915339622.7555392131
```
The `f64` is not as precise as `long double`.
Even to igore the case, GNU numfmt still has an error when number is out of limitation(which WE don't):
```
┌──(kali㉿KaliOnHP)-[~/coreutils]
└─$ ./target/debug/numfmt --from=iec 915339622.7555392723748798127937497128934
915339622.7555392980575561523437500000000

┌──(kali㉿KaliOnHP)-[~/coreutils]
└─$ /usr/bin/numfmt --from=iec 915339622.7555392723748798127937497128934
numfmt: 值或精度过大，无法输出："9.1534e+08/31"（请考虑使用 --to）
```
If anyone see this, pls NEW an ISSUE if it is reasonable, I'm worrying that this PR won't be merged, thus my environment is not relyable for now.

**Comment by cakebaker** [comment]
I don't know if you have seen it: a few `numfmt` tests fail in the CI.

**Comment by THEMIScale** [comment]
Yeah, I just woke up and correct it.

**Comment by THEMIScale** [comment]
will the fails be a problem? How can I run these failed checks again, I guess it might not be my problem. 🤔 @cakebaker

**Comment by cakebaker** [comment]
> will the fails be a problem?

No, you can ignore them, they are unrelated.

File: src/uu/numfmt/src/numeric.rs
Comment (cakebaker) [inline src/uu/numfmt/src/numeric.rs:1]: Can you please add the file header we use in the other files?

File: src/uu/numfmt/src/numeric.rs [hunk 1]
```diff
@@ -0,0 +1,26 @@
+// This file is written to solve #11654
+// This file is related to all code changes for GitHub Issue #11654.
```
Comment (cakebaker) [inline src/uu/numfmt/src/numeric.rs]: This sentence is more or less the same as the previous sentence, so my suggestion is to remove it.
```suggestion
```

File: src/uu/numfmt/src/numeric.rs
Comment (THEMIScale) [reply src/uu/numfmt/src/numeric.rs:1]: Done.
But I dont know what to write for ` spell-checker`, so I use the one in `format.rs`:
`// spell-checker:ignore powf seps`

Comment (cakebaker) [reply src/uu/numfmt/src/numeric.rs:1]: The line is unnecessary in this case. It's only needed when the spell checker complains about words it doesn't know.

File: src/uu/numfmt/src/format.rs [hunk 2]
```diff
@@ -479,14 +510,43 @@ fn consider_suffix(
         Ok((v, Some((suffixes[i - 1], with_i))))
     }
 }
```
Comment (cakebaker) [inline src/uu/numfmt/src/format.rs:509]: A detail: I would add an empty line as a separator between the two functions.
```suggestion
}

```

File: src/uu/numfmt/src/format.rs [hunk 3]
```diff
@@ -480,13 +511,43 @@ fn consider_suffix(
...
 
+fn try_format_exact_int_without_output_scaling(
```
Comment (cakebaker) [inline src/uu/numfmt/src/format.rs]: It looks like there is a mismatch between the function name and what the function does: the function name contains "without_output_scaling" whereas the function does some scaling. Maybe you can simply drop "without_output_scaling" from the name?

File: src/uu/numfmt/src/format.rs [hunk 4]
```diff
@@ -364,7 +370,27 @@ fn remove_suffix(i: f64, s: Option<Suffix>, u: Unit) -> Result<f64> {
     }
 }
 
-fn transform_from(s: &str, opts: &TransformOptions, options: &NumfmtOptions) -> Result<f64> {
+fn try_scale_exact_int_without_suffix(
+    value: ParsedNumber,
+    from_unit: usize,
+    had_no_suffix: bool,
```
Comment (cakebaker) [inline src/uu/numfmt/src/format.rs]: I would use a name without negation (and switch its meaning) to avoid the double negation on line 378.

File: src/uu/numfmt/src/format.rs (hunk 3 above)
Comment (THEMIScale) [reply src/uu/numfmt/src/format.rs]: The function can be named more precisly afer `try_format_exact_int_without_suffix_scaling`, is it Ok?

File: src/uu/numfmt/src/format.rs (hunk 4 above)
Comment (THEMIScale) [reply src/uu/numfmt/src/format.rs]: Yes, that is a problem. I'm thinking to verify `had_no_suffix` in `transform_from()` , and change name of the function `try_scale_exact_int_without_suffix`  into `try_scale_exact_int_with_from_unit`.

File: src/uu/numfmt/src/format.rs (hunk 3 above)
Comment (cakebaker) [reply src/uu/numfmt/src/format.rs]: Yes, it's an improvement.

File: src/uu/numfmt/src/format.rs (hunk 4 above)
Comment (cakebaker) [reply src/uu/numfmt/src/format.rs]: Yes, that might be an option.

**Comment by THEMIScale** [comment]
can my code be merged now?

**Comment by cakebaker** [comment]
Thanks!
