### PR TITLE
`uniq`: pass remaining GNU tests

### LINKED ISSUE #3509: `test_uniq::gnu_tests` often fails with `failed to write to stdin of child: Broken pipe`
I stopped counting the number of time I saw this issue in the CI:

```
run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils uniq -D
Test 111
current_directory_resolved: 
run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils uniq -D -w1
Test 112
current_directory_resolved: 
run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils uniq -D -c
thread 'test_uniq::gnu_tests' panicked at 'failed to write to stdin of child: Broken pipe (os error 32)', tests/common/util.rs:1091:21
```

### PR DESCRIPTION
**Pull request by zhitkoff**
This PR makes the following changes in order to pass GNU `tests/uniq/uniq.pl`:
1. Rework of how obsolete options are handled - following the same approach as was done for `split`. Unfortunately it is not possible to implement it with just Clap for all required test cases
2. In support of (1) above - introduces a module `posix` with 3 constants and a single function to return POSIX version based on `_POSIX2_VERSION` environment variable. This module would be needed to add similar functionality to `sort`, `tail` and `touch` later on (most likely to finalize their GNU tests compliance as well)
3. Rework of how input is processed - switching from requiring UTF8 (and failing if input has invalid UTF8 characters) to processing raw `u8` bytes sequence. This is required to pass GNU `schar` test case and in general aligns the behavior with GNU version
4. Override some Clap errors to match the exact wording of error messages hardcoded into GNU tests
5. More tests to cover the changes

Should also fix #3509

### CODE REVIEW

File: src/uu/uniq/src/uniq.rs [hunk 1]
```diff
@@ -207,76 +220,345 @@ impl Uniq {
...
 
         write_line_terminator!(writer, line_terminator)
     }
 }
 
-fn get_line_string(io_line: io::Result<Vec<u8>>) -> UResult<String> {
-    let line_bytes = io_line.map_err_context(|| "failed to split lines".to_string())?;
-    String::from_utf8(line_bytes)
-        .map_err(|e| USimpleError::new(1, format!("failed to convert line to utf8: {e}")))
+fn opt_parsed(opt_name: &str, matches: &ArgMatches) -> UResult<Option<usize>> {
```
Comment (sylvestre) [inline src/uu/uniq/src/uniq.rs:240]: I think it can be simplify this way:

fn opt_parsed(opt_name: &str, matches: &ArgMatches) -> UResult<Option<usize>> {
    matches.get_one::<String>(opt_name)
        .map(|arg_str| {
            arg_str.parse::<usize>()
                .map_err(|e| match e.kind() {
                    IntErrorKind::PosOverflow => USimpleError::new(1, format!("{} is too large for {}", arg_str.maybe_quote(), opt_name)),
                    _ => USimpleError::new(1, format!("Invalid argument for {}: {}", opt_name, arg_str.maybe_quote())),
                })
                .map(Some)
        })
        .transpose()
}

File: src/uu/uniq/src/uniq.rs [hunk 2]
```diff
@@ -207,76 +220,345 @@ impl Uniq {
...
+/// `uniq -u20s4 file` would equal `uniq -u -f20 -s4 file`
+/// `uniq -D1w3 -3 file` would equal `uniq -D -f3 -w3 file`
+///
+/// Examples for obsolete skip chars option
+/// `uniq +1 file` would equal `uniq -s1 file`
+/// `uniq +1 -s2 file` would equal `uniq -s2 file`
+/// `uniq -s2 +3 file` would equal `uniq -s3 file`
+///
+fn handle_obsolete(args: impl uucore::Args) -> (Vec<OsString>, Option<usize>, Option<usize>) {
+    let mut skip_fields_old = None;
```
Comment (sylvestre) [inline src/uu/uniq/src/uniq.rs:276]: this is a lot of mut, can it be avoided?

File: src/uu/uniq/src/uniq.rs (hunk 1 above)
Comment (zhitkoff) [reply src/uu/uniq/src/uniq.rs:240]: well, not exactly - we need to convert one of the error cases (IntErrorKind::PosOverflow) from parse() into a value of usize::MAX , while passing all other errors on

File: src/uu/uniq/src/uniq.rs (hunk 2 above)
Comment (zhitkoff) [reply src/uu/uniq/src/uniq.rs:276]: can put them all in a struct and make the struct mutable ... might impact readability for helper functions signatures as some take full set and others only a subset

Comment (zhitkoff) [reply src/uu/uniq/src/uniq.rs:276]: tried to experiment with a struct - it looks less readable in my opinion, so would the code as it currently is do or should I investigate other options?

File: src/uu/uniq/src/uniq.rs (hunk 1 above)
Comment (sylvestre) [reply src/uu/uniq/src/uniq.rs:240]: ok, sorry

File: src/uu/uniq/src/uniq.rs (hunk 2 above)
Comment (sylvestre) [reply src/uu/uniq/src/uniq.rs:276]: nope, let's keep it :)
thanks for trying

**Comment by zhitkoff** [comment]
@sylvestre checking in to see if you have any other comments / suggestions on this PR

File: src/uucore/src/lib/mods/posix.rs [hunk 3]
```diff
@@ -0,0 +1,52 @@
+// This file is part of the uutils coreutils package.
```
Comment (sylvestre) [inline src/uucore/src/lib/mods/posix.rs:1]: if uniq is the only user of this function, isn't it a bit overkill to use have it in uucore?

File: src/uucore/src/lib/mods/posix.rs [hunk 4]
```diff
@@ -0,0 +1,52 @@
...
+//!
+//! Utilities that rely on this module:
+//! `sort` (TBD)
+//! `tail` (TBD)
+//! `touch` (TBD)
+//! `uniq`
+//!
+use std::env;
+
+pub const OBSOLETE: usize = 199209;
```
Comment (sylvestre) [inline src/uucore/src/lib/mods/posix.rs:26]: what about using an enum here?

**Comment by sylvestre** [comment]
Impressive work!

File: src/uucore/src/lib/mods/posix.rs (hunk 4 above)
Comment (zhitkoff) [reply src/uucore/src/lib/mods/posix.rs:26]: yes, initially i tried to implement it as an enum, but discarded in favor of these constants - unfortunately it is inconsistently checked in GNU, so was easier to implement this way for now. Might need to give it another try later on as these will be needed to fully cover GNU tests for at least 2 more utilities

Comment (sylvestre) [reply src/uucore/src/lib/mods/posix.rs:26]: ok, thanks
