### PR TITLE
mv: make UpdateMode public

### LINKED ISSUE #5427: mv: make 'UpdateMode' public for nushell
Related to the work done on making some `mv` api public in pull #5335, there was `UpdateMode` missing from that as its still private and therefore cannot build `Options {}` for nushell. 

The fix :
```diff
diff --git a/src/uu/mv/src/mv.rs b/src/uu/mv/src/mv.rs
index 9888389ae..02c856ce0 100644
--- a/src/uu/mv/src/mv.rs
+++ b/src/uu/mv/src/mv.rs
@@ -19,12 +19,12 @@ use std::os::unix;
 #[cfg(windows)]
 use std::os::windows;
 use std::path::{Path, PathBuf};
-pub use uucore::backup_control::BackupMode;
 use uucore::backup_control::{self, source_is_target_backup};
 use uucore::display::Quotable;
 use uucore::error::{set_exit_code, FromIo, UError, UResult, USimpleError, UUsageError};
 use uucore::fs::{are_hardlinks_or_one_way_symlink_to_same_file, are_hardlinks_to_same_file};
-use uucore::update_control::{self, UpdateMode};
+use uucore::update_control;
+pub use uucore::{backup_control::BackupMode, update_control::UpdateMode};
 use uucore::{format_usage, help_about, help_section, help_usage, prompt_yes, show};
 
 use fs_extra::dir::{
```
Right now I use that diff and it seems to work just fine from nushell, so the fix should be just fine I think :) 

I could also make a PR with these tiny changes if its ok so that nushell can use them

### PR DESCRIPTION
**Pull request by dmatos2012**
Fixes #5427.

### CODE REVIEW

File: src/uu/mv/src/mv.rs [hunk 1]
```diff
@@ -19,12 +19,12 @@ use std::os::unix;
...
 use std::os::windows;
 use std::path::{Path, PathBuf};
-pub use uucore::backup_control::BackupMode;
 use uucore::backup_control::{self, source_is_target_backup};
 use uucore::display::Quotable;
 use uucore::error::{set_exit_code, FromIo, UError, UResult, USimpleError, UUsageError};
 use uucore::fs::{are_hardlinks_or_one_way_symlink_to_same_file, are_hardlinks_to_same_file};
-use uucore::update_control::{self, UpdateMode};
+use uucore::update_control;
+pub use uucore::{backup_control::BackupMode, update_control::UpdateMode};
```
Comment (cakebaker) [inline src/uu/mv/src/mv.rs:27]:
```suggestion
// These are exposed for projects (e.g. nushell) that want to create an `Options` value, which
// requires these enums
pub use uucore::{backup_control::BackupMode, update_control::UpdateMode};
```

**Comment by cakebaker** [comment]
Thanks!
