### PR TITLE
Fix stderr output mv file into dir and dir into file where both are files

### LINKED ISSUE #5463: mv: misleading error messages for `mv file1 file2/` and `mv file1/ file2`
GNU `mv` shows a "Not a directory" error when adding a `/` to a filename:
```
$ touch file1 file2
$ mv file1 file2/
mv: cannot stat 'file2/': Not a directory
$ mv file1/ file2
mv: cannot stat 'file1/': Not a directory
```
uutils `mv`, on the other hand, shows an "Is a directory" error in one case and a "No such file or directory" error in the other case:
```
$ touch file1 file2
$ cargo run mv file1 file2/
mv: Is a directory (os error 21)
$ cargo run mv file1/ file2
mv: cannot stat 'file1/': No such file or directory
```

### PR DESCRIPTION
**Pull request by mickvangelderen**
Fixes #5463

The implementation of mv seems a bit messy, at least to a first time reader. My changes also feel a bit "band-aided" in. Glad we have a bunch of tests but the many repeated calls to `is_dir` and `symlink_metadata` and hard to understand flow may need to be addressed.

### CODE REVIEW

File: src/uu/mv/src/mv.rs [hunk 1]
```diff
@@ -103,6 +104,14 @@ static OPT_VERBOSE: &str = "verbose";
...
 static ARG_FILES: &str = "files";
 
+/// Returns true if the passed `path` ends with a path terminator.
+fn path_ends_with_terminator(path: &Path) -> bool {
+    path.as_os_str()
+        .as_bytes()
+        .last()
+        .map_or(false, |&byte| std::path::is_separator(byte as char))
+}
+
```
Comment (mickvangelderen) [inline src/uu/mv/src/mv.rs:114]: Is something like this already implemented somewhere?

File: src/uu/mv/src/error.rs [hunk 2]
```diff
@@ -4,19 +4,23 @@
...
     NoSuchFile(String),
+    CannotStatNotADirectory(String),
     SameFile(String, String),
     SelfSubdirectory(String),
     SelfTargetSubdirectory(String, String),
     DirectoryToNonDirectory(String),
     NonDirectoryToDirectory(String, String),
     NotADirectory(String),
     TargetNotADirectory(String),
+    FailedToAccessNotADirectory(PathBuf),
```
Comment (mickvangelderen) [inline src/uu/mv/src/error.rs:23]: Would it be better to store a `PathBuf` instead of a `String` for all error variants?

File: src/uu/mv/src/mv.rs (hunk 1 above)
Comment (cakebaker) [reply src/uu/mv/src/mv.rs:114]: I'm not aware of such a function and I couldn't fine one.

File: src/uu/mv/src/error.rs (hunk 2 above)
Comment (cakebaker) [reply src/uu/mv/src/error.rs:23]: Yes, I don't know why `String` is used. Though I think it is outside the scope of this PR.

Comment (cakebaker) [inline src/uu/mv/src/error.rs:23]: Why do you use two different errors?

File: src/uu/mv/src/mv.rs [hunk 3]
```diff
@@ -103,6 +104,14 @@ static OPT_VERBOSE: &str = "verbose";
 static OPT_PROGRESS: &str = "progress";
 static ARG_FILES: &str = "files";
 
+/// Returns true if the passed `path` ends with a path terminator.
+fn path_ends_with_terminator(path: &Path) -> bool {
+    path.as_os_str()
+        .as_bytes()
```
Comment (cakebaker) [inline src/uu/mv/src/mv.rs:110]: I guess you have seen the error that there is no `as_bytes` function under Windows?

File: src/uu/mv/src/error.rs (hunk 2 above)
Comment (mickvangelderen) [reply src/uu/mv/src/error.rs:23]: Don't they have different outputs?

File: src/uu/mv/src/mv.rs (hunk 3 above)
Comment (mickvangelderen) [reply src/uu/mv/src/mv.rs:110]: Lord no I haven't, thanks for pointing it out.

File: src/uu/mv/src/error.rs (hunk 2 above)
Comment (mickvangelderen) [reply src/uu/mv/src/error.rs:23]: Thinking the same, wanted to point it out though. Will revert to string for now.

Comment (cakebaker) [reply src/uu/mv/src/error.rs:23]: Hm, at least on my machine with Arch Linux GNU `mv` shows the same error in both cases (see the ticket). I could imagine it depends on the underlying system, so we can leave it.

Comment (mickvangelderen) [reply src/uu/mv/src/error.rs:23]: I'm on `Linux pop-os 6.5.6-76060506-generic #202310061235~1697396945~22.04~9283e32 SMP PREEMPT_DYNAMIC Sun O x86_64 x86_64 x86_64 GNU/Linux`.

File: src/uu/mv/src/mv.rs (hunk 3 above)
Comment (mickvangelderen) [reply src/uu/mv/src/mv.rs:110]: Any tips on how I can develop against windows on linux? I'm using vscode with rust-analyzer. Tried fiddling with the target and features but couldn't get what I wanted: for the IDE to think that I was on windows.

Comment (mickvangelderen) [reply src/uu/mv/src/mv.rs:111]: @cakebaker can I run the workflows locally? They won't run until they're approved:

File: src/uu/mv/src/error.rs (hunk 2 above)
Comment (mickvangelderen) [reply src/uu/mv/src/error.rs]: @cakebaker does this PR really achieve the goal of the issue then? Which `mv` are we trying to emulate?

Comment (cakebaker) [reply src/uu/mv/src/error.rs]: Yes, the goal is to get better error messages and your PR achieves it. We try to be compatible with the latest version of `mv`. In this case it is not possible, though, as the behavior depends on the underlying system. This is why there is no test for it in https://github.com/coreutils/coreutils/blob/master/tests/mv/trailing-slash.sh and the  authors write in a comment:

> We would like the erroneous-looking "mv any non-dir/" to fail,
> but with the current implementation, it depends on how the
> underlying rename syscall handles the trailing slash.

**Comment by cakebaker** [comment]
Thanks for your PR :)

File: src/uu/mv/src/mv.rs (hunk 3 above)
Comment (cakebaker) [reply src/uu/mv/src/mv.rs:111]: @mickvangelderen the approval is no longer needed and the workflows should run automatically in the future.

**Comment by mickvangelderen** [comment]
> Thanks for your PR :)

Thanks for the guidance and swift reviews :)
