### PR TITLE
cp: require preserve only certain attributes

### LINKED ISSUE #4079: `test_cp_parents_2_dirs` fails on android
```

---- test_cp::test_cp_parents_2_dirs stdout ----
current_directory_resolved: 
mkdir_all: /data/data/com.termux/files/usr/tmp/.tmpLVaxT2/a/b/c
mkdir: /data/data/com.termux/files/usr/tmp/.tmpLVaxT2/d
run: /data/data/com.termux/files/home/coreutils/target/debug/coreutils cp -a --parents a/b/c d
thread 'test_cp::test_cp_parents_2_dirs' panicked at 'Command was expected to succeed.
stdout = 
 stderr = cp: Permission denied (os error 13)
', tests/common/util.rs:176:9

```

test introduced in:
https://github.com/uutils/coreutils/commit/ac3fcca6c04f324d5de97efc92712f9960fef5aa

cc @jfinkels

### PR DESCRIPTION
**Pull request by sssemil**
In GNU cp, there's a lot of special handling of errors based on using `-a`, `-p`, `--preserve=all`, `--preserve=xattr,context` etc. which is not handled properly at the moment. In this PR, an analogous behavior to that of `require_preserve_xattr`, `require_preserve_context`, and `require_preserve` flags in GNU cp code is implemented.

Somethings left todo are testing xattr permission denied case (outside of Android test), and also context permission denied case. One idea is making a simple user-space fuse FS with advanced xattr modification permission controls. This will be implemented in a separate PR here - https://github.com/uutils/coreutils/pull/4100.

Original PR: https://github.com/uutils/coreutils/pull/4095 (started implemeting testfs there, but it's a bit out of scope, so, I'm separating these PR's).

Closes #4079.

### CODE REVIEW

File: tests/by-util/test_cp.rs [hunk 1]
```diff
@@ -893,6 +893,28 @@ fn test_cp_preserve_no_args() {
...
 }
 
+#[test]
+#[cfg(unix)]
+fn test_cp_preserve_all() {
+    // TODO: create a destination that does not allow copying of xattr and context
+    new_ucmd!()
+        .arg(TEST_COPY_FROM_FOLDER_FILE)
+        .arg(TEST_HELLO_WORLD_DEST)
+        .arg("--preserve=all")
```
Comment (sylvestre) [inline tests/by-util/test_cp.rs:903]: this test only verifies if the command was successful. it would be better to test that some parameters are preserved!

Comment (sssemil) [reply tests/by-util/test_cp.rs:903]: Hm, true. However, this PR is about ignoring the error for `all` case and not ignoring for `xattr` case. So, this one should always pass. But, I think I need to change the second test, to have one for Android, that is expected to fail, and one for other, that is expected to pass. What do you think? Otherwise, I could add some user extended attribute and for example change permissions, and check if they persist, but feels a little random :)

Comment (sylvestre) [reply tests/by-util/test_cp.rs:903]: nan, this would be great :)

File: src/uu/cp/src/cp.rs [hunk 2]
```diff
@@ -769,6 +774,22 @@ impl Options {
...
 
+        // Parse attributes to require preserve
+        let require_preserve_attributes: Vec<Attribute> = if reduced_preserve_requirements_case {
+            preserve_attributes
+                .clone()
+                .into_iter()
+                .filter(|attribute| match attribute {
+                    #[cfg(feature = "feat_selinux")]
+                    Attribute::Context => false,
+                    Attribute::Xattr => false,
```
Comment (tertsdiepraam) [inline src/uu/cp/src/cp.rs:785]: What about the case of `--preserve=all,context`? Should it still not require preserving the context?

**Review by tertsdiepraam — COMMENTED** [review]
So, I think it'd be good to rethink how we handle attributes, cause I don't the approach with the `Vec<Attribute>` is great. It feels more complex that it needs to be. Instead of an `Attribute` enum, I think we need an `Attributes` struct with a `Preserve` enum. Let me give a sketch:

```rust
struct Attributes {
    ownership: Preserve,
    mode: Preserve,
    timestamps: Preserve,
    context: Preserve,
    links: Preserve,
    xattr: Preserve,
}

enum Preserve {
    No,      // don't preserve
    Try,     // preserve but don't error
    Require, // return error if it doesn't work
}
```

Alternatively:
```rust
enum Preserve {
    No,
    Yes{ required: bool },
}
```

The default would be `No` unless the attribute is specified to be preserved. In the case of `"all"`, we could then do:

```rust
impl Attributes {
    fn all() -> Self {
         Self {
             ownership: Preserve::Require,
             mode: Preserve::Require,
             timestamps: Preserve::Require,
             links: Preserve::Require,
             context: Preserve::Try,
             xattr: Preserve::Try,
         }
    }
}
```

I think this makes the code much easier to follow.

**Comment by sssemil** [comment]
> an `Attributes` struct

@tertsdiepraam  Nice idea, makes sense :) I wonder what the `copy_attributes` function should look like then, just manually going through each attribute? One way of avoiding that could be params for enums, what do you think about something like this:
```
pub enum Attribute {
    #[cfg(unix)]
    Ownership { required: bool },
    Mode { required: bool },
    Timestamps { required: bool },
    #[cfg(feature = "feat_selinux")]
    Context { required: bool },
    Links { required: bool },
    Xattr { required: bool },
}
```

Although, this would cause a lot of change to unrelated code, and some unnecessary required setting...

**Comment by tertsdiepraam** [comment]
I don't see how the required flag would help with not iterating through each attribute? I agree though that this would change too many things at the same time.

**Comment by sssemil** [comment]
> I don't see how the required flag would help with not iterating through each attribute? I agree though that this would change too many things at the same time.

Ah, I was going the opposite direction here. Was concerned that replacing that iteration over attributes vector with handling each separately would be a negative.

I'll try with the struct, let's see how it works out. Thanks!

**Comment by tertsdiepraam** [comment]
Oh I only see now that you wrote `enum` and not `struct`! That makes your message more clear :)

> Was concerned that replacing that iteration over attributes vector with handling each separately would be a negative.

I actually want to replace the `Vec` indeed, so `copy_attributes` just becomes (rough sketch):
```
fn copy_attributes(attrs: Attributes, ...) -> Result<...> {
    if attrs.ownership != Preserve::No {
         let error = {...};
         ignore_if_try(attr.ownership, error)?
    }
    
    if attrs.mode != Preserve::No {
         ...
    }
}
```
(I made the `ignore_if_try` up, you might come up with something better)

**Comment by sssemil** [comment]
@tertsdiepraam pushed my version of it :)

File: src/uu/cp/src/cp.rs [hunk 3]
```diff
@@ -1078,114 +1100,132 @@ impl OverwriteMode {
...
+macro_rules! handle_preserve {
+    ($preserve:expr, $copy_call:expr) => {
+        if $preserve.is_preserve() {
+            let result = $copy_call();
+            if $preserve == Preserve::Require {
+                result?;
+            }
+        }
+    };
+}
```
Comment (tertsdiepraam) [inline src/uu/cp/src/cp.rs:1113]: This doesn't need to be a macro, a function would be enough:
```rust
fn handle_preserve(p: Preserve, f: fn() -> CopyResult<()>) -> CopyResult<()> {
     if p.is_preserve() {
          let result = f();
          if preserve == Preserve::Require {
              result?;
          }
     }
     Ok(())
}
```
Only difference is that you call it with a `?` at the end.

**Review by tertsdiepraam — COMMENTED** [review]
It's starting to look super clean! Great work. I have a few more suggestions and some bits I think are not quite right, though I might be mistaken.

File: src/uu/cp/src/cp.rs (hunk 3 above)
Comment (sssemil) [reply src/uu/cp/src/cp.rs]: good idea, don't like macros very much :P

File: src/uu/cp/src/cp.rs [hunk 4]
```diff
@@ -157,18 +156,29 @@ pub enum CopyMode {
...
+    links: Preserve,
+    xattr: Preserve,
+}
+
+#[derive(Debug, PartialEq, Eq)]
+pub enum Preserve {
+    No,
+    Try,
+    Require,
+}
```
[the remark this answers is not in the document]
Comment (sssemil) [reply src/uu/cp/src/cp.rs]: Yeah, makes sense, thanks!

File: src/uu/cp/src/cp.rs [hunk 5]
```diff
@@ -710,43 +738,42 @@ impl Options {
...
-            vec![Attribute::Links]
+            let mut attributes = Attributes::none();
+            attributes.links = Preserve::Require;
+            attributes
         } else if matches.get_flag(options::PRESERVE_DEFAULT_ATTRIBUTES) {
-            DEFAULT_ATTRIBUTES.to_vec()
+            Attributes::default()
         } else {
-            vec![]
+            Attributes::none()
```
[the remark this answers is not in the document]
Comment (sssemil) [reply src/uu/cp/src/cp.rs:767]: Thanks :)

File: src/uu/cp/src/cp.rs [hunk 6]
```diff
@@ -710,43 +738,42 @@ impl Options {
...
+                None => Attributes::default(),
                 Some(attribute_strs) => {
-                    let mut attributes = Vec::new();
+                    let mut attributes: Attributes = Attributes::none();
+                    let mut attributes_empty = true;
                     for attribute_str in attribute_strs {
+                        attributes_empty = false;
                         if attribute_str == "all" {
-                            attributes = add_all_attributes();
+                            attributes = Attributes::all();
```
[the remark this answers is not in the document]
Comment (sssemil) [reply src/uu/cp/src/cp.rs:743]: Hm, true, didn't think about this.. Nice idea, let me try :)

File: src/uu/cp/src/cp.rs [hunk 7]
```diff
@@ -710,43 +738,42 @@ impl Options {
...
                             break;
                         } else {
-                            attributes.push(Attribute::from_str(attribute_str)?);
+                            attributes.try_set_from_string(attribute_str, Attributes::default())?;
```
[the remark this answers is not in the document]
Comment (sssemil) [reply src/uu/cp/src/cp.rs:773]: It should still error because it's basically disabled on a non-SELinux machine (because of the attribute). Which doesn't make it easier, hm. Could it be an issue if you try using a binary built on a SELinux machine on a non-SELinux machine?

**Comment by sylvestre** [comment]
fails on mac because of:
```

---- test_cp::test_cp_preserve_xattr stdout ----
current_directory_resolved: 
run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils cp a b --preserve=xattr
thread 'test_cp::test_cp_preserve_xattr' panicked at 'assertion failed: `(left != right)`
  left: `1669645276`,
 right: `1669645276`', tests/by-util/test_cp.rs:963:5
```

could you have please a look?
thanks

**Comment by sssemil** [comment]
> fails on mac because of:
> 
> ```
> 
> ---- test_cp::test_cp_preserve_xattr stdout ----
> current_directory_resolved: 
> run: /Users/runner/work/coreutils/coreutils/target/debug/coreutils cp a b --preserve=xattr
> thread 'test_cp::test_cp_preserve_xattr' panicked at 'assertion failed: `(left != right)`
>   left: `1669645276`,
>  right: `1669645276`', tests/by-util/test_cp.rs:963:5
> ```
> 
> could you have please a look? thanks

Hm, it looks like the modified time is copied in tests but not when running it locally... Is there some unusual file handling in the tests?

GNU cp:
```
$ rm -rf a b; touch a; sleep 1; cp --preserve=xattr a b; stat a b
  File: a
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: 0,37    Inode: 20061619    Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/    emil)   Gid: ( 1000/    emil)
Access: 2022-12-07 03:28:14.095178786 +0100
Modify: 2022-12-07 03:28:14.095178786 +0100
Change: 2022-12-07 03:28:14.095178786 +0100
 Birth: 2022-12-07 03:28:14.095178786 +0100
  File: b
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: 0,37    Inode: 20061624    Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/    emil)   Gid: ( 1000/    emil)
Access: 2022-12-07 03:28:15.101800872 +0100
Modify: 2022-12-07 03:28:15.101800872 +0100
Change: 2022-12-07 03:28:15.101800872 +0100
 Birth: 2022-12-07 03:28:15.101800872 +0100
```

uutils/coreutils:
```
$ rm -rf a b; touch a; sleep 1; coreutils cp --preserve=xattr a b; stat a b
  File: a
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: 0,37    Inode: 20061695    Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/    emil)   Gid: ( 1000/    emil)
Access: 2022-12-07 03:30:23.899427115 +0100
Modify: 2022-12-07 03:30:23.899427115 +0100
Change: 2022-12-07 03:30:23.899427115 +0100
 Birth: 2022-12-07 03:30:23.899427115 +0100
  File: b
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: 0,37    Inode: 20061699    Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/    emil)   Gid: ( 1000/    emil)
Access: 2022-12-07 03:30:24.902715973 +0100
Modify: 2022-12-07 03:30:24.902715973 +0100
Change: 2022-12-07 03:30:24.902715973 +0100
 Birth: 2022-12-07 03:30:24.902715973 +0100
```

**Comment by sssemil** [comment]
Here's what these files look like during the test:
```
/tmp/.tmpat5LjD $ stat a b
  File: a
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: 0,39    Inode: 4914        Links: 1
Access: (0500/-r-x------)  Uid: ( 1000/    emil)   Gid: ( 1000/    emil)
Access: 2022-12-07 03:40:10.430054364 +0100
Modify: 2022-12-07 03:40:09.386767394 +0100
Change: 2022-12-07 03:40:09.386767394 +0100
 Birth: 2022-12-07 03:40:09.386767394 +0100
  File: b
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: 0,39    Inode: 4915        Links: 1
Access: (0500/-r-x------)  Uid: ( 1000/    emil)   Gid: ( 1000/    emil)
Access: 2022-12-07 03:40:10.430054364 +0100
Modify: 2022-12-07 03:40:10.430054364 +0100
Change: 2022-12-07 03:40:10.430054364 +0100
 Birth: 2022-12-07 03:40:10.430054364 +0100
```

The access time is updates in the test, unlike in the manual run. Maybe difference between how `stat` works and the `fs::metadata` works. But doesn't explain the mac os error.

**Comment by sssemil** [comment]
@sylvestre I tried debugging this in a VM with mac os, and it looks like this is just how mac's copy works, I can't go much further without a mac, so I disabled this test for now and added a todo, maybe someone with a mac can work on this.

File: src/uu/cp/src/cp.rs [hunk 8]
```diff
@@ -710,43 +774,45 @@ impl Options {
...
                         if attribute_str == "all" {
-                            attributes = add_all_attributes();
+                            attributes.max(Attributes::all());
                             break;
                         } else {
-                            attributes.push(Attribute::from_str(attribute_str)?);
+                            attributes.try_set_from_string(
+                                attribute_str,
+                                Attributes::default_explicit(),
+                            )?;
```
Comment (tertsdiepraam) [inline src/uu/cp/src/cp.rs:792]: If this is the only `Attributes` you pass to `try_set_from_string` I think it's worth simplifying and always make `try_set_from_string` set attributes to `Preserve::Yes { required: true }`.

Comment (tertsdiepraam) [reply src/uu/cp/src/cp.rs:792]: I.e.
```rust
fn try_set_from_string(&mut self, value: &str) -> Result<(), Error> {
    let yes = Preserve::Yes { required: yes };
    match &*value.to_lowercase() {
        "mode" => self.mode = yes,
        #[cfg(unix)]
        "ownership" => self.ownership = yes,
        "timestamps" => self.timestamps = yes,
        #[cfg(feature = "feat_selinux")]
        "context" => self.context = yes,
        "links" => self.links = yes,
        "xattr" => self.xattr = yes,
        _ => {
            return Err(Error::InvalidArgument(format!(
                "invalid attribute {}",
                value.quote()
            )));
        }
    };
    Ok(())
}
```

Comment (tertsdiepraam) [reply src/uu/cp/src/cp.rs:792]: Oh and `"context"` should probably be recognized but emit a warning instead of failing if `feat_selinux` is not enabled.

**Review by tertsdiepraam — COMMENTED** [review]
Just some quick comments. Seems to be going well!

File: src/uu/cp/src/cp.rs (hunk 8 above)
Comment (sssemil) [reply src/uu/cp/src/cp.rs:792]: > Oh and `"context"` should probably be recognized but emit a warning instead of failing if `feat_selinux` is not enabled.

Thinking about this right now, should I then throw a new error type? Maybe `FeatureDisabled`? Maybe something like this:
```rust
"context" =>
    {
        #[cfg(feature = "feat_selinux")]
        {
            self.context = self.context.max(preserve_yes_required);
        }
        #[cfg(not(feature = "feat_selinux"))]
        {
            return Err(Error::FeatureDisabled)
        }
    }
,
```

Comment (sssemil) [reply src/uu/cp/src/cp.rs:792]: Hm, then it makes sense to throw an error in `handle_preserve(&attributes.context, || -> CopyResult<()> {...` section, it handles errors as warnings if not required already :)

Comment (sssemil) [reply src/uu/cp/src/cp.rs:792]: Ah, never mind, it just ignores silently if it's not required. Hm, would it be better to print the error message in the `handle_preserve` if the attribute in not required (and throw like we have it now otherwise)? I think this should be a more helpful behavior.

Comment (sssemil) [reply src/uu/cp/src/cp.rs]: Hm, this breaks `test_cp_parents_2_dirs` test, since it enables `--archive` and that causes it to print warning for the context option, which is not desired if I judge by the test?

Comment (sssemil) [reply src/uu/cp/src/cp.rs]: How about having the default attributes for the all case have the following conditioning for the context, if the cfg feature feat_selinux is on, then set context to `Preserve::Yes { required: false }`, otherwise to `Preserve::No,`, then only if the user explicitly specifies the `context` it will warn.

Comment (tertsdiepraam) [reply src/uu/cp/src/cp.rs]: That makes sense to me! About handling it in `handle_preserve`, wouldn't it then print the warning for each file? That seems a bit much.

Comment (sssemil) [reply src/uu/cp/src/cp.rs]: How about now?

File: src/uu/cp/src/cp.rs [hunk 9]
```diff
@@ -710,42 +763,51 @@ impl Options {
...
         };
 
-        // Make sure ownership is changed before other attributes,
-        // as chown clears some of the permission and therefore could undo previous changes
-        // if not executed first.
-        preserve_attributes.sort_unstable();
+        #[cfg(not(feature = "feat_selinux"))]
+        if let Preserve::Yes { required } = attributes.context {
+            let selinux_disabled_error =
+                Error::Error("SELinux was not enabled during the compile time!".to_string());
```
[the remark this answers is not in the document]
Comment (sssemil) [reply src/uu/cp/src/cp.rs]: That could be nice, but the GNU cp does the following:
```
$ cp --preserve=all,context a b
cp: cannot preserve security context without an SELinux-enabled kernel
✘ $ ls -lah a b
ls: cannot access 'b': No such file or directory
-rw-r--r-- 1 emil emil 0 Dec 21 10:58 a
✘ $
```

I pushed a commit to only warn, but can revert it.

[the remark this answers is not in the document]
Comment (tertsdiepraam) [reply src/uu/cp/src/cp.rs:804]: Sorry, forgot to respond. I think you're right, let's follow GNU!

**Comment by sssemil** [comment]
@tertsdiepraam @sylvestre is this good to merge? Would be great if we can resole this soon, and resolve any other questions in other PRs

File: src/uu/cp/src/cp.rs [hunk 10]
```diff
@@ -157,18 +156,49 @@ pub enum CopyMode {
...
+    }
+}
+
+#[derive(Debug, PartialEq, Eq)]
+pub enum Preserve {
+    No,
+    Yes { required: bool },
+}
+
+impl Preserve {
```
Comment (sylvestre) [inline src/uu/cp/src/cp.rs:190]: could you please add a comment here to explain what it is doing? thanks

File: src/uu/cp/src/cp.rs [hunk 11]
```diff
@@ -627,46 +649,77 @@ impl CopyMode {
...
+            ownership: Preserve::No,
+            mode: Preserve::No,
+            timestamps: Preserve::No,
+            context: Preserve::No,
+            links: Preserve::No,
+            xattr: Preserve::No,
+        }
+    }
+
+    fn try_set_from_string(&mut self, value: &str) -> Result<(), Error> {
```
Comment (sylvestre) [inline src/uu/cp/src/cp.rs:701]: please document this function

File: src/uu/cp/src/cp.rs [hunk 12]
```diff
@@ -951,6 +1011,20 @@ fn preserve_hardlinks(
     Ok(found_hard_link)
 }
 
+fn show_error_if_needed(error: &Error) -> bool {
```
Comment (sylvestre) [inline src/uu/cp/src/cp.rs:1014]: please also document this function

File: src/uu/cp/src/cp.rs [hunk 13]
```diff
@@ -1100,114 +1167,135 @@ impl OverwriteMode {
     }
 }
 
+fn handle_preserve<F: Fn() -> CopyResult<()>>(p: &Preserve, f: F) -> CopyResult<()> {
```
Comment (sylvestre) [inline src/uu/cp/src/cp.rs:1170]: ditto

File: src/uu/cp/src/cp.rs (hunk 10 above)
Comment (sssemil) [reply src/uu/cp/src/cp.rs:190]: Done

File: src/uu/cp/src/cp.rs (hunk 12 above)
Comment (sssemil) [reply src/uu/cp/src/cp.rs:1022]: Done

File: src/uu/cp/src/cp.rs (hunk 13 above)
Comment (sssemil) [reply src/uu/cp/src/cp.rs:1181]: Done

File: src/uu/cp/src/cp.rs (hunk 11 above)
Comment (sssemil) [reply src/uu/cp/src/cp.rs:707]: Done

File: src/uu/cp/src/cp.rs [hunk 14]
```diff
@@ -627,46 +651,81 @@ impl CopyMode {
...
+
+    /// Tries to match string containing a parameter to preserve with the corresponding entry in the
+    /// Attributes struct. The values are maximized, which means that, when the Attributes are
+    /// initialized with some preserve levels, and later found in the `--preserve=...` values, they
+    /// are updated to maximum of the one set already and the one found in the string from the user.
+    fn try_set_from_string(&mut self, value: &str) -> Result<(), Error> {
+        let preserve_yes_required = Preserve::Yes { required: true };
+
+        match &*value.to_lowercase() {
+            "mode" => self.mode = self.mode.max(preserve_yes_required),
```
Comment (tertsdiepraam) [inline src/uu/cp/src/cp.rs:711]: We don't need `max` here, right? `self.mode = preserve_yes_required` should be enough.

**Review by tertsdiepraam — APPROVED** [review]
You're right, this has taken a while :) I think it looks good, but will leave merging to Sylvestre if he thinks the docs are good now.

File: src/uu/cp/src/cp.rs (hunk 14 above)
Comment (sssemil) [reply src/uu/cp/src/cp.rs]: You are right, updated!
