### PR TITLE
uniq: fix -w to count bytes in C locale

### LINKED ISSUE #10184: uniq: -w counts UTF-8 characters instead of bytes
# `uniq -w` counts UTF-8 characters instead of bytes

## Component

uniq

## Description

GNU uniq's `-w N` (check-chars) option compares the first N **bytes** of each line, while uutils uniq compares the first N **UTF-8 characters**. This causes different behavior when processing multibyte characters (e.g., CJK characters, emoji).

[uutils uniq](https://github.com/uutils/coreutils/blob/75b3bc02eb80a5f07c708096e8a2ea4fd03190f2/src/uu/uniq/src/uniq.rs#L175-L181) always uses UTF-8 character-based comparison regardless of locale, using Rust's `.chars().take(N)` method.

```rust
let total_chars = string_after_skip.chars().count();

// `-w N` => Compare no more than N characters
let slice_stop = self.slice_stop.unwrap_or(total_chars);
let slice_start = slice_stop.min(total_chars);

let mut iter = string_after_skip.chars().take(slice_start);
```

## Test / Reproduction Steps

```bash
$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_ALL=
$ printf "가나다라마\n가나다바사\n" > korean.txt

# -w 3
$ uniq -w 3 korean.txt
가나다라마

$ coreutils uniq -w 3 korean.txt
가나다라마

# -w 4
$ uniq -w 4 korean.txt
가나다라마

$ coreutils uniq -w 4 korean.txt
가나다라마
가나다바사

# -w 12
$ uniq -w 12 korean.txt
가나다라마
가나다바사

$ coreutils uniq -w 12 korean.txt
가나다라마
가나다바사
```

## Impact

Scripts using `-w` with multibyte characters (CJK, emoji) produce different results between GNU and uutils.

### PR DESCRIPTION
**Pull request by aguimaraes**
### Summary

 ` uniq -w N` should count bytes in C/POSIX locale and characters in UTF-8 locale. Currently it always counts UTF-8 characters regardless of locale.

### Changes

  - Added `is_c_locale()` helper that checks `LC_ALL`, `LC_CTYPE`, `LANG` in order
  - Modified `key_end_index()` to use byte counting when in C locale
  - Added test for C locale byte counting behavior
  - Fixed `test_stdin_w1_multibyte` to explicitly set UTF-8 locale (it was implicitly relying on character counting)

### Considerations

I chose to inline the locale check (~9 lines) rather than adding the `i18n` feature dependency. The check is simple enough that duplicating it seemed better than pulling in ICU dependencies just for this.

If you'd prefer I use `uucore::i18n` instead, let me know and I'll update.

Fixes #10184

### CODE REVIEW

File: src/uu/uniq/src/uniq.rs [hunk 1]
```diff
@@ -186,6 +186,17 @@ impl Uniq {
...
+    fn is_c_locale() -> bool {
+        for key in ["LC_ALL", "LC_CTYPE", "LANG"] {
+            if let Ok(v) = std::env::var(key) {
+                if !v.is_empty() {
+                    return v == "C" || v == "POSIX";
+                }
+            }
+        }
+        true
+    }
```
Comment (xtqqczze) [inline src/uu/uniq/src/uniq.rs:198]:
```suggestion
    fn is_c_locale() -> bool {
        ["LC_ALL", "LC_CTYPE", "LANG"]
            .into_iter()
            .find_map(|k| std::env::var_os(k).filter(|v| !v.is_empty()))
            .is_none_or(|v| v == "C" || v == "POSIX")
    }
```

we can avoid some `String` allocations by using `var_os`

Comment (aguimaraes) [reply src/uu/uniq/src/uniq.rs:198]: Thank you, makes sense! Updated!

**Comment by cakebaker** [comment]
Thanks!
