### PR TITLE
fix(wc):GNU wc-cpu.sh

### LINKED ISSUE #9725: wc: implement `--debug` flag
In the GNU manual for [wc](https://www.gnu.org/software/coreutils/manual/html_node/wc-invocation.html), it contains a flag called `--debug` . The `--debug` flag currently prints the line count acceleration implementation being used to stderr.

In the failing test for `wc` `wc-cpu.log`, I looked into what `wc-cpu.sh` is testing for in GNU's upstream mirror (hope that's fine since it's not implementation related to `wc`). From my understanding, it's testing whether `wc` is outputting the same information to stdout with and without cpu disabling features. However, one of lines in the test code also invokes the `wc` command with `--debug` flag. I believe we're failing this test due to not supporting `--debug` flag in wc currently.

If we do plan on implementing this, this should be a quick and easy addition to the current `wc` program. Also note that this flag is not mentioned in GNU's `wc --h` (though it does exist and doesn't give me an error when I turn on the `--debug` flag in my terminal).

### PR DESCRIPTION
**Pull request by mattsu2020**
Fixes #9725

### Overview

Disable SIMD-accelerated paths when GLIBC_TUNABLES removes AVX/AVX512 so wc falls back to the naive counters.
Add hidden --debug flag output that reports whether hardware acceleration is active, disabled by tunables, or unavailable at runtime.
Cache SIMD policy decisions and reuse them within the fast path code to avoid repeated environment parsing.

### Testing

cargo test -p uu_wc
cargo clippy -p uu_wc -- -D warnings
Spot-check wc -l with and without GLIBC_TUNABLES='glibc.cpu.hwcaps=-AVX2,-AVX512F'

### CODE REVIEW

File: src/uu/wc/src/cpu_features.rs [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+    }
+    #[cfg(target_arch = "x86_64")]
+    {
+        if std::arch::is_x86_feature_detected!("avx2") {
+            features.push("AVX2");
+        }
+        if std::arch::is_x86_feature_detected!("sse2") {
+            features.push("SSE2");
+        }
+    }
```
Comment (RenjiSann) [inline src/uu/wc/src/cpu_features.rs]:
```suggestion
    #[cfg(any(target_arch = "x86", target_arch = "x86_64")]
    {
        if std::arch::is_x86_feature_detected!("avx2") {
            features.push("AVX2");
        }
        if std::arch::is_x86_feature_detected!("sse2") {
            features.push("SSE2");
        }
    }
```
Maybe simplify it to this (unless I missed something and it's actually not duplicated code)

File: src/uu/wc/src/cpu_features.rs
Comment (RenjiSann) [inline src/uu/wc/src/cpu_features.rs:1]: We should agree on a common implementation to put in uucore for it to be reused for the --debug flag of `cksum` (see https://github.com/uutils/coreutils/pull/9088)

Comment (mattsu2020) [reply src/uu/wc/src/cpu_features.rs:1]: Modified to use the uucore module

**Comment by RenjiSann** [comment]
Can you add a test to avoid regressions in the future ?

**Comment by sylvestre** [comment]
job fails with:
`ERROR taplo:format_files: the file is not properly formatted path="/home/runner/work/coreutils/coreutils/src/uu/wc/Cargo.toml"`

File: src/uu/wc/src/wc.rs [hunk 2]
```diff
@@ -814,6 +826,31 @@ fn wc(inputs: &Inputs, settings: &Settings) -> UResult<()> {
         _ => (compute_number_width(inputs, settings), true),
     };
 
+    if settings.debug {
+        let policy = simd_policy();
+        if policy.allows_simd() {
+            let enabled = policy.enabled_features();
+            if enabled.is_empty() {
+                eprintln!("wc: debug: hardware support unavailable on this CPU");
```
Comment (sylvestre) [inline src/uu/wc/src/wc.rs]: please use the translate! macro

**Comment by asder8215** [comment]
This looks good to me so far

**Comment by RenjiSann** [comment]
The hardware API in uucore changed, so there is no `simd_policy` function anymore.
There is some refactoring to do in this PR

Also, could you squash the different commits in a single one for better traceability once merged ? Thanks !

**Comment by RenjiSann** [comment]
```
$ ../gnu/src/wc -l --debug /dev/null          
wc: avx512 support not detected
wc: using avx2 hardware support
0 /dev/null

$ GLIBC_TUNABLES='glibc.cpu.hwcaps=-AVX512F,-AVX2' ../gnu/src/wc -l --debug /dev/null
wc: avx512 support not detected
wc: avx2 support not detected
0 /dev/null

$ GLIBC_TUNABLES='glibc.cpu.hwcaps=-AVX512F' ../gnu/src/wc -l --debug /dev/null    
wc: avx512 support not detected
wc: using avx2 hardware support
0 /dev/null

$ GLIBC_TUNABLES='glibc.cpu.hwcaps=-AVX512F' ./target/debug/wc -l --debug /dev/null      
wc: debug: hardware support disabled by GLIBC_TUNABLES (AVX512F)
0 /dev/null
```

When we only disable AVX512, this is misleading because we don't mention that `AVX2` is still usable

File: src/uu/wc/src/wc.rs [hunk 3]
```diff
@@ -805,6 +817,66 @@ fn escape_name_wrapper(name: &OsStr) -> String {
...
+        HardwareFeature::Avx512 => "AVX512F",
+        HardwareFeature::Avx2 => "AVX2",
+        HardwareFeature::PclMul => "PCLMUL",
+        HardwareFeature::Vmull => "VMULL",
+        HardwareFeature::Sse2 => "SSE2",
+        HardwareFeature::Asimd => "ASIMD",
+    }
+}
+
+fn is_wc_simd_runtime_feature(feature: &HardwareFeature) -> bool {
```
Comment (sylvestre) [inline src/uu/wc/src/wc.rs]: ould be shortened to `is_runtime_feature` since it's in wc context

File: src/uu/wc/src/wc.rs [hunk 4]
```diff
@@ -805,6 +817,66 @@ fn escape_name_wrapper(name: &OsStr) -> String {
...
+    matches!(
+        feature,
+        HardwareFeature::Avx2 | HardwareFeature::Sse2 | HardwareFeature::Asimd
+    )
+}
+
+fn is_wc_simd_debug_feature(feature: &HardwareFeature) -> bool {
```
Comment (sylvestre) [inline src/uu/wc/src/wc.rs]: same

File: src/uu/wc/src/wc.rs [hunk 5]
```diff
@@ -805,6 +817,66 @@ fn escape_name_wrapper(name: &OsStr) -> String {
...
+    matches!(
+        feature,
+        HardwareFeature::Avx512
+            | HardwareFeature::Avx2
+            | HardwareFeature::Sse2
+            | HardwareFeature::Asimd
+    )
+}
+
+fn wc_simd_enabled_features(policy: &SimdPolicy) -> Vec<HardwareFeature> {
```
Comment (sylvestre) [inline src/uu/wc/src/wc.rs]: Consider combining `wc_simd_enabled_features` and `wc_simd_disabled_features` into a single function that returns both to avoid duplicate iteration

File: src/uu/wc/src/wc.rs [hunk 6]
```diff
@@ -814,6 +886,46 @@ fn wc(inputs: &Inputs, settings: &Settings) -> UResult<()> {
...
+            .collect();
+        let disabled: Vec<&'static str> = disabled_features
+            .iter()
+            .copied()
+            .map(hardware_feature_label)
+            .collect();
+
+        let runtime_disabled = !disabled_runtime_features.is_empty();
+
+        match (enabled.is_empty(), runtime_disabled, disabled.is_empty()) {
```
Comment (sylvestre) [inline src/uu/wc/src/wc.rs]: Pattern matching on tuple with 3 bool elements is hard to read :/

File: src/uu/wc/src/wc.rs [hunk 7]
```diff
@@ -805,6 +817,66 @@ fn escape_name_wrapper(name: &OsStr) -> String {
...
+
+fn wc_simd_disabled_runtime_features(policy: &SimdPolicy) -> Vec<HardwareFeature> {
+    policy
+        .disabled_features()
+        .into_iter()
+        .filter(is_wc_simd_runtime_feature)
+        .collect()
+}
+
+pub(crate) fn wc_simd_allowed(policy: &SimdPolicy) -> bool {
```
Comment (sylvestre) [inline src/uu/wc/src/wc.rs:878]: should we cache this ?

File: src/uu/wc/src/wc.rs (hunk 3 above)
Comment (mattsu2020) [reply src/uu/wc/src/wc.rs]: fix

File: src/uu/wc/src/wc.rs (hunk 4 above)
Comment (mattsu2020) [reply src/uu/wc/src/wc.rs]: fix

File: src/uu/wc/src/wc.rs (hunk 5 above)
Comment (mattsu2020) [reply src/uu/wc/src/wc.rs]: fix

File: src/uu/wc/src/wc.rs (hunk 6 above)
Comment (mattsu2020) [reply src/uu/wc/src/wc.rs]: fix

File: src/uu/wc/src/wc.rs (hunk 7 above)
Comment (mattsu2020) [reply src/uu/wc/src/wc.rs:878]: Since it's already cached elsewhere, it's a tough call whether to cache it here.

File: src/uu/wc/src/wc.rs [hunk 8]
```diff
@@ -814,6 +894,51 @@ fn wc(inputs: &Inputs, settings: &Settings) -> UResult<()> {
...
+                "{}",
+                translate!("wc-debug-hw-disabled-glibc", "features" => disabled.join(", "))
+            );
+        } else if !enabled_empty && disabled_empty {
+            eprintln!(
+                "{}",
+                translate!("wc-debug-hw-using", "features" => enabled.join(", "))
+            );
+        } else {
+            eprintln!(
```
Comment (RenjiSann) [inline src/uu/wc/src/wc.rs]:
```suggestion
        if enabled_empty && !runtime_disabled {
            show_error!("{}", translate!("wc-debug-hw-unavailable"));
        } else if runtime_disabled {
            show_error!(
                "{}",
                translate!("wc-debug-hw-disabled-glibc", "features" => disabled.join(", "))
            );
        } else if !enabled_empty && disabled_empty {
            show_error!(
                "{}",
                translate!("wc-debug-hw-using", "features" => enabled.join(", "))
            );
        } else {
            show_error!(
```

The `show_error!` macro is specifically made to prepend `<bin-name>: ` to the message

File: src/uu/wc/locales/en-US.ftl [hunk 9]
```diff
@@ -31,3 +31,10 @@ decoder-error-io = underlying bytestream error: { $error }
 # Other messages
 wc-standard-input = standard input
 wc-total = total
+
+# Debug messages
+wc-debug-hw-unavailable = wc: debug: hardware support unavailable on this CPU
+wc-debug-hw-using = wc: debug: using hardware support (features: { $features })
+wc-debug-hw-disabled-env = wc: debug: hardware support disabled by environment
+wc-debug-hw-disabled-glibc = wc: debug: hardware support disabled by GLIBC_TUNABLES ({ $features })
+wc-debug-hw-limited-glibc = wc: debug: hardware support limited by GLIBC_TUNABLES (disabled: { $disabled }; enabled: { $enabled })
```
Comment (RenjiSann) [inline src/uu/wc/locales/en-US.ftl]:
```suggestion
wc-debug-hw-unavailable = debug: hardware support unavailable on this CPU
wc-debug-hw-using = debug: using hardware support (features: { $features })
wc-debug-hw-disabled-env = debug: hardware support disabled by environment
wc-debug-hw-disabled-glibc = debug: hardware support disabled by GLIBC_TUNABLES ({ $features })
wc-debug-hw-limited-glibc = debug: hardware support limited by GLIBC_TUNABLES (disabled: { $disabled }; enabled: { $enabled })
```

File: src/uu/wc/locales/fr-FR.ftl [hunk 10]
```diff
@@ -31,3 +31,10 @@ decoder-error-io = erreur du flux d'octets sous-jacent : { $error }
 # Autres messages
 wc-standard-input = entrée standard
 wc-total = total
+
+# Messages de débogage
+wc-debug-hw-unavailable = wc : debug : prise en charge matérielle indisponible sur ce CPU
+wc-debug-hw-using = wc : debug : utilisation de l'accélération matérielle (fonctions : { $features })
+wc-debug-hw-disabled-env = wc : debug : prise en charge matérielle désactivée par l'environnement
+wc-debug-hw-disabled-glibc = wc : debug : prise en charge matérielle désactivée par GLIBC_TUNABLES ({ $features })
+wc-debug-hw-limited-glibc = wc : debug : prise en charge matérielle limitée par GLIBC_TUNABLES (désactivé : { $disabled } ; activé : { $enabled })
```
Comment (RenjiSann) [inline src/uu/wc/locales/fr-FR.ftl]:
```suggestion
wc-debug-hw-unavailable = debug : prise en charge matérielle indisponible sur ce CPU
wc-debug-hw-using = debug : utilisation de l'accélération matérielle (fonctions : { $features })
wc-debug-hw-disabled-env = debug : prise en charge matérielle désactivée par l'environnement
wc-debug-hw-disabled-glibc = debug : prise en charge matérielle désactivée par GLIBC_TUNABLES ({ $features })
wc-debug-hw-limited-glibc = debug : prise en charge matérielle limitée par GLIBC_TUNABLES (désactivé : { $disabled } ; activé : { $enabled })
```

File: src/uu/wc/src/wc.rs [hunk 11]
```diff
@@ -814,6 +894,51 @@ fn wc(inputs: &Inputs, settings: &Settings) -> UResult<()> {
...
+            .iter()
+            .copied()
+            .map(hardware_feature_label)
+            .collect();
+        let disabled: Vec<&'static str> = features
+            .disabled
+            .iter()
+            .copied()
+            .map(hardware_feature_label)
+            .collect();
```
Comment (sylvestre) [inline src/uu/wc/src/wc.rs:912]: why these two ?
if it is enabled, it can not be disabled?

File: src/uu/wc/src/wc.rs [hunk 12]
```diff
@@ -814,6 +894,51 @@ fn wc(inputs: &Inputs, settings: &Settings) -> UResult<()> {
...
+
+        let enabled_empty = enabled.is_empty();
+        let disabled_empty = disabled.is_empty();
```
Comment (sylvestre) [inline src/uu/wc/src/wc.rs:915]: same

File: src/uu/wc/src/wc.rs (hunk 11 above)
Comment (mattsu2020) [reply src/uu/wc/src/wc.rs:912]: enabled is derived from policy.iter_features() (hardware minus GLIBC_TUNABLES‑disabled), while disabled is the subset explicitly disabled by GLIBC_TUNABLES for debug output. They’re intentionally different sets, so you can have both when some SIMD features are available and others are disabled
