### PR TITLE
mktemp: fix PrefixContainsDirSeparator verification

### LINKED ISSUE #4378: mktemp: wrong prefix verification
# Discovery

I started testing uutils/coreutils using the AUR package from [coreutils-hybrid](https://aur.archlinux.org/packages/coreutils-hybrid), it merges the uutils packages with the ones missing from the standard GNU . I use dracut to resolve the initframes, however when I updated the kernel and the initframes would be recreated I got the following error:

```sh
dracut: mktemp -p '/var/tmp/' -d -t dracut.XXXXXX failed.
```

I checked and found that the mktemp package came from coreutils and that it was already available in uutils.

# Issue

Let me tell you that I don't program in Rust, not so much in C. Checking the code of both versions I realized that maybe the author of the code checked the prefix after the join with the path.

# Solution

What I did was change the check to prefix only. Passed the tests and apparently everything is ok.

```diff
+ // Check that the prefix is valid.
+ let prefix_of_template = Path::new(prefix_from_template).display().to_string();

+ if options.treat_as_template && prefix_of_template.contains(MAIN_SEPARATOR) {
    return Err(MkTempError::PrefixContainsDirSeparator(options.template));
}
```

---

[NOTICE]: I'm from Brazil, it's Carnaval, so maybe I won't respond so quickly 🥳 🍺 🏖️

### PR DESCRIPTION
**Pull request by ZauJulio**
- I belive can resolve #4378 : ]

### CODE REVIEW

**Comment by sylvestre** [comment]
could you please add a test to make sure we don't regress in the future ?

File: src/uu/mktemp/src/mktemp.rs [hunk 1]
```diff
@@ -281,7 +281,11 @@ impl Params {
             .join(prefix_from_template)
             .display()
             .to_string();
-        if options.treat_as_template && prefix.contains(MAIN_SEPARATOR) {
+
+        // Check that the prefix is valid.
+        let prefix_of_template = Path::new(prefix_from_template).display().to_string();
```
Comment (tertsdiepraam) [inline src/uu/mktemp/src/mktemp.rs:286]:
```suggestion
        let prefix_of_template = Path::new(prefix_from_template).to_string_lossy();
```

This is a slightly shorter way to do the same thing.

**Review by tertsdiepraam — COMMENTED** [review]
Cool looks good to me, though it's a bit sad we have to convert to a `String`.

File: src/uu/mktemp/src/mktemp.rs (hunk 1 above)
Comment (ZauJulio) [reply src/uu/mktemp/src/mktemp.rs:286]: Works perfectly, thanks for the suggestion

**Comment by ZauJulio** [comment]
> could you please add a test to make sure we don't regress in the future ?

Well remembered, I'll do it as soon as I get back

**Comment by sylvestre** [comment]
@ZauJulio ping ? :)

**Comment by ZauJulio** [comment]
> @ZauJulio ping ? :)
> 

Carnival is finally over here in Brazil, I'll upload the test and send it today : ]

**Comment by ZauJulio** [comment]
> @ZauJulio ping ? :)

done, I believe that is enough.
I loved contributing to the project, I'm going to start my studies in Rust and intend to continue here 🧡

File: tests/by-util/test_mktemp.rs [hunk 2]
```diff
@@ -571,6 +572,12 @@ fn test_template_path_separator() {
         ));
 }
 
+/// Test that a prefix with a point is valid.
+#[test]
+fn test_prefix_template_separator() {
+    new_ucmd!().args(&["-t", TEST_TEMPLATE9]).succeeds();
```
Comment (tertsdiepraam) [inline tests/by-util/test_mktemp.rs:578]: This does not really test the issue right? I thought it needed `-p` to error on `main` or am I mistaken?

File: src/uu/mktemp/src/mktemp.rs [hunk 3]
```diff
@@ -281,7 +281,11 @@ impl Params {
             .join(prefix_from_template)
             .display()
             .to_string();
-        if options.treat_as_template && prefix.contains(MAIN_SEPARATOR) {
+
+        // Check that the prefix is valid.
+        let prefix_of_template = Path::new(prefix_from_template).to_string_lossy();
```
Comment (tertsdiepraam) [inline src/uu/mktemp/src/mktemp.rs:286]: Two more small things here:
1. The name is a bit confusing because it's different from `prefix_from_template` maybe those should just be the same? Or `prefix_from_template_string` or something like that?
2. Is it an `OsString`? Then we don't need to convert to a path before using `to_string_lossy()`. It could just be:
```rust
let prefix_from_template_string = prefix_from_template.to_string_lossy();
```

File: tests/by-util/test_mktemp.rs (hunk 2 above)
Comment (ZauJulio) [reply tests/by-util/test_mktemp.rs:578]: I believe it is a mistake, I checked the code and the flow that leads to the error is still correct. If ```-p``` is not passed as a parameter it will use a default OS temp directory, does not affect the problem.

Only the ```-t``` parameter is needed for the test as I understand it.

Comment (ZauJulio) [reply tests/by-util/test_mktemp.rs:578]: I tested it by changing the TEST_TEMPLATE9 with ```/``` instead of ```.```, it seems to be correct. Crashes and fail when I use  ```/```


```sh
running 1 test
test test_mktemp::test_prefix_template_separator ... FAILED

failures:

---- test_mktemp::test_prefix_template_separator stdout ----
run: /home/zau/Desktop/Projects/CONTRIB/coreutils/target/debug/coreutils mktemp -t a/XXXX
thread 'test_mktemp::test_prefix_template_separator' panicked at 'Command was expected to succeed.
stdout = 
 stderr = mktemp: invalid template, 'a/XXXX', contains directory separator
', tests/by-util/test_mktemp.rs:578:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

File: src/uu/mktemp/src/mktemp.rs (hunk 3 above)
Comment (ZauJulio) [reply src/uu/mktemp/src/mktemp.rs:286]: prefix_from_template is &str only, so the conversion is not even necessary, it could be even simpler, I'll upload the correction:

```rs
if options.treat_as_template && prefix_from_template.contains(MAIN_SEPARATOR) {
        return Err(MkTempError::PrefixContainsDirSeparator(options.template));
}
```

So simple, but I didn't realize it in my first contact with the language. Thanks for commenting, it made me study the code and the language more to be able to comment here (I hope I'm not wrong, although the tests are ok).

**Review by ZauJulio — COMMENTED** [review]
Apparently it was so simple, I'll pay more attention 😅

File: tests/by-util/test_mktemp.rs (hunk 2 above)
Comment (tertsdiepraam) [reply tests/by-util/test_mktemp.rs:578]: Interesting! Let's add both cases to the test suite. It never hurts to have more tests :)

File: src/uu/mktemp/src/mktemp.rs (hunk 3 above)
Comment (tertsdiepraam) [reply src/uu/mktemp/src/mktemp.rs]: Excellent!

File: tests/by-util/test_mktemp.rs (hunk 2 above)
Comment (ZauJulio) [reply tests/by-util/test_mktemp.rs:578]: Done, it was fun

Comment (tertsdiepraam) [reply tests/by-util/test_mktemp.rs:578]: Wait, I still don't get it. The case you've written succeeds on `main`. We do still need to verify that the fix fixed the issue, right?

For example something like this:
```rust
let (at, mut ucmd) = at_and_ucmd!();
at.mkdir("some");
at.mkdir("some/dir");
ucmd.args(&["-p", "some/dir", "-t", TEST_TEMPLATE9]).succeeds();
```

Comment (ZauJulio) [reply tests/by-util/test_mktemp.rs:578]: It's really strange that ```-p``` is needed for the test, I checked as I said and indeed the test passes the main. I think we can simplify it to:

```rust
new_ucmd!().args(&["-p", ".", "-t", TEST_TEMPLATE9]).succeeds();
```

Comment (ZauJulio) [reply tests/by-util/test_mktemp.rs:578]: I'll upload the test correction and check the why of this `-p`

**Comment by ZauJulio** [comment]
> There's a rustfmt issue, but otherwise it's good

show, I just uploaded the fmt correction

**Review by tertsdiepraam — APPROVED** [review]

**Comment by ZauJulio** [comment]
Hi @tertsdiepraam , I was wondering about the current state of PR, do you need anything else? If yes, how can I help you?
