### PR TITLE
Fixed panic in who > /dev/full

### LINKED ISSUE #10550: who > /dev/full panics

### PR DESCRIPTION
**Pull request by AntoxaBarin**
Fixes #10550 (copy of #11639)

### CODE REVIEW

File: tests/by-util/test_who.rs [hunk 1]
```diff
@@ -275,3 +275,20 @@ fn test_locale() {
         .succeeds()
         .stdout_is(&expected_stdout);
 }
+
+#[cfg(target_os = "linux")]
+#[test]
+fn test_piped_to_dev_full() {
```
Comment (cakebaker) [inline tests/by-util/test_who.rs:281]: The test passes even without the changes you made to `unix.rs`. Thus, I would make the asserts more strict by using `fails_with_code` or `stderr_is`.

Comment (AntoxaBarin) [reply tests/by-util/test_who.rs:281]: Done

**Comment by cakebaker** [comment]
Thanks for your PR!

**Comment by oech3** [comment]
Can we remove `Error flushing stdout: No space left on device (os error 28)` of 
```
$ who >/dev/full
who: No space left on device
Error flushing stdout: No space left on device (os error 28)
```
too?

**Comment by AntoxaBarin** [comment]
@oech3, I didn't see this error log on my Ubuntu 24.04, I'll take a look at this. What is your OS?

**Comment by oech3** [comment]
Arch
