### PR TITLE
du: fix `--time` behavior

### LINKED ISSUE #2279: du: different `--time` output from gnu
GNU:
```
$ /usr/bin/du --time=nope
/usr/bin/du: invalid argument ‘nope’ for ‘--time’
Valid arguments are:
  - ‘atime’, ‘access’, ‘use’
  - ‘ctime’, ‘status’
Try '/usr/bin/du --help' for more information.
```

us:
```
$ du --time=nope
du: error: invalid argument 'modified' for '--time'
    Valid arguments are:
      - 'accessed', 'created', 'modified'
    Try 'du --help' for more information.
```

Probably our `ls` is a good example:
```
$ ls --time=nope
error: 'nope' isn't a valid value for '--time=<field>'
	[possible values: access, atime, birth, creation, ctime, status, use]


USAGE:
    ls [OPTION]... [FILE]...

For more information try --help
```

### PR DESCRIPTION
**Pull request by syukronrm**
Closes #2279 

I also added `birth` and `creation` feature like `--time` behavior in `ls` command.

### CODE REVIEW

**Comment by sylvestre** [comment]
please add tests to cover this! thanks :)

File: src/uu/du/src/du.rs [hunk 1]
```diff
@@ -670,15 +668,16 @@ Try '{} --help' for more information.",
...
-                                        "modified" => stat.modified,
+                                        "ctime" | "status" => stat.modified,
+                                        "access" | "atime" | "use" => stat.accessed,
                                         _ => {
                                             show_error!(
-                                                "invalid argument 'modified' for '--time'
-    Valid arguments are:
-      - 'accessed', 'created', 'modified'
-    Try '{} --help' for more information.",
+                                                "invalid argument ‘{}’ for ‘--time’
```
Comment (sylvestre) [inline src/uu/du/src/du.rs:675]: hmm, it isn't possible to use https://docs.rs/clap/2.31.0/clap/struct.Arg.html#method.possible_values to avoid that?

**Review by sylvestre — COMMENTED** [review]
many thanks for the tests!

File: src/uu/du/src/du.rs (hunk 1 above)
Comment (syukronrm) [reply src/uu/du/src/du.rs:676]: Done.

Comment (sylvestre) [reply src/uu/du/src/du.rs:676]: I think this block isn't necessary anymore.
clap will reject unknown argument

**Comment by sylvestre** [comment]
please add them and just return an error message the arch isn't supported, no?

**Comment by syukronrm** [comment]
Yeah, I'll try it.

**Comment by syukronrm** [comment]
I think we have several options on the error handling:
1. Print the error if the program encounter the first unsupported file and exit 1 the program
2. Print the error if the arch isn't supported for each file, but this will return huge error messages, the program exit successfully
3. Print dash `-` on timestamp field if arch isn't supported
```
4	-	./Document
7000	-	./
```

What do you think?

**Comment by sylvestre** [comment]
what gnu is doing?

**Comment by syukronrm** [comment]
They don't have the `birth`/`creation` argument.

**Comment by sylvestre** [comment]
Just activate these values on supported platform then ? :)

File: src/uu/du/src/du.rs (hunk 1 above)
Comment (syukronrm) [reply src/uu/du/src/du.rs]: Updated

File: src/uu/du/src/du.rs [hunk 2]
```diff
@@ -670,19 +668,10 @@ Try '{} --help' for more information.",
...
-                                                "invalid argument 'modified' for '--time'
-    Valid arguments are:
-      - 'accessed', 'created', 'modified'
-    Try '{} --help' for more information.",
-                                                NAME
-                                            );
-                                            return 1;
-                                        }
+                                        "ctime" | "status" => stat.modified,
+                                        "access" | "atime" | "use" => stat.accessed,
```
Comment (sylvestre) [inline src/uu/du/src/du.rs:672]: please bring back created :)

Comment (syukronrm) [reply src/uu/du/src/du.rs:694]: Added

File: src/uu/du/src/du.rs [hunk 3]
```diff
@@ -129,18 +130,39 @@ impl Stat {
...
-// https://doc.rust-lang.org/std/os/windows/fs/trait.MetadataExt.html#tymethod.creation_time
+// https://doc.rust-lang.org/std/os/windows/fs/trait.MetadataExt.html#tymethod.last_access_time
 // "The returned 64-bit value [...] which represents the number of 100-nanosecond intervals since January 1, 1601 (UTC)."
+// "If the underlying filesystem does not support last access time, the returned value is 0."
 fn windows_time_to_unix_time(win_time: u64) -> u64 {
-    win_time / 10_000_000 - 11_644_473_600
+    match (win_time / 10_000_000).checked_sub(11_644_473_600) {
+        None => 0,
+        Some(t) => t,
+    }
```
[the remark this answers is not in the document]
Comment (tertsdiepraam) [reply src/uu/du/src/du.rs:148]: Sounds like a job for [saturating_sub](https://doc.rust-lang.org/std/primitive.u64.html#method.saturating_sub)!

File: src/uu/du/src/du.rs [hunk 4]
```diff
@@ -129,18 +130,39 @@ impl Stat {
...
+}
+
+#[cfg(windows)]
+fn windows_creation_time_to_unix_time(win_time: u64) -> Option<u64> {
+    match (win_time / 10_000_000).checked_sub(11_644_473_600) {
+        None => None,
+        Some(t) => Some(t),
+    }
```
Comment (tertsdiepraam) [inline src/uu/du/src/du.rs:156]: This match can be removed

File: src/uu/du/src/du.rs [hunk 5]
```diff
@@ -129,18 +130,39 @@ impl Stat {
...
+}
+
+#[cfg(not(windows))]
+fn birth_u64(meta: &Metadata) -> Option<u64> {
+    meta.created()
+        .ok()
+        .and_then(|t| t.duration_since(UNIX_EPOCH).ok())
+        .map(|e| Some(e.as_secs() as u64))
+        .unwrap_or_else(|| None)
```
Comment (tertsdiepraam) [inline src/uu/du/src/du.rs:165]: Very minor suggestion: you could use `and_then` instead of `map` and remove `unwrap_or_else`. Also, when the closure of `unwrap_or_else` is just a literal, you might want to use `unwrap_or` instead.

**Review by tertsdiepraam — COMMENTED** [review]
It looks really good! I just left a few minor suggestions

File: src/uu/du/src/du.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (syukronrm) [reply src/uu/du/src/du.rs:148]: Great! Should've read more the docs
