### PR TITLE
checksum: prepare further behavior fix with a rework

### LINKED ISSUE #6572: cksum: gets confused by base64 that happens to consist entirely of hexadecimal digits
The Base64 alphabet has, as the name suggests, 64 letters. 22 of these letters look like hexadecimal digits. That means that a random string of 8 Base64 letters (which encodes 6 bytes = 48 bits) has a chance of (22/64)^8 ~= 2^-12.3 to be a valid hexadecimal string. This means that generating a hash with an output length of 24 bits or a multiple thereof (e.g. SHA384 or Blake2b-48) might generate two different hexadecimal-looking hashes (of different lengths). This can cause all kinds of shenanigans with `cksum`, which has to detect/guess the encoding from the sums-file.

In particular, here is a case where it goes wrong:

```console
$ echo -n esq > foo.dat # The bytestring b"esq" is very special
$ cksum --algo=blake2b --length=48 --base64 foo.dat | tee foo.sums # Because the base64 *looks* like it's hexadecimal!
BLAKE2b-48 (foo.dat) = fc1f97C4
$ cksum --check foo.sums # GNU cksum takes no issue with this.
foo.dat: OK
$ cargo run -q cksum --check foo.sums # But uutils gets confused by this.
foo.dat: FAILED
cksum: WARNING: 1 computed checksum did NOT match
[$? = 1]
$ cargo run -q hashsum --b2sum --bits 48 --check foo.sums # hashsum *also* gets confused by this.
foo.dat: FAILED
hashsum: WARNING: 1 computed checksum did NOT match
[$? = 1]
```

There are probably more bugs like this.

Note that this is not specific to blake2b: With SHA384, it would probably require around 2^99 attempts to find a file that hashes to a digest that triggers this bug. For reference, the Bitcoin mining community computes about 2^60 hashes per second according to some sketchy website, which is good enough for this thought experiment. So it would require about 17734 years to find that file. Okay, nevermind, this bug doesn't realistically affect SHA384. (But theoretically it does.)

Found while reading #6500 (probably unrelated though).

CC @sylvestre, because you seem to be interested in this kind of bugs.

### PR DESCRIPTION
**Pull request by RenjiSann**
Now that #6782, #6793 and #6815 have landed, it is time to achieve the rework of `checksum.rs` started in #6654.

This will allow us to fix #6572, #6614 and #6653.

This PR mainly tries to split the massive `perform_checksum_verification` in smaller functions, and to get rid of the `&mut ChecksumResult` that is passed everywhere, which makes it very difficult to understand where the global state of the program is modified.

Also, it adds ignored tests for future features (it will prevent too many conflicts when rebasing future PRs on each other).

Next PRs will focus on reworking the algorithm detection behavior, in particular for blake2b size guessing,
Regex detection behavior which for now prevents us from encountering both hexa and base64 digits in the same file.

### CODE REVIEW

**Comment by RenjiSann** [comment]
Depending on the feedback on this discussion, I might split the `checksum.rs` file into several files (a bit like the initial PR #6654).
I'd like to move Error structs to `checksum/error.rs`, everything that's Algorithm-related to `checksum/algo.rs`, etc...

What do you think ?

File: src/uucore/src/lib/features/checksum.rs [hunk 1]
```diff
@@ -75,6 +75,55 @@ struct ChecksumResult {
     pub failed_open_file: i32,
 }
 
+enum LineCheckError {
```
Comment (sylvestre) [inline src/uucore/src/lib/features/checksum.rs:78]: please document this :)

File: src/uucore/src/lib/features/checksum.rs [hunk 2]
```diff
@@ -181,6 +230,24 @@ enum FileChecksumResult {
     CantOpen,
 }
 
+impl FileChecksumResult {
```
Comment (sylvestre) [inline src/uucore/src/lib/features/checksum.rs:233]: same, please document these functions

**Comment by cakebaker** [comment]
> I'd like to move Error structs to checksum/error.rs, everything that's Algorithm-related to checksum/algo.rs, etc...

> What do you think ?

It sounds good to me.

File: tests/by-util/test_cksum.rs [hunk 3]
```diff
@@ -1502,3 +1502,268 @@ mod check_utf8 {
...
+        .arg(at.subdir.join("foo.sums"))
+        .succeeds()
+        .stdout_is("foo.dat: OK\n");
+}
+
+/// This test checks that when a file contains several checksum lines
+/// with different encoding, the decoding still works.
+#[ignore = "not yet implemented"]
+#[test]
+fn test_check_mix_hexa_base64() {
```
Comment (cakebaker) [inline tests/by-util/test_cksum.rs:1572]:
```suggestion
fn test_check_mix_hex_base64() {
```

File: tests/by-util/test_cksum.rs [hunk 4]
```diff
@@ -1502,3 +1502,268 @@ mod check_utf8 {
...
+    let hex = "BLAKE2b-128 (foo2.dat) = 04136e24f85d470465c3db66e58ed56c";
+
+    let scene = TestScenario::new(util_name!());
+    let at = &scene.fixtures;
+
+    at.write("foo1.dat", "foo");
+    at.write("foo2.dat", "foo");
+
+    at.write("hex_b64", &format!("{}\n{}", hex, b64));
+    at.write("b64_hex", &format!("{}\n{}", b64, hex));
```
Comment (cakebaker) [inline tests/by-util/test_cksum.rs:1583]:
```suggestion
    at.write("hex_b64", &format!("{hex}\n{b64}"));
    at.write("b64_hex", &format!("{b64}\n{hex}"));
```

File: tests/by-util/test_cksum.rs [hunk 5]
```diff
@@ -1502,3 +1502,268 @@ mod check_utf8 {
...
+
+    scene
+        .ucmd()
+        .arg("--check")
+        .arg(at.subdir.join("hex_b64"))
+        .succeeds()
+        .stdout_is("foo2.dat: OK\nfoo1.dat: OK\n")
+        .no_stderr();
```
Comment (cakebaker) [inline tests/by-util/test_cksum.rs:1591]: You can simplify it with:
```suggestion
        .stdout_only("foo2.dat: OK\nfoo1.dat: OK\n");
```

File: tests/by-util/test_cksum.rs [hunk 6]
```diff
@@ -1502,3 +1502,268 @@ mod check_utf8 {
...
+            if !digest.ends_with('=') {
+                continue;
+            }
+
+            let mut line = output_format(algo, digest);
+            if line.ends_with("==") {
+                line = line.replace("==", "=");
+            } else if line.ends_with('=') {
+                line = line.replace('=', "");
+            }
```
Comment (cakebaker) [inline tests/by-util/test_cksum.rs:1730]: You can simplify it to:
```suggestion
            if line.ends_with('=') {
                line.pop();
            }
```

File: tests/by-util/test_cksum.rs [hunk 7]
```diff
@@ -1502,3 +1502,268 @@ mod check_utf8 {
...
+
+        for (algo, digest) in PAIRS {
+            if !digest.ends_with("==") {
+                continue;
+            }
+
+            let mut line = output_format(algo, digest);
+            if line.ends_with("==") {
+                line = line.replace("==", "");
+            }
```
Comment (cakebaker) [inline tests/by-util/test_cksum.rs:1757]: You can get rid of the `if` with:
```suggestion
            let line = output_format(algo, digest);
            let line = line.trim_end_matches("==");
```

**Comment by RenjiSann** [comment]
I've finally decided to keep the splitting in several files for later, because it's a nightmare to mix changes and file architecture when you have to rebase to keep a sound change history.

**Comment by RenjiSann** [comment]
I'm not sure why the macos test failed. Is it just flakey or have I touched something ?

**Comment by sylvestre** [comment]
flaky:

```
---- test_stat::test_stdin_pipe_fifo1 stdout ----
run: /Users/runner/work/coreutils/coreutils/target/aarch64-apple-darwin/debug/coreutils stat -
run: /Users/runner/work/coreutils/coreutils/target/aarch64-apple-darwin/debug/coreutils stat -L -
thread 'test_stat::test_stdin_pipe_fifo1' panicked at ''  File: -
  Size: 0         	Blocks: 0          IO Block: 512    weird file
Device: 4ef1bb9ch/1324465052d	Inode: 500453238   Links: 0
Access: (0660/?rw-rw----)  Uid: (  501/  runner)   Gid: (   20/   staff)
Access: 2024-10-25 15:48:53.191317902 +0000
Modify: 2024-10-25 15:48:53.191317902 +0000
Change: 2024-10-25 15:48:53.191317902 +0000
 Birth: 1970-01-01 00:00:00.000000000 +0000
' does not contain 'fifo'', tests/by-util/test_stat.rs:288:10
```

File: src/uucore/src/lib/features/checksum.rs [hunk 8]
```diff
@@ -75,6 +75,65 @@ struct ChecksumResult {
...
+/// could not proceed to digest comparison.
+enum LineCheckError {
+    /// a generic UError was encountered in sub-functions
+    UError(Box<dyn UError>),
+    /// the line is empty or is a comment
+    Skipped,
+    /// the line has a formatting error
+    ImproperlyFormatted,
+    /// the given file is not found, may be a directory
+    CantOpenFile(bool),
```
Comment (cakebaker) [inline src/uucore/src/lib/features/checksum.rs:88]: What's the meaning of the `bool` field?

File: src/uucore/src/lib/features/checksum.rs [hunk 9]
```diff
@@ -502,208 +590,243 @@ fn identify_algo_name_and_length(
...
+    line: &OsStr,
+    i: usize,
+    chosen_regex: &Regex,
+    is_algo_based_format: bool,
+    res: &mut ChecksumResult,
+    cli_algo_name: Option<&str>,
+    cli_algo_length: Option<usize>,
+    properly_formatted: &mut bool,
+    opts: ChecksumOptions,
+) -> Result<bool, LineCheckError> {
```
Comment (cakebaker) [inline src/uucore/src/lib/features/checksum.rs:611]: Why does the function return a `bool` in the success case?

Comment (RenjiSann) [reply src/uucore/src/lib/features/checksum.rs:611]: It's not a hard requirement. I just wanted to represent the Result as an answer to "could the digest comparison happen ?". So either everything is right and the comparison is done, thus returning `Ok()` with the result of the comparison, or the process failed beforehand and the `Err` is describing why.

File: src/uucore/src/lib/features/checksum.rs (hunk 8 above)
Comment (RenjiSann) [reply src/uucore/src/lib/features/checksum.rs:88]: Here, the boolean represents the fact that the error should increment the `failed_open_file` of the `ChecksumResult` structure.
Missing files will increment this file if the flag `--ignore-missing` was not provided (otherwise this is considered as a silent error), but a file actually being a directory will trigger an increment in any case

**Comment by RenjiSann** [comment]
@cakebaker Both of your comments address the details of implementation I came to when working on it.
If you come up with better alternatives, I'll gladly hear them ^^

File: src/uucore/src/lib/features/checksum.rs (hunk 8 above)
Comment (cakebaker) [reply src/uucore/src/lib/features/checksum.rs:88]: Hm, I think you are mixing concerns because the field is not about the error variant itself but about what the error handler should do if it encounters this error variant.

As the `CantOpenFile` variant is returned for three different reasons (`File::open()` fails, `metadata()` fails, file is a directory), it might make sense to have a variant for each reason.

File: src/uucore/src/lib/features/checksum.rs [hunk 10]
```diff
@@ -75,6 +75,65 @@ struct ChecksumResult {
...
+
+/// Represents an error that was encountered when processing a checksum file.
+#[allow(clippy::enum_variant_names)]
+enum FileCheckError {
+    /// a generic UError was encountered in sub-functions
+    UError(Box<dyn UError>),
+    /// the error does not stop the processing of next files
+    NonCriticalError,
+    /// the error must stop the run of the program
+    CriticalError,
```
Comment (cakebaker) [inline src/uucore/src/lib/features/checksum.rs:111]: These two variants are quite generic and don't provide much information about what went wrong. When I read the error handler on lines 826 - 830, I have to lookup what is considered a critical error and what not. However, I think it is the job of the error handler to do such a categorization.

File: src/uucore/src/lib/features/checksum.rs (hunk 9 above)
Comment (cakebaker) [reply src/uucore/src/lib/features/checksum.rs:611]: Hm, is the "could the digest comparison happen?" question even relevant in this context? Maybe I'm missing something.

File: src/uucore/src/lib/features/checksum.rs [hunk 11]
```diff
@@ -502,208 +590,243 @@ fn identify_algo_name_and_length(
...
+fn process_checksum_line(
+    filename_input: &OsStr,
+    line: &OsStr,
+    i: usize,
+    chosen_regex: &Regex,
+    is_algo_based_format: bool,
+    res: &mut ChecksumResult,
+    cli_algo_name: Option<&str>,
+    cli_algo_length: Option<usize>,
+    properly_formatted: &mut bool,
```
Comment (cakebaker) [inline src/uucore/src/lib/features/checksum.rs:609]: Is this argument necessary? There's already `LineCheckError::ImproperlyFormatted`.

**Review by cakebaker — COMMENTED** [review]
Overall good job with this refactoring :)

File: src/uucore/src/lib/features/checksum.rs (hunk 8 above)
Comment (RenjiSann) [reply src/uucore/src/lib/features/checksum.rs:88]: Sure, I can do this :+1:

File: src/uucore/src/lib/features/checksum.rs (hunk 11 above)
Comment (RenjiSann) [reply src/uucore/src/lib/features/checksum.rs:609]: With the way the program currently works, it is complicated to completely get rid of it.
I plan to get rid of it with the following PRs that will be in charge of fixing the tests that are added **but ignored** by this PR.

You can take a look at my previous, now deprecated, PR #6654, which fixed everything at once, but which was a pain to review.

File: src/uucore/src/lib/features/checksum.rs (hunk 9 above)
Comment (RenjiSann) [reply src/uucore/src/lib/features/checksum.rs:615]: I decided to go with this approach, but it's not a hard requirement. I will change the return type of the function to `Result<(), LineCheckError>` and add an error variant for failed digest comparison.

File: src/uucore/src/lib/features/checksum.rs (hunk 10 above)
Comment (RenjiSann) [reply src/uucore/src/lib/features/checksum.rs:117]: You're right, I will add more error variants to make it more understandable.

**Comment by RenjiSann** [comment]
Up @cakebaker 
Once this is done, I will move on and fix the tests I added :)

**Comment by RenjiSann** [comment]
This PR might have been forgotten, just pinging  maintainers for final review/merge @cakebaker  @sylvestre ^^

**Comment by sylvestre** [comment]
thanks for the ping :)
